-- CreateTable
CREATE TABLE "TBLINVENTORYRULE" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "productId" INTEGER NOT NULL,
    "warehouseId" INTEGER NOT NULL,
    "minQty" DECIMAL(28,8) NOT NULL DEFAULT 0,
    "maxQty" DECIMAL(28,8) NOT NULL DEFAULT 0,
    "reorderPoint" DECIMAL(28,8) NOT NULL DEFAULT 0,
    "reorderQty" DECIMAL(28,8) NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLINVENTORYRULE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLINVENTORYRULE_companyId_idx" ON "TBLINVENTORYRULE"("companyId");

-- CreateIndex
CREATE INDEX "TBLINVENTORYRULE_productId_idx" ON "TBLINVENTORYRULE"("productId");

-- CreateIndex
CREATE INDEX "TBLINVENTORYRULE_warehouseId_idx" ON "TBLINVENTORYRULE"("warehouseId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLINVENTORYRULE_companyId_productId_warehouseId_key" ON "TBLINVENTORYRULE"("companyId", "productId", "warehouseId");

-- AddForeignKey
ALTER TABLE "TBLINVENTORYRULE" ADD CONSTRAINT "TBLINVENTORYRULE_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLINVENTORYRULE" ADD CONSTRAINT "TBLINVENTORYRULE_productId_fkey" FOREIGN KEY ("productId") REFERENCES "TBLPRODUCT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLINVENTORYRULE" ADD CONSTRAINT "TBLINVENTORYRULE_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "TBLWAREHOUSE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

