-- CreateEnum
CREATE TYPE "MaterialLinkType" AS ENUM ('PRODUCT', 'PRODUCT_GROUP');

-- CreateEnum
CREATE TYPE "LocationLinkType" AS ENUM ('LOCATION', 'LOCATION_GROUP');

-- CreateTable
CREATE TABLE "TBLENTRYCONDITIONTYPE" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(100),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLENTRYCONDITIONTYPE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLEXITCONDITIONTYPE" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(100),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLEXITCONDITIONTYPE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLROUTINGTYPE" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(100),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLROUTINGTYPE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLROUTINGRULE" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "routingTypeId" INTEGER,
    "materialLinkType" "MaterialLinkType" NOT NULL,
    "materialLinkCode" INTEGER NOT NULL,
    "locationLinkType" "LocationLinkType" NOT NULL,
    "locationLinkCode" INTEGER NOT NULL,
    "priority" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLROUTINGRULE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLENTRYCONDITIONTYPE_companyId_idx" ON "TBLENTRYCONDITIONTYPE"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLENTRYCONDITIONTYPE_companyId_code_key" ON "TBLENTRYCONDITIONTYPE"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLEXITCONDITIONTYPE_companyId_idx" ON "TBLEXITCONDITIONTYPE"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLEXITCONDITIONTYPE_companyId_code_key" ON "TBLEXITCONDITIONTYPE"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLROUTINGTYPE_companyId_idx" ON "TBLROUTINGTYPE"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLROUTINGTYPE_companyId_code_key" ON "TBLROUTINGTYPE"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLROUTINGRULE_companyId_idx" ON "TBLROUTINGRULE"("companyId");

-- CreateIndex
CREATE INDEX "TBLROUTINGRULE_materialLinkCode_idx" ON "TBLROUTINGRULE"("materialLinkCode");

-- AddForeignKey
ALTER TABLE "TBLENTRYCONDITIONTYPE" ADD CONSTRAINT "TBLENTRYCONDITIONTYPE_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLEXITCONDITIONTYPE" ADD CONSTRAINT "TBLEXITCONDITIONTYPE_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLROUTINGTYPE" ADD CONSTRAINT "TBLROUTINGTYPE_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLROUTINGRULE" ADD CONSTRAINT "TBLROUTINGRULE_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLROUTINGRULE" ADD CONSTRAINT "TBLROUTINGRULE_routingTypeId_fkey" FOREIGN KEY ("routingTypeId") REFERENCES "TBLROUTINGTYPE"("id") ON DELETE SET NULL ON UPDATE CASCADE;

