-- CreateEnum
CREATE TYPE "PartnerType" AS ENUM ('CUSTOMER', 'SUPPLIER', 'BOTH');

-- AlterTable
ALTER TABLE "TBLDOCUMENT" ADD COLUMN     "partnerId" INTEGER;

-- AlterTable
ALTER TABLE "TBLUSER" ADD COLUMN     "companyId" INTEGER;

-- CreateTable
CREATE TABLE "TBLBUSINESSPARTNER" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(40) NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "type" "PartnerType" NOT NULL DEFAULT 'CUSTOMER',
    "taxNumber" VARCHAR(20),
    "phone" VARCHAR(20),
    "email" VARCHAR(150),
    "city" VARCHAR(60),
    "address" VARCHAR(255),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLBUSINESSPARTNER_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLBUSINESSPARTNER_companyId_idx" ON "TBLBUSINESSPARTNER"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLBUSINESSPARTNER_companyId_code_key" ON "TBLBUSINESSPARTNER"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLDOCUMENT_partnerId_idx" ON "TBLDOCUMENT"("partnerId");

-- CreateIndex
CREATE INDEX "TBLUSER_companyId_idx" ON "TBLUSER"("companyId");

-- AddForeignKey
ALTER TABLE "TBLUSER" ADD CONSTRAINT "TBLUSER_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLBUSINESSPARTNER" ADD CONSTRAINT "TBLBUSINESSPARTNER_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENT" ADD CONSTRAINT "TBLDOCUMENT_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "TBLBUSINESSPARTNER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

