-- Entegrasyon tanım ekranları (StokBar paritesi): Okuma Sorgu (+kolon dönüşüm) + Yazma Parametre + XML Convert
-- Legacy: TBLSBENTEGRASYONSORGU / TBLSBENTEGRASYONSORGUKOLONDONUSUM / TBLSBENTYAZMAPARAMETRE / TBLSBENTEGRASYONXMLCONVERT

CREATE TABLE wms."TBLINTEGRATIONQUERY" (
  "id" SERIAL PRIMARY KEY,
  "companyId" INTEGER NOT NULL,
  "packageId" INTEGER NOT NULL,
  "queryType" VARCHAR(20) NOT NULL,
  "query" TEXT NOT NULL,
  "ordering" VARCHAR(300),
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "TBLINTEGRATIONQUERY_packageId_fkey" FOREIGN KEY ("packageId")
    REFERENCES wms."TBLINTEGRATIONPACKAGE"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "TBLINTEGRATIONQUERY_companyId_idx" ON wms."TBLINTEGRATIONQUERY"("companyId");
CREATE INDEX "TBLINTEGRATIONQUERY_packageId_idx" ON wms."TBLINTEGRATIONQUERY"("packageId");

CREATE TABLE wms."TBLINTEGRATIONQUERYCOLUMN" (
  "id" SERIAL PRIMARY KEY,
  "companyId" INTEGER NOT NULL,
  "queryId" INTEGER NOT NULL,
  "sourceColumn" VARCHAR(100) NOT NULL,
  "targetField" VARCHAR(40) NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "TBLINTEGRATIONQUERYCOLUMN_queryId_fkey" FOREIGN KEY ("queryId")
    REFERENCES wms."TBLINTEGRATIONQUERY"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "TBLINTEGRATIONQUERYCOLUMN_companyId_idx" ON wms."TBLINTEGRATIONQUERYCOLUMN"("companyId");
CREATE INDEX "TBLINTEGRATIONQUERYCOLUMN_queryId_idx" ON wms."TBLINTEGRATIONQUERYCOLUMN"("queryId");

CREATE TABLE wms."TBLINTEGRATIONWRITEPARAM" (
  "id" SERIAL PRIMARY KEY,
  "companyId" INTEGER NOT NULL,
  "facilityId" INTEGER,
  "conversionId" INTEGER,
  "addressId" INTEGER NOT NULL,
  "bulkAction" BOOLEAN NOT NULL DEFAULT false,
  "batchTransfer" BOOLEAN NOT NULL DEFAULT false,
  "palletBatchTransfer" BOOLEAN NOT NULL DEFAULT false,
  "serialTransfer" BOOLEAN NOT NULL DEFAULT false,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "TBLINTEGRATIONWRITEPARAM_addressId_fkey" FOREIGN KEY ("addressId")
    REFERENCES wms."TBLINTEGRATIONADDRESS"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "TBLINTEGRATIONWRITEPARAM_companyId_idx" ON wms."TBLINTEGRATIONWRITEPARAM"("companyId");
CREATE INDEX "TBLINTEGRATIONWRITEPARAM_addressId_idx" ON wms."TBLINTEGRATIONWRITEPARAM"("addressId");

CREATE TABLE wms."TBLINTEGRATIONXMLCONVERT" (
  "id" SERIAL PRIMARY KEY,
  "companyId" INTEGER NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "xmlTemplate" TEXT,
  "xslTemplate" TEXT,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE INDEX "TBLINTEGRATIONXMLCONVERT_companyId_idx" ON wms."TBLINTEGRATIONXMLCONVERT"("companyId");
