-- AlterTable
ALTER TABLE "TBLUSER" ADD COLUMN     "alias" VARCHAR(60),
ADD COLUMN     "cannotChangePassword" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isApproved" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mustChangePassword" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "passwordNeverExpires" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone" VARCHAR(30),
ADD COLUMN     "userType" VARCHAR(20),
ADD COLUMN     "validUntil" DATE;

-- CreateTable
CREATE TABLE "TBLUSERSCREENRIGHT" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "userId" INTEGER,
    "groupId" INTEGER,
    "resource" VARCHAR(60) NOT NULL,
    "canView" BOOLEAN NOT NULL DEFAULT true,
    "canAdd" BOOLEAN NOT NULL DEFAULT true,
    "canEdit" BOOLEAN NOT NULL DEFAULT true,
    "canDelete" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLUSERSCREENRIGHT_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLUSERSCREENRIGHT_companyId_idx" ON "TBLUSERSCREENRIGHT"("companyId");

-- CreateIndex
CREATE INDEX "TBLUSERSCREENRIGHT_userId_idx" ON "TBLUSERSCREENRIGHT"("userId");

-- CreateIndex
CREATE INDEX "TBLUSERSCREENRIGHT_groupId_idx" ON "TBLUSERSCREENRIGHT"("groupId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLUSERSCREENRIGHT_userId_resource_key" ON "TBLUSERSCREENRIGHT"("userId", "resource");

-- CreateIndex
CREATE UNIQUE INDEX "TBLUSERSCREENRIGHT_groupId_resource_key" ON "TBLUSERSCREENRIGHT"("groupId", "resource");

-- AddForeignKey
ALTER TABLE "TBLUSERSCREENRIGHT" ADD CONSTRAINT "TBLUSERSCREENRIGHT_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLUSERSCREENRIGHT" ADD CONSTRAINT "TBLUSERSCREENRIGHT_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TBLUSER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLUSERSCREENRIGHT" ADD CONSTRAINT "TBLUSERSCREENRIGHT_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "TBLUSERGROUP"("id") ON DELETE CASCADE ON UPDATE CASCADE;

