-- Faz 3: Belge durum geçiş geçmişi (audit). Additive — mevcut tablolara dokunmaz.
CREATE TABLE wms."TBLDOCUMENTSTATUSHISTORY" (
  "id" SERIAL NOT NULL,
  "companyId" INTEGER NOT NULL,
  "documentId" INTEGER NOT NULL,
  "fromCode" VARCHAR(20),
  "toCode" VARCHAR(20) NOT NULL,
  "source" VARCHAR(40) NOT NULL,
  "userId" INTEGER,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "TBLDOCUMENTSTATUSHISTORY_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "TBLDOCUMENTSTATUSHISTORY_companyId_idx" ON wms."TBLDOCUMENTSTATUSHISTORY"("companyId");
CREATE INDEX "TBLDOCUMENTSTATUSHISTORY_documentId_idx" ON wms."TBLDOCUMENTSTATUSHISTORY"("documentId");
