-- CreateTable
CREATE TABLE "TBLOPERATIONTYPESTATUS" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "operationTypeId" INTEGER NOT NULL,
    "sourceStatusId" INTEGER,
    "targetStatusId" INTEGER NOT NULL,
    "sortOrder" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLOPERATIONTYPESTATUS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLOPERATIONTYPELOCATION" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "operationTypeId" INTEGER NOT NULL,
    "sourceLocationId" INTEGER,
    "targetLocationId" INTEGER,
    "fixLocation" BOOLEAN NOT NULL DEFAULT false,
    "sortOrder" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLOPERATIONTYPELOCATION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLOPERATIONTYPEREASON" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "operationTypeId" INTEGER NOT NULL,
    "reasonId" INTEGER NOT NULL,
    "sortOrder" INTEGER,
    "isAutomatic" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLOPERATIONTYPEREASON_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLOPERATIONTYPEPALLETTYPE" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "operationTypeId" INTEGER NOT NULL,
    "palletTypeId" INTEGER NOT NULL,
    "innerPalletTypeId" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLOPERATIONTYPEPALLETTYPE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPESTATUS_companyId_idx" ON "TBLOPERATIONTYPESTATUS"("companyId");

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPESTATUS_operationTypeId_idx" ON "TBLOPERATIONTYPESTATUS"("operationTypeId");

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPELOCATION_companyId_idx" ON "TBLOPERATIONTYPELOCATION"("companyId");

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPELOCATION_operationTypeId_idx" ON "TBLOPERATIONTYPELOCATION"("operationTypeId");

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPEREASON_companyId_idx" ON "TBLOPERATIONTYPEREASON"("companyId");

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPEREASON_operationTypeId_idx" ON "TBLOPERATIONTYPEREASON"("operationTypeId");

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPEPALLETTYPE_companyId_idx" ON "TBLOPERATIONTYPEPALLETTYPE"("companyId");

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPEPALLETTYPE_operationTypeId_idx" ON "TBLOPERATIONTYPEPALLETTYPE"("operationTypeId");

-- AddForeignKey
ALTER TABLE "TBLOPERATIONTYPESTATUS" ADD CONSTRAINT "TBLOPERATIONTYPESTATUS_operationTypeId_fkey" FOREIGN KEY ("operationTypeId") REFERENCES "TBLOPERATIONTYPE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLOPERATIONTYPELOCATION" ADD CONSTRAINT "TBLOPERATIONTYPELOCATION_operationTypeId_fkey" FOREIGN KEY ("operationTypeId") REFERENCES "TBLOPERATIONTYPE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLOPERATIONTYPEREASON" ADD CONSTRAINT "TBLOPERATIONTYPEREASON_operationTypeId_fkey" FOREIGN KEY ("operationTypeId") REFERENCES "TBLOPERATIONTYPE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLOPERATIONTYPEPALLETTYPE" ADD CONSTRAINT "TBLOPERATIONTYPEPALLETTYPE_operationTypeId_fkey" FOREIGN KEY ("operationTypeId") REFERENCES "TBLOPERATIONTYPE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

