-- CreateEnum
CREATE TYPE "HandheldScreenType" AS ENUM ('RECEIPT', 'PICK', 'COUNT', 'STOCK');

-- CreateTable
CREATE TABLE "TBLHANDHELDMENUGROUP" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "facilityId" INTEGER,
    "code" VARCHAR(40) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLHANDHELDMENUGROUP_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLHANDHELDMENUITEM" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "groupId" INTEGER NOT NULL,
    "code" VARCHAR(40) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "screenType" "HandheldScreenType" NOT NULL,
    "operationTypeId" INTEGER,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLHANDHELDMENUITEM_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLHANDHELDMENUGROUP_companyId_idx" ON "TBLHANDHELDMENUGROUP"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLHANDHELDMENUGROUP_companyId_code_key" ON "TBLHANDHELDMENUGROUP"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLHANDHELDMENUITEM_companyId_idx" ON "TBLHANDHELDMENUITEM"("companyId");

-- CreateIndex
CREATE INDEX "TBLHANDHELDMENUITEM_groupId_idx" ON "TBLHANDHELDMENUITEM"("groupId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLHANDHELDMENUITEM_companyId_code_key" ON "TBLHANDHELDMENUITEM"("companyId", "code");

-- AddForeignKey
ALTER TABLE "TBLHANDHELDMENUITEM" ADD CONSTRAINT "TBLHANDHELDMENUITEM_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "TBLHANDHELDMENUGROUP"("id") ON DELETE CASCADE ON UPDATE CASCADE;

