-- AlterTable
ALTER TABLE "TBLUSERAUTHORIZATION" ADD COLUMN     "groupId" INTEGER,
ALTER COLUMN "userId" DROP NOT NULL;

-- CreateTable
CREATE TABLE "TBLUSERGROUP" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(40) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLUSERGROUP_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLUSERGROUPMEMBER" (
    "userId" INTEGER NOT NULL,
    "groupId" INTEGER NOT NULL,

    CONSTRAINT "TBLUSERGROUPMEMBER_pkey" PRIMARY KEY ("userId","groupId")
);

-- CreateIndex
CREATE INDEX "TBLUSERGROUP_companyId_idx" ON "TBLUSERGROUP"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLUSERGROUP_companyId_code_key" ON "TBLUSERGROUP"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLUSERGROUPMEMBER_groupId_idx" ON "TBLUSERGROUPMEMBER"("groupId");

-- CreateIndex
CREATE INDEX "TBLUSERAUTHORIZATION_groupId_idx" ON "TBLUSERAUTHORIZATION"("groupId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLUSERAUTHORIZATION_groupId_scopeType_referenceId_key" ON "TBLUSERAUTHORIZATION"("groupId", "scopeType", "referenceId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLUSERAUTHORIZATION_groupId_scopeType_referenceCode_key" ON "TBLUSERAUTHORIZATION"("groupId", "scopeType", "referenceCode");

-- AddForeignKey
ALTER TABLE "TBLUSERAUTHORIZATION" ADD CONSTRAINT "TBLUSERAUTHORIZATION_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "TBLUSERGROUP"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLUSERGROUP" ADD CONSTRAINT "TBLUSERGROUP_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLUSERGROUPMEMBER" ADD CONSTRAINT "TBLUSERGROUPMEMBER_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TBLUSER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLUSERGROUPMEMBER" ADD CONSTRAINT "TBLUSERGROUPMEMBER_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "TBLUSERGROUP"("id") ON DELETE CASCADE ON UPDATE CASCADE;

