-- AlterTable
ALTER TABLE "sales"."TBLSALESORDERLINE" ADD COLUMN     "allocatedQty" DECIMAL(28,8) NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "sales"."TBLSALESALLOCATION" (
    "id" SERIAL NOT NULL,
    "orderLineId" INTEGER NOT NULL,
    "stockId" INTEGER NOT NULL,
    "quantity" DECIMAL(28,8) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLSALESALLOCATION_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLSALESALLOCATION_orderLineId_idx" ON "sales"."TBLSALESALLOCATION"("orderLineId");

-- CreateIndex
CREATE INDEX "TBLSALESALLOCATION_stockId_idx" ON "sales"."TBLSALESALLOCATION"("stockId");

-- AddForeignKey
ALTER TABLE "sales"."TBLSALESALLOCATION" ADD CONSTRAINT "TBLSALESALLOCATION_orderLineId_fkey" FOREIGN KEY ("orderLineId") REFERENCES "sales"."TBLSALESORDERLINE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

