-- Entegrasyon Paketi + Adresi (legacy TBLSBENTEGRASYONPAKET / TBLSBENTEGRASYONADRES)
CREATE TYPE wms."IntegrationPackageType" AS ENUM ('GENERIC_REST', 'NETSIS_REST', 'LOGO_REST');

CREATE TABLE wms."TBLINTEGRATIONPACKAGE" (
  "id" SERIAL PRIMARY KEY,
  "companyId" INTEGER NOT NULL REFERENCES wms."TBLCOMPANY"("id"),
  "code" VARCHAR(40) NOT NULL,
  "name" VARCHAR(150),
  "packageType" wms."IntegrationPackageType" NOT NULL DEFAULT 'GENERIC_REST',
  "baseUrl" VARCHAR(300),
  "username" VARCHAR(100),
  "password" VARCHAR(200),
  "clientId" VARCHAR(150),
  "clientSecret" VARCHAR(200),
  "dbType" VARCHAR(30),
  "dbName" VARCHAR(100),
  "dbUser" VARCHAR(100),
  "dbPassword" VARCHAR(200),
  "branchCode" VARCHAR(20),
  "firmNr" VARCHAR(10),
  "periodNr" VARCHAR(10),
  "logging" BOOLEAN NOT NULL DEFAULT false,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "TBLINTEGRATIONPACKAGE_companyId_code_key" ON wms."TBLINTEGRATIONPACKAGE"("companyId","code");
CREATE INDEX "TBLINTEGRATIONPACKAGE_companyId_idx" ON wms."TBLINTEGRATIONPACKAGE"("companyId");

CREATE TABLE wms."TBLINTEGRATIONADDRESS" (
  "id" SERIAL PRIMARY KEY,
  "companyId" INTEGER NOT NULL,
  "packageId" INTEGER NOT NULL REFERENCES wms."TBLINTEGRATIONPACKAGE"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "operationTypeId" INTEGER,
  "facilityId" INTEGER,
  "name" VARCHAR(150),
  "path" VARCHAR(300) NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "onCreate" BOOLEAN NOT NULL DEFAULT false,
  "onFirstScan" BOOLEAN NOT NULL DEFAULT false,
  "onConfirm" BOOLEAN NOT NULL DEFAULT false,
  "onComplete" BOOLEAN NOT NULL DEFAULT false,
  "logging" BOOLEAN NOT NULL DEFAULT false,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE INDEX "TBLINTEGRATIONADDRESS_companyId_idx" ON wms."TBLINTEGRATIONADDRESS"("companyId");
CREATE INDEX "TBLINTEGRATIONADDRESS_packageId_idx" ON wms."TBLINTEGRATIONADDRESS"("packageId");
CREATE INDEX "TBLINTEGRATIONADDRESS_operationTypeId_idx" ON wms."TBLINTEGRATIONADDRESS"("operationTypeId");
