-- CreateTable
CREATE TABLE "TBLDOCUMENTASSIGNMENT" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "documentId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,
    "note" VARCHAR(200),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLDOCUMENTASSIGNMENT_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLDOCUMENTASSIGNMENT_companyId_idx" ON "TBLDOCUMENTASSIGNMENT"("companyId");

-- CreateIndex
CREATE INDEX "TBLDOCUMENTASSIGNMENT_documentId_idx" ON "TBLDOCUMENTASSIGNMENT"("documentId");

-- CreateIndex
CREATE INDEX "TBLDOCUMENTASSIGNMENT_userId_idx" ON "TBLDOCUMENTASSIGNMENT"("userId");

