-- CreateEnum
CREATE TYPE "MovementDirection" AS ENUM ('INBOUND', 'OUTBOUND', 'INTERNAL');

-- DropForeignKey
ALTER TABLE "TBLDOCUMENTLINE" DROP CONSTRAINT "TBLDOCUMENTLINE_locationId_fkey";

-- DropIndex
DROP INDEX "TBLDOCUMENT_createdById_idx";

-- DropIndex
DROP INDEX "TBLDOCUMENT_documentNo_key";

-- DropIndex
DROP INDEX "TBLDOCUMENT_type_status_idx";

-- DropIndex
DROP INDEX "TBLDOCUMENTLINE_locationId_idx";

-- AlterTable
ALTER TABLE "TBLDOCUMENT" DROP COLUMN "type",
ADD COLUMN     "companyId" INTEGER NOT NULL,
ADD COLUMN     "completedAt" TIMESTAMP(3),
ADD COLUMN     "operationTypeId" INTEGER NOT NULL;

-- AlterTable
ALTER TABLE "TBLDOCUMENTLINE" DROP COLUMN "locationId",
ADD COLUMN     "batchNo" VARCHAR(100),
ADD COLUMN     "palletId" INTEGER,
ADD COLUMN     "serialNo" VARCHAR(100),
ADD COLUMN     "sourceLocationId" INTEGER,
ADD COLUMN     "sourceStatusId" INTEGER,
ADD COLUMN     "targetLocationId" INTEGER,
ADD COLUMN     "targetStatusId" INTEGER,
ADD COLUMN     "unitId" INTEGER NOT NULL,
ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(28,8);

-- DropEnum
DROP TYPE "DocumentType";

-- CreateTable
CREATE TABLE "TBLOPERATIONTYPE" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "direction" "MovementDirection" NOT NULL,
    "affectsStock" BOOLEAN NOT NULL DEFAULT true,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLOPERATIONTYPE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPE_companyId_idx" ON "TBLOPERATIONTYPE"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLOPERATIONTYPE_companyId_code_key" ON "TBLOPERATIONTYPE"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLDOCUMENT_companyId_idx" ON "TBLDOCUMENT"("companyId");

-- CreateIndex
CREATE INDEX "TBLDOCUMENT_operationTypeId_idx" ON "TBLDOCUMENT"("operationTypeId");

-- CreateIndex
CREATE INDEX "TBLDOCUMENT_status_idx" ON "TBLDOCUMENT"("status");

-- CreateIndex
CREATE UNIQUE INDEX "TBLDOCUMENT_companyId_documentNo_key" ON "TBLDOCUMENT"("companyId", "documentNo");

-- CreateIndex
CREATE INDEX "TBLDOCUMENTLINE_sourceLocationId_idx" ON "TBLDOCUMENTLINE"("sourceLocationId");

-- CreateIndex
CREATE INDEX "TBLDOCUMENTLINE_targetLocationId_idx" ON "TBLDOCUMENTLINE"("targetLocationId");

-- AddForeignKey
ALTER TABLE "TBLOPERATIONTYPE" ADD CONSTRAINT "TBLOPERATIONTYPE_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENT" ADD CONSTRAINT "TBLDOCUMENT_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENT" ADD CONSTRAINT "TBLDOCUMENT_operationTypeId_fkey" FOREIGN KEY ("operationTypeId") REFERENCES "TBLOPERATIONTYPE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTLINE" ADD CONSTRAINT "TBLDOCUMENTLINE_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "TBLUNIT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTLINE" ADD CONSTRAINT "TBLDOCUMENTLINE_sourceLocationId_fkey" FOREIGN KEY ("sourceLocationId") REFERENCES "TBLLOCATION"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTLINE" ADD CONSTRAINT "TBLDOCUMENTLINE_targetLocationId_fkey" FOREIGN KEY ("targetLocationId") REFERENCES "TBLLOCATION"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTLINE" ADD CONSTRAINT "TBLDOCUMENTLINE_sourceStatusId_fkey" FOREIGN KEY ("sourceStatusId") REFERENCES "TBLSTATUS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTLINE" ADD CONSTRAINT "TBLDOCUMENTLINE_targetStatusId_fkey" FOREIGN KEY ("targetStatusId") REFERENCES "TBLSTATUS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTLINE" ADD CONSTRAINT "TBLDOCUMENTLINE_palletId_fkey" FOREIGN KEY ("palletId") REFERENCES "TBLPALLET"("id") ON DELETE SET NULL ON UPDATE CASCADE;

