-- CreateTable
CREATE TABLE "TBLPRODUCTFACILITY" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "productId" INTEGER NOT NULL,
    "facilityId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TBLPRODUCTFACILITY_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLPRODUCTFACILITY_companyId_idx" ON "TBLPRODUCTFACILITY"("companyId");

-- CreateIndex
CREATE INDEX "TBLPRODUCTFACILITY_productId_idx" ON "TBLPRODUCTFACILITY"("productId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLPRODUCTFACILITY_productId_facilityId_key" ON "TBLPRODUCTFACILITY"("productId", "facilityId");

-- AddForeignKey
ALTER TABLE "TBLPRODUCTFACILITY" ADD CONSTRAINT "TBLPRODUCTFACILITY_productId_fkey" FOREIGN KEY ("productId") REFERENCES "TBLPRODUCT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

