-- CreateEnum
CREATE TYPE "LocationType" AS ENUM ('SHELF', 'FLOOR', 'RECEIVING', 'SHIPPING', 'STAGING', 'QUARANTINE');

-- CreateEnum
CREATE TYPE "DocumentType" AS ENUM ('RECEIPT', 'SHIPMENT', 'TRANSFER', 'ADJUSTMENT', 'COUNT');

-- CreateEnum
CREATE TYPE "DocumentStatus" AS ENUM ('DRAFT', 'CONFIRMED', 'COMPLETED', 'CANCELLED');

-- CreateTable
CREATE TABLE "TBLUSER" (
    "id" SERIAL NOT NULL,
    "username" VARCHAR(50) NOT NULL,
    "email" VARCHAR(150) NOT NULL,
    "passwordHash" VARCHAR(255) NOT NULL,
    "fullName" VARCHAR(150) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastLoginAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLUSER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLROLE" (
    "id" SERIAL NOT NULL,
    "code" VARCHAR(40) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLROLE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLUSERROLE" (
    "userId" INTEGER NOT NULL,
    "roleId" INTEGER NOT NULL,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TBLUSERROLE_pkey" PRIMARY KEY ("userId","roleId")
);

-- CreateTable
CREATE TABLE "TBLLOCATION" (
    "id" SERIAL NOT NULL,
    "warehouseId" INTEGER NOT NULL,
    "code" VARCHAR(40) NOT NULL,
    "name" VARCHAR(100),
    "type" "LocationType" NOT NULL DEFAULT 'SHELF',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLLOCATION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLUNIT" (
    "id" SERIAL NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLUNIT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLPRODUCT" (
    "id" SERIAL NOT NULL,
    "code" VARCHAR(40) NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "barcode" VARCHAR(50),
    "unitId" INTEGER NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLPRODUCT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLDOCUMENT" (
    "id" SERIAL NOT NULL,
    "documentNo" VARCHAR(40) NOT NULL,
    "type" "DocumentType" NOT NULL,
    "status" "DocumentStatus" NOT NULL DEFAULT 'DRAFT',
    "warehouseId" INTEGER NOT NULL,
    "createdById" INTEGER NOT NULL,
    "documentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "note" VARCHAR(500),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLDOCUMENT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLDOCUMENTLINE" (
    "id" SERIAL NOT NULL,
    "documentId" INTEGER NOT NULL,
    "lineNo" INTEGER NOT NULL,
    "productId" INTEGER NOT NULL,
    "locationId" INTEGER,
    "quantity" DECIMAL(18,3) NOT NULL,
    "note" VARCHAR(255),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLDOCUMENTLINE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TBLUSER_username_key" ON "TBLUSER"("username");

-- CreateIndex
CREATE UNIQUE INDEX "TBLUSER_email_key" ON "TBLUSER"("email");

-- CreateIndex
CREATE UNIQUE INDEX "TBLROLE_code_key" ON "TBLROLE"("code");

-- CreateIndex
CREATE INDEX "TBLUSERROLE_roleId_idx" ON "TBLUSERROLE"("roleId");

-- CreateIndex
CREATE INDEX "TBLLOCATION_warehouseId_idx" ON "TBLLOCATION"("warehouseId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLLOCATION_warehouseId_code_key" ON "TBLLOCATION"("warehouseId", "code");

-- CreateIndex
CREATE UNIQUE INDEX "TBLUNIT_code_key" ON "TBLUNIT"("code");

-- CreateIndex
CREATE UNIQUE INDEX "TBLPRODUCT_code_key" ON "TBLPRODUCT"("code");

-- CreateIndex
CREATE INDEX "TBLPRODUCT_unitId_idx" ON "TBLPRODUCT"("unitId");

-- CreateIndex
CREATE INDEX "TBLPRODUCT_barcode_idx" ON "TBLPRODUCT"("barcode");

-- CreateIndex
CREATE UNIQUE INDEX "TBLDOCUMENT_documentNo_key" ON "TBLDOCUMENT"("documentNo");

-- CreateIndex
CREATE INDEX "TBLDOCUMENT_warehouseId_idx" ON "TBLDOCUMENT"("warehouseId");

-- CreateIndex
CREATE INDEX "TBLDOCUMENT_createdById_idx" ON "TBLDOCUMENT"("createdById");

-- CreateIndex
CREATE INDEX "TBLDOCUMENT_type_status_idx" ON "TBLDOCUMENT"("type", "status");

-- CreateIndex
CREATE INDEX "TBLDOCUMENTLINE_documentId_idx" ON "TBLDOCUMENTLINE"("documentId");

-- CreateIndex
CREATE INDEX "TBLDOCUMENTLINE_productId_idx" ON "TBLDOCUMENTLINE"("productId");

-- CreateIndex
CREATE INDEX "TBLDOCUMENTLINE_locationId_idx" ON "TBLDOCUMENTLINE"("locationId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLDOCUMENTLINE_documentId_lineNo_key" ON "TBLDOCUMENTLINE"("documentId", "lineNo");

-- AddForeignKey
ALTER TABLE "TBLUSERROLE" ADD CONSTRAINT "TBLUSERROLE_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TBLUSER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLUSERROLE" ADD CONSTRAINT "TBLUSERROLE_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "TBLROLE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLLOCATION" ADD CONSTRAINT "TBLLOCATION_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "TBLWAREHOUSE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPRODUCT" ADD CONSTRAINT "TBLPRODUCT_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "TBLUNIT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENT" ADD CONSTRAINT "TBLDOCUMENT_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "TBLWAREHOUSE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENT" ADD CONSTRAINT "TBLDOCUMENT_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "TBLUSER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTLINE" ADD CONSTRAINT "TBLDOCUMENTLINE_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "TBLDOCUMENT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTLINE" ADD CONSTRAINT "TBLDOCUMENTLINE_productId_fkey" FOREIGN KEY ("productId") REFERENCES "TBLPRODUCT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTLINE" ADD CONSTRAINT "TBLDOCUMENTLINE_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "TBLLOCATION"("id") ON DELETE SET NULL ON UPDATE CASCADE;
