-- CreateTable
CREATE TABLE "TBLLOCATIONGROUPLINK" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "locationId" INTEGER NOT NULL,
    "locationGroupId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TBLLOCATIONGROUPLINK_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLLOCATIONGROUPLINK_companyId_idx" ON "TBLLOCATIONGROUPLINK"("companyId");

-- CreateIndex
CREATE INDEX "TBLLOCATIONGROUPLINK_locationGroupId_idx" ON "TBLLOCATIONGROUPLINK"("locationGroupId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLLOCATIONGROUPLINK_locationId_locationGroupId_key" ON "TBLLOCATIONGROUPLINK"("locationId", "locationGroupId");

-- AddForeignKey
ALTER TABLE "TBLLOCATIONGROUPLINK" ADD CONSTRAINT "TBLLOCATIONGROUPLINK_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "TBLLOCATION"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLLOCATIONGROUPLINK" ADD CONSTRAINT "TBLLOCATIONGROUPLINK_locationGroupId_fkey" FOREIGN KEY ("locationGroupId") REFERENCES "TBLLOCATIONGROUP"("id") ON DELETE CASCADE ON UPDATE CASCADE;

