-- CreateTable
CREATE TABLE "TBLDOCUMENTSTATUSACTION" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "documentStatusId" INTEGER NOT NULL,
    "actionType" INTEGER NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLDOCUMENTSTATUSACTION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLDOCUMENTSTATUSCRITERIA" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "operationTypeId" INTEGER NOT NULL,
    "businessPartnerId" INTEGER,
    "criteria" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLDOCUMENTSTATUSCRITERIA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLDOCUMENTAPPROVALTYPE" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "operationTypeId" INTEGER NOT NULL,
    "approvalType" INTEGER NOT NULL,
    "controlCollection" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLDOCUMENTAPPROVALTYPE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLDOCUMENTSTATUSACTION_companyId_idx" ON "TBLDOCUMENTSTATUSACTION"("companyId");

-- CreateIndex
CREATE INDEX "TBLDOCUMENTSTATUSCRITERIA_companyId_idx" ON "TBLDOCUMENTSTATUSCRITERIA"("companyId");

-- CreateIndex
CREATE INDEX "TBLDOCUMENTAPPROVALTYPE_companyId_idx" ON "TBLDOCUMENTAPPROVALTYPE"("companyId");

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTSTATUSACTION" ADD CONSTRAINT "TBLDOCUMENTSTATUSACTION_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTSTATUSCRITERIA" ADD CONSTRAINT "TBLDOCUMENTSTATUSCRITERIA_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTAPPROVALTYPE" ADD CONSTRAINT "TBLDOCUMENTAPPROVALTYPE_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

