-- CreateEnum
CREATE TYPE "ColumnAuthMode" AS ENUM ('READONLY', 'HIDDEN');

-- CreateTable
CREATE TABLE "TBLUSERCOLUMNAUTH" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "userId" INTEGER,
    "groupId" INTEGER,
    "resource" VARCHAR(60) NOT NULL,
    "column" VARCHAR(60) NOT NULL,
    "mode" "ColumnAuthMode" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLUSERCOLUMNAUTH_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLUSERCOLUMNAUTH_companyId_idx" ON "TBLUSERCOLUMNAUTH"("companyId");

-- CreateIndex
CREATE INDEX "TBLUSERCOLUMNAUTH_userId_idx" ON "TBLUSERCOLUMNAUTH"("userId");

-- CreateIndex
CREATE INDEX "TBLUSERCOLUMNAUTH_groupId_idx" ON "TBLUSERCOLUMNAUTH"("groupId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLUSERCOLUMNAUTH_userId_resource_column_key" ON "TBLUSERCOLUMNAUTH"("userId", "resource", "column");

-- CreateIndex
CREATE UNIQUE INDEX "TBLUSERCOLUMNAUTH_groupId_resource_column_key" ON "TBLUSERCOLUMNAUTH"("groupId", "resource", "column");

-- AddForeignKey
ALTER TABLE "TBLUSERCOLUMNAUTH" ADD CONSTRAINT "TBLUSERCOLUMNAUTH_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLUSERCOLUMNAUTH" ADD CONSTRAINT "TBLUSERCOLUMNAUTH_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TBLUSER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLUSERCOLUMNAUTH" ADD CONSTRAINT "TBLUSERCOLUMNAUTH_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "TBLUSERGROUP"("id") ON DELETE CASCADE ON UPDATE CASCADE;

