-- CreateEnum
CREATE TYPE "UserScopeType" AS ENUM ('FACILITY', 'WAREHOUSE', 'OPERATION_TYPE');

-- CreateTable
CREATE TABLE "TBLUSERAUTHORIZATION" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,
    "scopeType" "UserScopeType" NOT NULL,
    "referenceId" INTEGER NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLUSERAUTHORIZATION_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLUSERAUTHORIZATION_companyId_idx" ON "TBLUSERAUTHORIZATION"("companyId");

-- CreateIndex
CREATE INDEX "TBLUSERAUTHORIZATION_userId_idx" ON "TBLUSERAUTHORIZATION"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLUSERAUTHORIZATION_userId_scopeType_referenceId_key" ON "TBLUSERAUTHORIZATION"("userId", "scopeType", "referenceId");

-- AddForeignKey
ALTER TABLE "TBLUSERAUTHORIZATION" ADD CONSTRAINT "TBLUSERAUTHORIZATION_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLUSERAUTHORIZATION" ADD CONSTRAINT "TBLUSERAUTHORIZATION_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TBLUSER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

