-- CreateTable
CREATE TABLE "TBLPARTNERFACILITY" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "partnerId" INTEGER NOT NULL,
    "facilityId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TBLPARTNERFACILITY_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLPARTNERFACILITY_companyId_idx" ON "TBLPARTNERFACILITY"("companyId");

-- CreateIndex
CREATE INDEX "TBLPARTNERFACILITY_partnerId_idx" ON "TBLPARTNERFACILITY"("partnerId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLPARTNERFACILITY_partnerId_facilityId_key" ON "TBLPARTNERFACILITY"("partnerId", "facilityId");

-- AddForeignKey
ALTER TABLE "TBLPARTNERFACILITY" ADD CONSTRAINT "TBLPARTNERFACILITY_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "TBLBUSINESSPARTNER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

