
-- AlterTable
ALTER TABLE "TBLPRODUCT" ADD COLUMN     "detailTypeId" INTEGER,
ADD COLUMN     "productTypeId" INTEGER;

-- CreateTable
CREATE TABLE "TBLPRODUCTTYPE" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(40) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLPRODUCTTYPE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLPRODUCTDETAILTYPE" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLPRODUCTDETAILTYPE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLPRODUCTSUBSTITUTE" (
    "id" SERIAL NOT NULL,
    "productId" INTEGER NOT NULL,
    "substituteProductId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TBLPRODUCTSUBSTITUTE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLPRODUCTTYPE_companyId_idx" ON "TBLPRODUCTTYPE"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLPRODUCTTYPE_companyId_code_key" ON "TBLPRODUCTTYPE"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLPRODUCTDETAILTYPE_companyId_idx" ON "TBLPRODUCTDETAILTYPE"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLPRODUCTDETAILTYPE_companyId_code_key" ON "TBLPRODUCTDETAILTYPE"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLPRODUCTSUBSTITUTE_productId_idx" ON "TBLPRODUCTSUBSTITUTE"("productId");

-- CreateIndex
CREATE INDEX "TBLPRODUCTSUBSTITUTE_substituteProductId_idx" ON "TBLPRODUCTSUBSTITUTE"("substituteProductId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLPRODUCTSUBSTITUTE_productId_substituteProductId_key" ON "TBLPRODUCTSUBSTITUTE"("productId", "substituteProductId");

-- CreateIndex
CREATE INDEX "TBLPRODUCT_productTypeId_idx" ON "TBLPRODUCT"("productTypeId");

-- CreateIndex
CREATE INDEX "TBLPRODUCT_detailTypeId_idx" ON "TBLPRODUCT"("detailTypeId");

-- AddForeignKey
ALTER TABLE "TBLPRODUCT" ADD CONSTRAINT "TBLPRODUCT_productTypeId_fkey" FOREIGN KEY ("productTypeId") REFERENCES "TBLPRODUCTTYPE"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPRODUCT" ADD CONSTRAINT "TBLPRODUCT_detailTypeId_fkey" FOREIGN KEY ("detailTypeId") REFERENCES "TBLPRODUCTDETAILTYPE"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPRODUCTTYPE" ADD CONSTRAINT "TBLPRODUCTTYPE_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPRODUCTDETAILTYPE" ADD CONSTRAINT "TBLPRODUCTDETAILTYPE_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPRODUCTSUBSTITUTE" ADD CONSTRAINT "TBLPRODUCTSUBSTITUTE_productId_fkey" FOREIGN KEY ("productId") REFERENCES "TBLPRODUCT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPRODUCTSUBSTITUTE" ADD CONSTRAINT "TBLPRODUCTSUBSTITUTE_substituteProductId_fkey" FOREIGN KEY ("substituteProductId") REFERENCES "TBLPRODUCT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

