-- Tolerans master-detay (StokBar): master'dan duz %/miktar kalkar (detaya tasinir); yeni Detay tablosu (kademe bazinda).
ALTER TABLE "wms"."TBLOPERATIONTYPETOLERANCE" DROP COLUMN IF EXISTS "tolerancePercent";
ALTER TABLE "wms"."TBLOPERATIONTYPETOLERANCE" DROP COLUMN IF EXISTS "toleranceQty";

CREATE TABLE "wms"."TBLOPERATIONTYPETOLERANCEDETAIL" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "toleranceId" INTEGER NOT NULL,
    "lowerTier" DECIMAL(28,8),
    "upperTier" DECIMAL(28,8),
    "tierUnitId" INTEGER,
    "lowerIsPercent" BOOLEAN NOT NULL DEFAULT false,
    "lowerValue" DECIMAL(28,8),
    "lowerUnitId" INTEGER,
    "upperIsPercent" BOOLEAN NOT NULL DEFAULT false,
    "upperValue" DECIMAL(28,8),
    "upperUnitId" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "TBLOPERATIONTYPETOLERANCEDETAIL_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "TBLOPERATIONTYPETOLERANCEDETAIL_companyId_idx" ON "wms"."TBLOPERATIONTYPETOLERANCEDETAIL"("companyId");
CREATE INDEX "TBLOPERATIONTYPETOLERANCEDETAIL_toleranceId_idx" ON "wms"."TBLOPERATIONTYPETOLERANCEDETAIL"("toleranceId");
ALTER TABLE "wms"."TBLOPERATIONTYPETOLERANCEDETAIL" ADD CONSTRAINT "TBLOPERATIONTYPETOLERANCEDETAIL_toleranceId_fkey" FOREIGN KEY ("toleranceId") REFERENCES "wms"."TBLOPERATIONTYPETOLERANCE"("id") ON DELETE CASCADE ON UPDATE CASCADE;
