-- CreateTable
CREATE TABLE "TBLDOCUMENTSTATUS" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(100),
    "color" VARCHAR(20),
    "sortOrder" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLDOCUMENTSTATUS_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLDOCUMENTSTATUS_companyId_idx" ON "TBLDOCUMENTSTATUS"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLDOCUMENTSTATUS_companyId_code_key" ON "TBLDOCUMENTSTATUS"("companyId", "code");

-- AddForeignKey
ALTER TABLE "TBLDOCUMENTSTATUS" ADD CONSTRAINT "TBLDOCUMENTSTATUS_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

