CREATE PROCEDURE [dbo].[SSP_SBOPERASYONBELGEHAREKET]  
(  
 @LNGOPERASYONKOD INT,  
 @TXTOPERASYONNO NVARCHAR(50),  
 @OLUSACAKUSTPALET INT,  
 @TERSOPERASYON TINYINT,  
 @BELGETIPI INT,  
 @USERCODE INT  
)  
AS  
PRINT(CONVERT(NVARCHAR,GETDATE(),9))  
DECLARE @LNGOPERASYONTIPKOD INT  
DECLARE @OPERASYONPARCALIKULLANIM TINYINT  
DECLARE @OPERASYONTRANSFERDEPALETTENCIKAR TINYINT  
DECLARE @TXTPALETNO NVARCHAR(50)  
DECLARE @PALETTRANSFERDEPALETTENCIKAR TINYINT  
DECLARE @PALETTIP TINYINT  
DECLARE @PALETID INT  
DECLARE @STOKTOPLAMMIKTAR DECIMAL(28,8)  
DECLARE @OPTOPLAMMIKTAR DECIMAL(28,8)  
DECLARE @USTPALETNO INT  
DECLARE @PALETBOZMA TINYINT  
DECLARE @BYTGIRISCIKIS TINYINT  
DECLARE @OPKATEGORI TINYINT  
DECLARE @PALETTIPKOD INT  
DECLARE @ANAMIKTAR DECIMAL(28,8)  
DECLARE @ANABIRIM INT  
DECLARE @SONKULLANMATARIHI DATETIME  
DECLARE @URETIMTARIHI DATETIME  
DECLARE @LOKASYONKOD INT  
DECLARE @URUNKOD INT  
DECLARE @BATCHNO NVARCHAR(50)  
DECLARE @SERINO NVARCHAR(50)  
DECLARE @PO NVARCHAR(50)  
DECLARE @POLINE NVARCHAR(50)  
DECLARE @MUSTERI INT  
DECLARE @REZERVEBELGEKOD INT  
DECLARE @REZERVEBELGETIPKOD INT  
DECLARE @NETAGIRLIK DECIMAL(28,8)  
DECLARE @BRUTAGIRLIK DECIMAL(28,8)  
DECLARE @AGIRLIKBIRIMI INT  
DECLARE @STATUKOD INT  
DECLARE @REZERVEGUNCELLE TINYINT  
DECLARE @MESSAGESTOKHAREKET AS TABLE(MESSAGETYPE NVARCHAR(1),MESSAGETEXT NVARCHAR(100))  
DECLARE @MESSAGETEXT NVARCHAR(200)  
  
DECLARE @OPERASYONDETAY AS TABLE(LNGKOD INT, TXTPALETNO NVARCHAR(50),BYTGIRISCIKIS TINYINT,LNGANAOLCUBIRIMKOD INT,DBLANAMIKTAR DECIMAL(28,8),TRHSONKULLANMATARIHI DATETIME,  
 TRHURETIMTARIHI DATETIME,LNGLOKASYONKOD INT,LNGURUNKOD INT,TXTBATCHNO NVARCHAR(50),TXTSERINO NVARCHAR(50),TXTPO NVARCHAR(50),TXTPOLINE NVARCHAR(50),  
 LNGMUSTERIKOD INT,LNGREZERVEBELGEKOD INT,LNGREZERVEBELGETIPKOD INT,DBLNETAGIRLIK DECIMAL(28,8),DBLBRUTAGIRLIK DECIMAL(28,8),LNGAGIRLIKOLCUBIRIMKOD INT,LNGSTATU INT)  
  
SELECT @OPERASYONPARCALIKULLANIM=OT.BYTPARCALIKULLANIM,@OPERASYONTRANSFERDEPALETTENCIKAR=BYTTRANSFERDEPALETTENCIKAR,@PALETBOZMA=BYTPALETBOZMA,  
 @OPKATEGORI=BYTKATEGORI  
FROM TBLSBOPERASYONBELGEBASLIK BB  
 INNER JOIN TBLSBOPERASYONTIPI OT ON BB.LNGOPERASYONTIPKOD=OT.LNGKOD  
WHERE BB.LNGKOD=@LNGOPERASYONKOD  
PRINT('Parametre Alindi')  
PRINT(CONVERT(NVARCHAR,GETDATE(),9))  
 INSERT INTO  @OPERASYONDETAY  
 SELECT LNGKOD,TXTPALETNO,BYTGIRISCIKIS,LNGANAOLCUBIRIMKOD,DBLANAMIKTAR,TRHSONKULLANMATARIHI,TRHURETIMTARIHI,LNGLOKASYONKOD,LNGURUNKOD,  
 TXTBATCHNO,TXTSERINO ,TXTPO ,TXTPOLINE ,LNGMUSTERIKOD ,LNGREZERVEBELGEKOD ,LNGREZERVEBELGETIPKOD ,DBLNETAGIRLIK,DBLBRUTAGIRLIK,LNGAGIRLIKOLCUBIRIMKOD,LNGSTATU  
 FROM TBLSBOPERASYONBELGEDETAY WITH(NOLOCK)    
 WHERE LNGBASLIKKOD=@LNGOPERASYONKOD  
  
 PRINT('Insert Edildi')  
 PRINT(CONVERT(NVARCHAR,GETDATE(),9))  
IF @BELGETIPI=4 OR @BELGETIPI=1   
 SET @REZERVEGUNCELLE=1  
ELSE  
 SET @REZERVEGUNCELLE=0  
  
 DECLARE DETAY CURSOR SCROLL FOR                            
 SELECT TXTPALETNO,BYTGIRISCIKIS,LNGANAOLCUBIRIMKOD,DBLANAMIKTAR,TRHSONKULLANMATARIHI,TRHURETIMTARIHI,LNGLOKASYONKOD,LNGURUNKOD,  
 TXTBATCHNO,TXTSERINO ,TXTPO ,TXTPOLINE ,LNGMUSTERIKOD ,LNGREZERVEBELGEKOD ,LNGREZERVEBELGETIPKOD ,DBLNETAGIRLIK,DBLBRUTAGIRLIK,LNGAGIRLIKOLCUBIRIMKOD,LNGSTATU  
 FROM @OPERASYONDETAY  
  
 OPEN DETAY                            
 FETCH FIRST FROM DETAY INTO @TXTPALETNO,@BYTGIRISCIKIS,@ANABIRIM,@ANAMIKTAR,@SONKULLANMATARIHI,@URETIMTARIHI, @LOKASYONKOD,@URUNKOD,  
 @BATCHNO,@SERINO ,@PO ,@POLINE ,@MUSTERI ,@REZERVEBELGEKOD ,@REZERVEBELGETIPKOD ,@NETAGIRLIK,@BRUTAGIRLIK,@AGIRLIKBIRIMI,@STATUKOD  
 WHILE  @@FETCH_STATUS = 0                                              
 BEGIN            
 PRINT('DonguBaslangici')  
 PRINT(CONVERT(NVARCHAR,GETDATE(),9))  
 IF @TXTPALETNO IS NOT NULL  
 BEGIN  
  IF @BYTGIRISCIKIS=2  
  BEGIN  
   SELECT @PALETID=P.LNGKOD, @PALETTIP=PT.BYTTIP,@PALETTRANSFERDEPALETTENCIKAR=BYTTRANSFERDEPALETTENCIKAR ,@USTPALETNO=LNGUSTPALETKOD  
   FROM TBLSBPALET P   
    INNER JOIN TBLSBPALETTIPI PT ON PT.LNGKOD=P.LNGPALETTIPIKOD  
   WHERE TXTPALETNO=@TXTPALETNO  
   IF (@PALETTIP=1 OR @PALETTIP=0) AND @OPERASYONTRANSFERDEPALETTENCIKAR=1 AND @PALETTRANSFERDEPALETTENCIKAR=1  
   BEGIN  
    SELECT @STOKTOPLAMMIKTAR = SUM(DBLANAMIKTAR) FROM TBLSBSTOKDURUM WHERE LNGPALETID=@PALETID  
    SELECT @OPTOPLAMMIKTAR = SUM(DBLANAMIKTAR) FROM @OPERASYONDETAY WHERE TXTPALETNO=@TXTPALETNO AND BYTGIRISCIKIS=2  
    IF @STOKTOPLAMMIKTAR<>@OPTOPLAMMIKTAR  
    BEGIN  
     UPDATE TBLSBOPERASYONBELGEDETAY SET TXTPALETNO=NULL WHERE LNGKOD IN(SELECT LNGKOD FROM @OPERASYONDETAY WHERE LNGBASLIKKOD=@LNGOPERASYONKOD AND BYTGIRISCIKIS=1 AND TXTPALETNO=@TXTPALETNO)  
    END  
   END  
   ELSE  
   BEGIN  
    IF @USTPALETNO IS NOT NULL  
     UPDATE TBLSBPALET SET LNGUSTPALETKOD= NULL WHERE LNGKOD=@PALETTIP  
   END  
  END  
  
  IF @BYTGIRISCIKIS=2 AND @PALETBOZMA=1  
  BEGIN  
   UPDATE TBLSBPALET SET BYTAKTIF=0 WHERE LNGKOD=@PALETID  
  END  
  IF @BYTGIRISCIKIS=1 AND @PALETID IS NULL  
  --PaletYarat  
  BEGIN  
   IF @BELGETIPI=2  
    RAISERROR('Kodlanamadi',16,1 )  
   ELSE  
   BEGIN  
    SELECT @PALETTIPKOD=LNGPALETTIPKOD FROM TBLSBOPERASYONTIPIPALETTIPI WHERE LNGOPERASYONTIPKOD=@LNGOPERASYONTIPKOD  
    IF @PALETTIPKOD IS NULL   
     RAISERROR('OlusacakPaletTipiBulunamadi',16,1)  
    ELSE  
    BEGIN  
     INSERT INTO TBLSBPALET (TXTPALETNO,BYTAKTIF,LNGPALETTIPIKOD,DBLORJINALMIKTAR,LNGANAOLCUBIRIMI,TRHSONKULLANMATARIHI,TRHURETIMTARIHI,BYTARSIV,LNGUSTPALETKOD,TRHILKISLEMTARIHI,TRHSONISLEMTARIHI,LNGILKKULLANICIKOD,LNGSONKULLANICIKOD)  
     VALUES(@TXTPALETNO,1,@PALETTIPKOD,@ANAMIKTAR,@ANABIRIM,@SONKULLANMATARIHI,@URETIMTARIHI,1,@OLUSACAKUSTPALET,GETDATE(),GETDATE(),@USERCODE,@USERCODE)  
     SET @PALETID=@@IDENTITY  
    END  
   END  
  END  
  ELSE IF @BYTGIRISCIKIS=1 AND @PALETID IS NOT NULL AND @OLUSACAKUSTPALET IS NOT NULL AND @USTPALETNO IS NULL  
   UPDATE TBLSBPALET SET LNGUSTPALETKOD=@OLUSACAKUSTPALET WHERE LNGKOD=@PALETID  
  ELSE IF @BYTGIRISCIKIS=2 AND @PALETID IS NOT NULL AND @OLUSACAKUSTPALET IS NOT NULL AND @USTPALETNO = @OLUSACAKUSTPALET  
   UPDATE TBLSBPALET SET LNGUSTPALETKOD=NULL WHERE LNGKOD=@PALETID  
     
  INSERT INTO @MESSAGESTOKHAREKET  
  EXEC SSP_SBSTOKHAREKETI_TRANSFER  @LOKASYONKOD,@URUNKOD,@BATCHNO,@SERINO,@PO ,@POLINE,@PALETID,@STATUKOD,@MUSTERI,@REZERVEBELGEKOD,@REZERVEBELGETIPKOD,@ANAMIKTAR,@ANABIRIM,  
   @NETAGIRLIK,@BRUTAGIRLIK,@AGIRLIKBIRIMI,@SONKULLANMATARIHI,@URETIMTARIHI,@OPERASYONPARCALIKULLANIM,@REZERVEGUNCELLE,@TERSOPERASYON,@BYTGIRISCIKIS,NULL,'',NULL  
    
  IF EXISTS(SELECT * FROM @MESSAGESTOKHAREKET WHERE MESSAGETYPE='E')  
  BEGIN  
   SELECT @MESSAGETEXT=MESSAGETEXT FROM @MESSAGESTOKHAREKET WHERE MESSAGETYPE='E'  
   SET @MESSAGETEXT=@MESSAGETEXT + '-' + CONVERT(NVARCHAR,@URUNKOD) + '-' + @BATCHNO  
   RAISERROR (@MESSAGETEXT,16,1)  
   RETURN  
  END  
     
  
  IF  @OPKATEGORI <> 3 AND @BYTGIRISCIKIS = 2 And @TERSOPERASYON=1 And @BELGETIPI <> 2  
   RAISERROR('Kodlanamadi',16,1 )  
  ELSE  
  BEGIN  
   IF NOT EXISTS(SELECT LNGKOD FROM TBLSBSTOKDURUM WHERE LNGPALETID=@PALETID)  
   BEGIN  
    UPDATE TBLSBPALET SET BYTAKTIF=0 WHERE LNGKOD=@PALETID  
    IF @USTPALETNO IS NOT NULL  
    BEGIN  
     IF EXISTS(SELECT LNGKOD FROM TBLSBPALET WHERE LNGUSTPALETKOD=@USTPALETNO AND BYTAKTIF=1)  
      UPDATE TBLSBPALET SET BYTAKTIF=0 WHERE LNGKOD=@USTPALETNO    
    END  
   END  
   ELSE  
   BEGIN  
    UPDATE TBLSBPALET SET BYTAKTIF=1 WHERE LNGKOD=@PALETID  
    UPDATE TBLSBPALET SET BYTAKTIF=1 WHERE LNGKOD=@USTPALETNO  
   END  
   --tarihçeye kayit at  
   INSERT INTO TBLSBPALETTARIHCE(LNGPALETKOD,BYTAKTIF,LNGURETIMREFERANSKOD,LNGUSTPALETKOD,DBLORJINALMIKTAR,LNGANAOLCUBIRIMI,  
    LNGANAPALETKOD,TRHSONKULLANMATARIHI,TRHURETIMTARIHI,BYTARSIV,TXTOPERASYONBELGEBASLIKKOD,TRHILKISLEMTARIHI,TRHSONISLEMTARIHI,LNGILKKULLANICIKOD,LNGSONKULLANICIKOD)  
   (SELECT LNGKOD,BYTAKTIF,LNGURETIMREFERANSKOD,LNGUSTPALETKOD,DBLORJINALMIKTAR,LNGANAOLCUBIRIMI,LNGANAPALETKOD,TRHSONKULLANMATARIHI,  
    TRHURETIMTARIHI,BYTARSIV,@TXTOPERASYONNO,GETDATE(),GETDATE(),@USERCODE,@USERCODE FROM TBLSBPALET WHERE LNGKOd=@PALETID)  
  END  
 END  
 ELSE  
 BEGIN  
 --palet yoksa  
  IF  @OPKATEGORI = 1 --onaydaPaletYaratilsin=1  
   RAISERROR('Kodlanamadi',16,1 )  
  
  INSERT INTO @MESSAGESTOKHAREKET  
  EXEC SSP_SBSTOKHAREKETI_TRANSFER  @LOKASYONKOD,@URUNKOD,@BATCHNO,@SERINO,@PO ,@POLINE,@PALETID,@STATUKOD,@MUSTERI,@REZERVEBELGEKOD,@REZERVEBELGETIPKOD,@ANAMIKTAR,@ANABIRIM,  
   @NETAGIRLIK,@BRUTAGIRLIK,@AGIRLIKBIRIMI,@SONKULLANMATARIHI,@URETIMTARIHI,@OPERASYONPARCALIKULLANIM,@REZERVEGUNCELLE,@TERSOPERASYON,@BYTGIRISCIKIS,NULL,'',NULL  
  IF EXISTS(SELECT * FROM @MESSAGESTOKHAREKET WHERE MESSAGETYPE='E')  
  BEGIN  
   SELECT @MESSAGETEXT=MESSAGETEXT FROM @MESSAGESTOKHAREKET WHERE MESSAGETYPE='E'  
   SET @MESSAGETEXT=@MESSAGETEXT + '-' + CONVERT(NVARCHAR,@URUNKOD) + '-' + @BATCHNO  
   RAISERROR (@MESSAGETEXT,16,1)  
   RETURN  
  END  
 END  
 PRINT('DonguSonu')  
 PRINT(CONVERT(NVARCHAR,GETDATE(),9))  
 FETCH NEXT FROM DETAY INTO @TXTPALETNO,@BYTGIRISCIKIS,@ANABIRIM,@ANAMIKTAR,@SONKULLANMATARIHI,@URETIMTARIHI, @LOKASYONKOD,@URUNKOD,  
 @BATCHNO,@SERINO ,@PO ,@POLINE ,@MUSTERI ,@REZERVEBELGEKOD ,@REZERVEBELGETIPKOD ,@NETAGIRLIK,@BRUTAGIRLIK,@AGIRLIKBIRIMI,@STATUKOD  
 END                                                    
 CLOSE DETAY                            
 DEALLOCATE DETAY   
 PRINT('IslemBitti')  
 PRINT(CONVERT(NVARCHAR,GETDATE(),9))