CREATE PROCEDURE [dbo].[SSP_SBOPERASYONDETAYLARIGIRISCIKIS]      
(      
 @LNGOPERASYONKOD int    
)      
AS  
select CASE WHEN OG.LNGBASLIKKOD IS NULL THEN OC.LNGBASLIKKOD ELSE OG.LNGBASLIKKOD END AS LNGBASLIKKOD, CASE WHEN OG.LNGDETAYKOD IS NULL THEN OC.LNGDETAYKOD ELSE OG.LNGDETAYKOD END AS LNGDETAYKOD,    
  CASE WHEN OG.LNGURUNKOD IS NULL THEN OC.LNGURUNKOD ELSE OG.LNGURUNKOD END AS LNGURUNKOD,OG.LNGLOKASYONKOD as LNGGIRISLOKASYON,OC.LNGLOKASYONKOD AS LNGCIKISLOKASYON,     
  CASE WHEN OG.DBLANAMIKTAR IS NULL THEN OC.DBLANAMIKTAR ELSE OG.DBLANAMIKTAR END AS DBLANAMIKTAR,CASE WHEN OG.LNGANAOLCUBIRIMKOD IS NULL THEN OC.LNGANAOLCUBIRIMKOD ELSE OG.LNGANAOLCUBIRIMKOD END AS LNGANAOLCUBIRIMKOD,      
  --CASE WHEN OG.DBLISLEMMIKTAR IS NULL THEN OC.DBLISLEMMIKTAR ELSE OG.DBLISLEMMIKTAR END AS DBLISLEMMIKTAR,
  CASE WHEN OG.DBLANAMIKTAR IS NULL THEN OC.DBLANAMIKTAR ELSE OG.DBLANAMIKTAR END / UOB.DBLCARPAN*UOB.DBLBOLEN AS DBLISLEMMIKTAR,
  CASE WHEN OG.LNGISLEMOLCUBIRIMKOD IS NULL THEN OC.LNGISLEMOLCUBIRIMKOD ELSE OG.LNGISLEMOLCUBIRIMKOD END AS LNGISLEMOLCUBIRIMKOD,      
  CASE WHEN OG.DBLNETAGIRLIK IS NULL THEN OC.DBLNETAGIRLIK ELSE OG.DBLNETAGIRLIK END AS DBLNETAGIRLIK,CASE WHEN OG.LNGAGIRLIKOLCUBIRIMKOD IS NULL THEN OC.LNGAGIRLIKOLCUBIRIMKOD ELSE OG.LNGAGIRLIKOLCUBIRIMKOD END AS LNGAGIRLIKOLCUBIRIMKOD,    
  CASE WHEN OG.LNGREFBELGEDETAYNO IS NULL THEN OC.LNGREFBELGEDETAYNO ELSE OG.LNGREFBELGEDETAYNO END AS LNGREFBELGEDETAYNO, CASE WHEN OG.LNGOPERASYONNEDENKOD IS NULL THEN OC.LNGOPERASYONNEDENKOD ELSE OG.LNGOPERASYONNEDENKOD END AS LNGOPERASYONNEDENKOD    
from (SELECT LNGBASLIKKOD,MIN(LNGDETAYKOD) AS LNGDETAYKOD,LNGURUNKOD,L.LNGKOD AS LNGLOKASYONKOD,SUM(DBLANAMIKTAR) AS DBLANAMIKTAR,LNGANAOLCUBIRIMKOD,    
		LNGISLEMOLCUBIRIMKOD,SUM(DBLNETAGIRLIK) AS DBLNETAGIRLIK,LNGAGIRLIKOLCUBIRIMKOD,LNGOPERASYONNEDENKOD,LNGREFBELGEDETAYNO    
	FROM TBLSBOPERASYONBELGEDETAY WITH(NOLOCK)   
		INNER JOIN TBLSBLOKASYON L WITH(NOLOCK) ON L.LNGKOD=TBLSBOPERASYONBELGEDETAY.LNGLOKASYONKOD  
	WHERE BYTGIRISCIKIS=1 AND LNGBASLIKKOD=@LNGOPERASYONKOD    
	GROUP BY LNGBASLIKKOD,LNGURUNKOD,L.LNGKOD,LNGANAOLCUBIRIMKOD,LNGISLEMOLCUBIRIMKOD,LNGAGIRLIKOLCUBIRIMKOD,LNGOPERASYONNEDENKOD,LNGREFBELGEDETAYNO) OG      
 FULL OUTER JOIN 
   (SELECT LNGBASLIKKOD,MIN(LNGDETAYKOD) AS LNGDETAYKOD,LNGURUNKOD,L.LNGKOD AS LNGLOKASYONKOD,SUM(DBLANAMIKTAR) AS DBLANAMIKTAR,LNGANAOLCUBIRIMKOD,    
        LNGISLEMOLCUBIRIMKOD,SUM(DBLNETAGIRLIK) AS DBLNETAGIRLIK,  
        LNGAGIRLIKOLCUBIRIMKOD,LNGOPERASYONNEDENKOD,LNGREFBELGEDETAYNO    
	FROM TBLSBOPERASYONBELGEDETAY WITH(NOLOCK)    
		INNER JOIN TBLSBLOKASYON L WITH(NOLOCK) ON L.LNGKOD=TBLSBOPERASYONBELGEDETAY.LNGLOKASYONKOD  
	WHERE BYTGIRISCIKIS=2 AND LNGBASLIKKOD=@LNGOPERASYONKOD    
	GROUP BY LNGBASLIKKOD,LNGURUNKOD,L.LNGKOD,LNGANAOLCUBIRIMKOD,LNGISLEMOLCUBIRIMKOD,LNGAGIRLIKOLCUBIRIMKOD,LNGOPERASYONNEDENKOD,LNGREFBELGEDETAYNO) OC     
   ON OG.LNGREFBELGEDETAYNO=OC.LNGREFBELGEDETAYNO  AND OG.LNGBASLIKKOD=OC.LNGBASLIKKOD 
 INNER JOIN TBLSBURUNOLCUBIRIM UOB ON CASE WHEN OG.LNGURUNKOD IS NULL THEN OC.LNGURUNKOD ELSE OG.LNGURUNKOD END=UOB.LNGURUNKOD 
										AND CASE WHEN OG.LNGISLEMOLCUBIRIMKOD IS NULL THEN OC.LNGISLEMOLCUBIRIMKOD ELSE OG.LNGISLEMOLCUBIRIMKOD END =UOB.LNGBIRIMKOD