
CREATE PROC [dbo].[SSP_SBMALKABULYONLENDIRME_ANA]

(  
 @LNGLOKASYON INT,  
 @LNGKAYNAKLOKASYON int,
 @LNGMALZEME INT,  
 @TXTKONTROLSAHASI NVARCHAR(50),  
 @KONTROLSAHASIDEGERI  NVARCHAR(50),  
 @DBLOKUTULANMIKTAR DECIMAL(28,8),  
 @DBLOKUTULANBIRIM DECIMAL(28,8),
 @BYTARTANSIRALAMA TINYINT,  
 @TXTPALETNO NVARCHAR(20),
 @LNGBELGEKOD INT,
 @LNGESKILOKASYON INT=0
)  
AS

CREATE TABLE #LOKASYON (LNGKOD INT, TXTLOKASYONKOD NVARCHAR(50),TXTTANIMI NVARCHAR(100))
CREATE TABLE #USTLOKASYON (LNGUSTKOD INT)
CREATE TABLE #ONERILOKASYON (LNGKOD INT, LOKASYON NVARCHAR(50))
CREATE TABLE #ONERILOKASYONURUN (LNGKOD INT, LOKASYON NVARCHAR(50))
CREATE TABLE #STOKDURUM (LNGKOD INT, TXTTANIMI  NVARCHAR(50))
CREATE TABLE #BOSLOKASYONLAR (LNGKOD INT, TXTLOKASYONKOD NVARCHAR(50), DBLPALETMIKTAR INT, BOSMIK INT)
CREATE TABLE #KAPSAMKONTROL (LNGKOD INT, TXTTANIMI  NVARCHAR(50))


INSERT INTO #KAPSAMKONTROL
		SELECT  L.LNGKOD AS LNGKOD , L.TXTTANIMI AS LOKASYON FROM TBLSBBELGEKAPSAM BK
		INNER JOIN TBLSBBELGEDETAY BD ON BD.LNGKOD=BK.LNGDETAYKOD
		INNER JOIN TBLSBBELGEBASLIK BB ON BB.LNGKOD=BD.LNGBASLIKKOD
		INNER JOIN TBLSBLOKASYON L ON L.LNGKOD=BK.LNGHEDEFLOKASYONKOD
		WHERE BB.BYTBELGEDURUM =7 AND BB.LNGOPERASYONTIPKOD=1241 AND BD.LNGMALZEMEKOD=@LNGMALZEME AND BB.LNGDISTKOD=8

INSERT INTO #BOSLOKASYONLAR
	SELECT  *  FROM (
	SELECT L.LNGKOD, L.TXTLOKASYONKOD, LK.DBLPALETMIKTAR, (LK.DBLPALETMIKTAR-COUNT(SD.LNGLOKASYONKOD)-COUNT(KAPSAM.LNGKOD)) AS BOSMIK FROM TBLSBLOKASYON L WITH(NOLOCK)
	INNER JOIN TBLSBLOKASYONKAPASITE LK WITH(NOLOCK) ON LK.LNGLOKASYONBAGLANTIKODU=L.LNGKOD	
	LEFT JOIN TBLSBSTOKDURUM SD WITH(NOLOCK) ON SD.LNGLOKASYONKOD=L.LNGKOD
	LEFT JOIN #KAPSAMKONTROL KAPSAM WITH(NOLOCK) ON KAPSAM.LNGKOD=L.LNGKOD
	WHERE SUBSTRING(L.TXTLOKASYONKOD,6,2)<>'01'  AND L.LNGDISTKOD=8
	GROUP BY L.TXTLOKASYONKOD, LK.DBLPALETMIKTAR, L.LNGKOD) BOSRAF WHERE
	BOSMIK>0 ORDER BY TXTLOKASYONKOD


INSERT INTO #STOKDURUM
		SELECT DISTINCT L.LNGKOD AS LNGKOD , L.TXTTANIMI AS LOKASYON  FROM TBLSBLOKASYON L WITH(NOLOCK)
		INNER JOIN TBLSBSTOKDURUM S WITH(NOLOCK) ON S.LNGLOKASYONKOD=L.LNGKOD
		WHERE LEN(L.TXTLOKASYONKOD)=7 AND LNGMALZEMEKOD=@LNGMALZEME AND L.LNGDISTKOD=8

INSERT INTO #USTLOKASYON
SELECT DISTINCT * FROM (
				SELECT DISTINCT LNGUSTKOD FROM TBLSBLOKASYON L WITH(NOLOCK)
		INNER JOIN TBLSBSTOKDURUM S WITH(NOLOCK) ON S.LNGLOKASYONKOD=L.LNGKOD
		INNER JOIN TBLSBLOKASYONKAPASITE LK WITH(NOLOCK) ON LK.LNGLOKASYONBAGLANTIKODU=L.LNGKOD
		WHERE LEN(L.TXTLOKASYONKOD)=7 AND LNGMALZEMEKOD=@LNGMALZEME  AND L.LNGDISTKOD=8
		UNION ALL
				SELECT DISTINCT LNGUSTKOD FROM TBLSBLOKASYON L WITH(NOLOCK)
		INNER JOIN  #KAPSAMKONTROL S  ON S.LNGKOD=L.LNGKOD
		INNER JOIN TBLSBLOKASYONKAPASITE LK WITH(NOLOCK) ON LK.LNGLOKASYONBAGLANTIKODU=L.LNGKOD
		WHERE LEN(L.TXTLOKASYONKOD)=7 AND L.LNGDISTKOD=8 ) A

INSERT INTO #ONERILOKASYON
		SELECT TOP 1 LNGKOD,  TXTLOKASYONKOD FROM (
		SELECT L.LNGKOD,  L.TXTLOKASYONKOD, LK.DBLPALETMIKTAR, (LK.DBLPALETMIKTAR-COUNT(SD.LNGLOKASYONKOD)-COUNT(KAPSAM.LNGKOD)) AS BOSMIK FROM TBLSBLOKASYON L WITH(NOLOCK)
		INNER JOIN TBLSBLOKASYONKAPASITE LK WITH(NOLOCK) ON LK.LNGLOKASYONBAGLANTIKODU=L.LNGKOD
		INNER JOIN #USTLOKASYON UST WITH(NOLOCK) ON UST.LNGUSTKOD=L.LNGUSTKOD
		LEFT JOIN TBLSBSTOKDURUM SD WITH(NOLOCK) ON SD.LNGLOKASYONKOD=L.LNGKOD
		LEFT JOIN #KAPSAMKONTROL KAPSAM WITH(NOLOCK) ON KAPSAM.LNGKOD=L.LNGKOD
		WHERE SUBSTRING(L.TXTLOKASYONKOD,6,2)<>'01'  AND L.LNGDISTKOD=8
		GROUP BY L.LNGKOD, L.TXTLOKASYONKOD, LK.DBLPALETMIKTAR) BOSRAF
		WHERE BOSMIK>0 ORDER BY CONVERT(INT,SUBSTRING(TXTLOKASYONKOD,6,2)) DESC



--EĞER STOKTA VARSA ÖNCE STOKTA HANGİ RAFTA OLDUĞU BULUNUR
IF  EXISTS (SELECT * FROM #STOKDURUM) 
 BEGIN
	--STOKTA OLAN RAFIN USTLOKASOYNU ALINARAK AYNI SÜTUNDAKİ DİĞER RAFLARDA BOŞ RAF VAR MI DİYE BAKILIR. EĞER BOŞ RAF VARSA ÖNCE EN ÜST RAF ÖNERİLİR. TOPLAMA RAFLARI ÖNERİLMEZ. YOKSA YAKINDAKİ BOŞ RAF BULUNUR
	PRINT 'Ürün Stokta Var'

	IF (@TXTPALETNO IS NULL OR @TXTPALETNO='')--EĞER PALET OKUTULMADISYSA TOPLAMA GÖZÜNE YÖNLENDİRİLİYOR.
	BEGIN
	PRINT 'Toplama Gözüne Yönlendiriliyor.'
	SELECT TOP 1 L.LNGKOD, L.LNGKOD AS LOKASYON,  TXTLOKASYONKOD AS TXTTANIMI FROM TBLSBSTOKDURUM SD
	INNER JOIN TBLSBLOKASYON L ON L.LNGKOD=SD.LNGLOKASYONKOD
	WHERE LNGPALETID IS NULL AND SUBSTRING(L.TXTLOKASYONKOD,6,2)='01' AND   LNGMALZEMEKOD=@LNGMALZEME
	END

	ELSE--EĞER PALET OKUTULDUYSA STOK RAFINA YÖNLENDİRİLİYOR.
	BEGIN
	PRINT 'Stok Gözüne Yönlendiriliyor.'
	IF NOT EXISTS (SELECT * FROM #ONERILOKASYON) 	--EĞER STOKTA VARSA VE STOKTA OLAN RAFLARA AIT SUTUN KOMPLE DOLUYSA YAKINDAKI BOS RAFLAR BULUNUR.
	BEGIN
	PRINT 'Ürünün bulunuğu sütunda boş raf yok'


	INSERT INTO #LOKASYON
	SELECT TOP 1 LNGKOD, TXTLOKASYONKOD, TXTLOKASYONKOD AS  TXTTANIM FROM (
	SELECT CASE WHEN (UBLOKDEGER-BLOKDEGER)<0 THEN (UBLOKDEGER-BLOKDEGER)*-1 WHEN (UBLOKDEGER-BLOKDEGER)>0 THEN (UBLOKDEGER-BLOKDEGER) WHEN (UBLOKDEGER-BLOKDEGER)=0 THEN 0 END  AS BLOKMESAFE, 
	CASE WHEN (USUTUN-SUTUN)<0 THEN (USUTUN-SUTUN)*-1  WHEN (USUTUN-SUTUN)>0 THEN  (USUTUN-SUTUN) WHEN (USUTUN-SUTUN)=0 THEN 0 END  AS SUTUNMESAFE,
	TXTLOKASYONKOD, LNGKOD FROM (
	SELECT SUBSTRING(TXTLOKASYONKOD,1,1) AS BLOK, CONVERT(INT,SUBSTRING(TXTLOKASYONKOD,3,2)) AS SUTUN, SUBSTRING(TXTLOKASYONKOD,6,2) AS RAF,  
		CASE WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='A' THEN 1
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='B' THEN 2
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='C' THEN 3
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='D' THEN 4
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='E' THEN 5
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='F' THEN 6
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='G' THEN 7
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='H' THEN 8
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='I' THEN 9
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='J' THEN 10
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='K' THEN 11
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='L' THEN 12
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='M' THEN 13
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='N' THEN 14
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='O' THEN 15
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='P' THEN 16
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='R' THEN 17
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='S' THEN 18
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='T' THEN 19
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='U' THEN 20
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='V' THEN 21
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='Y' THEN 22
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='Z' THEN 23
	END AS BLOKDEGER,
	CASE WHEN SUBSTRING(UBLOK,1,1)='A' THEN 1
	WHEN SUBSTRING(UBLOK,1,1)='B' THEN 2
	WHEN SUBSTRING(UBLOK,1,1)='C' THEN 3
	WHEN SUBSTRING(UBLOK,1,1)='D' THEN 4
	WHEN SUBSTRING(UBLOK,1,1)='E' THEN 5
	WHEN SUBSTRING(UBLOK,1,1)='F' THEN 6
	WHEN SUBSTRING(UBLOK,1,1)='G' THEN 7
	WHEN SUBSTRING(UBLOK,1,1)='H' THEN 8
	WHEN SUBSTRING(UBLOK,1,1)='I' THEN 9
	WHEN SUBSTRING(UBLOK,1,1)='J' THEN 10
	WHEN SUBSTRING(UBLOK,1,1)='K' THEN 11
	WHEN SUBSTRING(UBLOK,1,1)='L' THEN 12
	WHEN SUBSTRING(UBLOK,1,1)='M' THEN 13
	WHEN SUBSTRING(UBLOK,1,1)='N' THEN 14
	WHEN SUBSTRING(UBLOK,1,1)='O' THEN 15
	WHEN SUBSTRING(UBLOK,1,1)='P' THEN 16
	WHEN SUBSTRING(UBLOK,1,1)='R' THEN 17
	WHEN SUBSTRING(UBLOK,1,1)='S' THEN 18
	WHEN SUBSTRING(UBLOK,1,1)='T' THEN 19
	WHEN SUBSTRING(UBLOK,1,1)='U' THEN 20
	WHEN SUBSTRING(UBLOK,1,1)='V' THEN 21
	WHEN SUBSTRING(UBLOK,1,1)='Y' THEN 22
	WHEN SUBSTRING(UBLOK,1,1)='Z' THEN 23
	END AS UBLOKDEGER,	
	* 
	FROM (SELECT * FROM #BOSLOKASYONLAR) BOSRAF 
	CROSS JOIN (SELECT * FROM( SELECT DISTINCT  SUBSTRING(TXTTANIMI,1,1) AS UBLOK , CONVERT(INT,SUBSTRING(TXTTANIMI,3,2)) AS USUTUN FROM #STOKDURUM)G)A
	WHERE BOSMIK>0 )SQL)SQL2 ORDER BY BLOKMESAFE, SUTUNMESAFE, TXTLOKASYONKOD
	
	
	SELECT LNGKOD AS LNGKOD,LNGKOD AS LOKASYON, TXTTANIMI AS TXTTANIMI  FROM #LOKASYON ORDER BY LNGKOD ASC
	PRINT 'En yakındaki boş raf bulundu.'


	END 

	ELSE 
	--STOKTAKI URUNE AIT RAFIN SUTUNUNA BAKILIP BOŞ OLAN RAF ÖNERİLİR
	BEGIN
	PRINT 'Stoktaki Ürünün Bulunduğu Raf Öneriliyor.'
	INSERT INTO #LOKASYON
	SELECT LNGKOD AS LNGKOD,LNGKOD AS LOKASYON, LOKASYON AS TXTTANIMI FROM #ONERILOKASYON

	SELECT LNGKOD AS LNGKOD,LNGKOD AS LOKASYON, TXTTANIMI AS TXTTANIMI  FROM #LOKASYON ORDER BY LNGKOD ASC

	END

    END
 END

IF NOT EXISTS (SELECT *FROM #STOKDURUM) 
BEGIN
PRINT 'Ürün Stokta Yok.'
IF  EXISTS (SELECT *FROM #KAPSAMKONTROL) 
 BEGIN
	--STOKTA OLAN RAFIN USTLOKASOYNU ALINARAK AYNI SÜTUNDAKİ DİĞER RAFLARDA BOŞ RAF VAR MI DİYE BAKILIR. EĞER BOŞ RAF VARSA ÖNCE EN ÜST RAF ÖNERİLİR. TOPLAMA RAFLARI ÖNERİLMEZ. YOKSA YAKINDAKİ BOŞ RAF BULUNUR
	PRINT 'Ürün Kapsamda Var'
	
	IF NOT EXISTS (SELECT * FROM #ONERILOKASYON) 	--EĞER STOKTA VARSA VE STOKTA OLAN RAFLARA AIT SUTUN KOMPLE DOLUYSA YAKINDAKI BOS RAFLAR BULUNUR.
	BEGIN
	PRINT 'Ürünün okutulduğu kapsam sütunda boş raf yok'


	INSERT INTO #LOKASYON
	SELECT TOP 1 LNGKOD, TXTLOKASYONKOD, TXTLOKASYONKOD AS  TXTTANIM FROM (
	SELECT CASE WHEN (UBLOKDEGER-BLOKDEGER)<0 THEN (UBLOKDEGER-BLOKDEGER)*-1 WHEN (UBLOKDEGER-BLOKDEGER)>0 THEN (UBLOKDEGER-BLOKDEGER) WHEN (UBLOKDEGER-BLOKDEGER)=0 THEN 0 END  AS BLOKMESAFE, 
	CASE WHEN (USUTUN-SUTUN)<0 THEN (USUTUN-SUTUN)*-1  WHEN (USUTUN-SUTUN)>0 THEN  (USUTUN-SUTUN) WHEN (USUTUN-SUTUN)=0 THEN 0 END  AS SUTUNMESAFE,
	TXTLOKASYONKOD, LNGKOD FROM (
	SELECT SUBSTRING(TXTLOKASYONKOD,1,1) AS BLOK, CONVERT(INT,SUBSTRING(TXTLOKASYONKOD,3,2)) AS SUTUN, SUBSTRING(TXTLOKASYONKOD,6,2) AS RAF,  
		CASE WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='A' THEN 1
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='B' THEN 2
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='C' THEN 3
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='D' THEN 4
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='E' THEN 5
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='F' THEN 6
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='G' THEN 7
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='H' THEN 8
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='I' THEN 9
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='J' THEN 10
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='K' THEN 11
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='L' THEN 12
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='M' THEN 13
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='N' THEN 14
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='O' THEN 15
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='P' THEN 16
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='R' THEN 17
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='S' THEN 18
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='T' THEN 19
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='U' THEN 20
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='V' THEN 21
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='Y' THEN 22
	WHEN SUBSTRING(TXTLOKASYONKOD,1,1)='Z' THEN 23
	END AS BLOKDEGER,
	CASE WHEN SUBSTRING(UBLOK,1,1)='A' THEN 1
	WHEN SUBSTRING(UBLOK,1,1)='B' THEN 2
	WHEN SUBSTRING(UBLOK,1,1)='C' THEN 3
	WHEN SUBSTRING(UBLOK,1,1)='D' THEN 4
	WHEN SUBSTRING(UBLOK,1,1)='E' THEN 5
	WHEN SUBSTRING(UBLOK,1,1)='F' THEN 6
	WHEN SUBSTRING(UBLOK,1,1)='G' THEN 7
	WHEN SUBSTRING(UBLOK,1,1)='H' THEN 8
	WHEN SUBSTRING(UBLOK,1,1)='I' THEN 9
	WHEN SUBSTRING(UBLOK,1,1)='J' THEN 10
	WHEN SUBSTRING(UBLOK,1,1)='K' THEN 11
	WHEN SUBSTRING(UBLOK,1,1)='L' THEN 12
	WHEN SUBSTRING(UBLOK,1,1)='M' THEN 13
	WHEN SUBSTRING(UBLOK,1,1)='N' THEN 14
	WHEN SUBSTRING(UBLOK,1,1)='O' THEN 15
	WHEN SUBSTRING(UBLOK,1,1)='P' THEN 16
	WHEN SUBSTRING(UBLOK,1,1)='R' THEN 17
	WHEN SUBSTRING(UBLOK,1,1)='S' THEN 18
	WHEN SUBSTRING(UBLOK,1,1)='T' THEN 19
	WHEN SUBSTRING(UBLOK,1,1)='U' THEN 20
	WHEN SUBSTRING(UBLOK,1,1)='V' THEN 21
	WHEN SUBSTRING(UBLOK,1,1)='Y' THEN 22
	WHEN SUBSTRING(UBLOK,1,1)='Z' THEN 23
	END AS UBLOKDEGER,	
	* 
	FROM (SELECT * FROM #BOSLOKASYONLAR) BOSRAF 
	CROSS JOIN (SELECT * FROM( SELECT DISTINCT  SUBSTRING(TXTTANIMI,1,1) AS UBLOK , CONVERT(INT,SUBSTRING(TXTTANIMI,3,2)) AS USUTUN FROM #STOKDURUM)G)A
	WHERE BOSMIK>0 )SQL)SQL2 ORDER BY BLOKMESAFE, SUTUNMESAFE, TXTLOKASYONKOD
	
	
	SELECT LNGKOD AS LNGKOD,LNGKOD AS LOKASYON, TXTTANIMI AS TXTTANIMI  FROM #LOKASYON ORDER BY LNGKOD ASC
	PRINT 'En yakındaki boş raf bulundu.'


	END 

	ELSE 
	--STOKTAKI URUNE AIT RAFIN SUTUNUNA BAKILIP BOŞ OLAN RAF ÖNERİLİR
	BEGIN
	PRINT 'Stoktaki Ürünün Bulunduğu Raf Öneriliyor.'
	INSERT INTO #LOKASYON
	SELECT LNGKOD AS LNGKOD,LNGKOD AS LOKASYON, LOKASYON AS TXTTANIMI FROM #ONERILOKASYON

	SELECT LNGKOD AS LNGKOD,LNGKOD AS LOKASYON, TXTTANIMI AS TXTTANIMI  FROM #LOKASYON ORDER BY LNGKOD ASC

	END

 END

 ELSE
 BEGIN
	SELECT 1 AS LNGKOD , 1 AS LOKASYON ,'STOKTA YOK' AS TXTTANIMI

 END 
 END
 DROP TABLE #BOSLOKASYONLAR
DROP TABLE #ONERILOKASYON
DROP TABLE #USTLOKASYON
DROP TABLE #STOKDURUM

