CREATE PROCEDURE SSP_SBTOPLAMAEMRIDETAY
(
	@LNGYUKLEMEKOD INT,
	@TRHISLEMTARIHI DATETIME
)
AS
SELECT CONVERT(INT,0) AS LNGKOD, CONVERT(INT,0) AS LNGBASLIKKOD, CONVERT(INT,ROW_NUMBER() OVER(ORDER BY LNGMALZEMEKOD)) as LNGDETAYKOD,* FROM (
SELECT BD.LNGMALZEMEKOD,SUM(BD.DBLISLEMMIKTARI) AS DBLISLEMMIKTARI,
       BD.LNGISLEMOLCUBIRIMKOD,SUM(BD.DBLANAMIKTAR) AS DBLANAMIKTAR,BD.LNGANAOLCUBIRIMKOD,CONVERT(DECIMAL,0) AS DBLTOPLANANMIKTAR,SUM(ISNULL(BD.DBLNETAGIRLIK,0)) AS DBLNETAGIRLIK,BD.LNGAGIRLIKOLCUBIRIMKOD,
       BD.TXTKAYNAKBATCHNO,BD.TXTHEDEFBATCHNO,BD.TXTSERINO,NULL AS LNGKAYNAKLOKASYONKOD,L.LNGKOD AS LNGHEDEFLOKASYONKOD,BD.LNGKAYNAKSTATU,
       BD.LNGKAYNAKSTATU AS LNGHEDEFSTATU,BD.TXTPALETNO,BD.LNGMUADILBAGLANTI,BD.LNGANAURUNKOD,BD.TXTPO,BD.TXTPOLINE,BD.BYTARSIV,
       GETDATE() AS TRHILKISLEMTARIHI,GETDATE() AS TRHSONISLEMTARIHI,NULL AS LNGILKKULLANICIKOD,NULL AS LNGSONKULLANICIKOD,
       BD.TXTREFBELGEDETAYNO,BD.BYTPARAMBOLUNEMEZ,CONVERT(DECIMAL,0) AS DBLHAZIRLANANMIKTAR,BD.LNGANADETAYKOD,RB.LNGKOD AS LNGYUKLEMEKOD
FROM TBLSBDINAMIKROTABASLIK RB
       INNER JOIN TBLSBDINAMIKROTADETAY RD ON RB.LNGKOD=RD.LNGBASLIKKOD
       INNER JOIN TBLSBBELGEBASLIK BB ON RD.LNGBELGEKOD=BB.LNGKOD
       INNER JOIN TBLSBBELGEDETAY BD ON BB.LNGKOD=BD.LNGBASLIKKOD
       LEFT OUTER JOIN TBLSBLOKASYON L ON L.BYTRAMPA=1 AND L.LNGKOD=RB.LNGRAMPAKOD
WHERE  RB.LNGKOD=@LNGYUKLEMEKOD AND RD.TRHILKISLEMTARIHI > @TRHISLEMTARIHI 
GROUP BY BD.LNGMALZEMEKOD,BD.LNGISLEMOLCUBIRIMKOD,BD.LNGANAOLCUBIRIMKOD,BD.LNGAGIRLIKOLCUBIRIMKOD,
       BD.TXTKAYNAKBATCHNO,BD.TXTHEDEFBATCHNO,BD.TXTSERINO,L.LNGKOD ,BD.LNGKAYNAKSTATU,
       BD.LNGKAYNAKSTATU ,BD.TXTPALETNO,BD.LNGMUADILBAGLANTI,BD.LNGANAURUNKOD,BD.TXTPO,BD.TXTPOLINE,BD.BYTARSIV,
       BD.TXTREFBELGEDETAYNO,BD.BYTPARAMBOLUNEMEZ,BD.LNGANADETAYKOD,RB.LNGKOD) A 