CREATE PROCEDURE [dbo].[SSP_SBBELGEPLANLAMA]  
@LNGBELGEKOD AS INT  
AS  
SELECT BD.LNGKOD AS LNGKOD,BD.LNGMALZEMEKOD AS LNGURUNKOD,U.TXTKOD AS TXTURUNKOD2,U.TXTAD AS TXTURUNACIKLAMA,G.TXTKOD AS TXTURUNGRUPKOD,
DBLISLEMMIKTARI AS DBLISLEMMIKTARI,B.LNGKOD AS LNGBIRIMKOD,NULL AS DBLPARCA1,NULL AS DBLPARCA2,NULL AS DBLPARCA3,NULL AS DBLPARCA4,NULL AS DBLPARCA5,
'' AS TXTEKSAHA11,'' AS TXTEKSAHA21,'' AS TXTEKSAHA31,'' AS TXTEKSAHA41,'' AS TXTEKSAHA51,
'' AS TXTEKSAHA12,'' AS TXTEKSAHA22,'' AS TXTEKSAHA32,'' AS TXTEKSAHA42,'' AS TXTEKSAHA52,
NULL AS DBLSTOKMIKTARI

FROM TBLSBBELGEDETAY BD 
INNER JOIN TBLSBBIRIM B ON B.LNGKOD = BD.LNGISLEMOLCUBIRIMKOD
LEFT JOIN TBLSBURUNEKGRUPBAGLANTI UGB ON BD.LNGMALZEMEKOD = UGB.LNGURUNKOD  AND UGB.LNGSIRANO=1
LEFT JOIN TBLSBGRUP G ON G.LNGKOD = UGB.LNGGRUPKOD
LEFT JOIN TBLURUN U ON U.LNGKOD=BD.LNGMALZEMEKOD
WHERE LNGBASLIKKOD = @LNGBELGEKOD