CREATE PROCEDURE [dbo].[SSP_SBYONLENDIRMEKONTROL_ORIJINAL]
(
	@LNGLOKASYON int,
	@BYTLOKASYONTIPI INT, 	
	@LNGKAYNAKLOKASYON int,
	@LNGMALZEME int,
	@TXTKONTROLSAHASI NVARCHAR(50),
	@KONTROLSAHASIDEGERI NVARCHAR(30),
	@DBLOKUTULANMIKTAR DECIMAL,
	@BYTARTANSIRALAMA bit,
	@TXTPALETNO NVARCHAR(20)
)
AS
DECLARE @SQL NVARCHAR(4000),@SQL2 NVARCHAR(4000),@SQL3 NVARCHAR(4000)
CREATE TABLE #LOC (LNGKOD INT,TXTTANIMI NVARCHAR(50))

	INSERT INTO #LOC(LNGKOD,TXTTANIMI)
	(SELECT LNGKOD,TXTTANIMI FROM FNC_SBLOKASYON(@LNGLOKASYON,@BYTLOKASYONTIPI,1) )

SET @SQL2='SELECT TOP 1000 LOK.LNGKOD AS LOKASYON,TXTTANIMI,KAPASITE.DBLMIKTAR AS KAPASITE_MIKTARI,STOKDURUM.MIKTAR AS STOK_MIKTARI,KAPSAM.MIKTAR AS KAPSAM_MIKTARI
,CASE WHEN NOT STOKDURUM.MIKTAR IS NULL OR NOT KAPSAM.MIKTAR IS NULL THEN 1 ELSE 0 END  KAYITDURUM
 FROM #LOC AS LOK  
	LEFT JOIN (SELECT CASE WHEN LGB.LNGLOKASYONKOD IS NOT NULL THEN LGB.LNGLOKASYONKOD ELSE KAP.LNGLOKASYONBAGLANTIKODU END AS LOKASYON,DBLMIKTAR,DBLPALETMIKTAR 
				FROM TBLSBLOKASYONKAPASITE KAP
					LEFT JOIN TBLSBLOKASYONGRUPBAGLANTI LGB ON LGB.LNGGRUPKOD = KAP.LNGLOKASYONBAGLANTIKODU 
					LEFT JOIN TBLSBURUNEKGRUPBAGLANTI UEB WITH(NOLOCK) ON KAP.BYTMALZEMEBAGLANTITIPI = UEB.LNGSIRANO + 2 AND KAP.LNGMALZEMEBAGLANTIKODU=UEB.LNGKOD 
					LEFT OUTER JOIN TBLURUN U WITH(NOLOCK) ON KAP.BYTMALZEMEBAGLANTITIPI=1 AND U.LNGDETAYTIPI=KAP.LNGMALZEMEBAGLANTIKODU  
				WHERE ((BYTLOKASYONBAGLANTITIPI=1) OR (BYTLOKASYONBAGLANTITIPI=0 AND NOT LGB.LNGKOD IS NULL)) AND 
				((BYTMALZEMEBAGLANTITIPI=0 AND LNGMALZEMEBAGLANTIKODU=' + CONVERT(NVARCHAR(20),@LNGMALZEME) + ') OR 
				(BYTMALZEMEBAGLANTITIPI>0 AND NOT LNGURUNKOD IS NULL) OR (BYTMALZEMEBAGLANTITIPI=99) OR (BYTMALZEMEBAGLANTITIPI=1 AND U.LNGKOD=' + CONVERT(NVARCHAR(20),@LNGMALZEME) + '))
			   ) AS KAPASITE ON LOK.LNGKOD=KAPASITE.LOKASYON
	LEFT JOIN (SELECT LNGLOKASYONKOD,ISNULL(SUM(DBLANAMIKTAR),0) AS MIKTAR FROM TBLSBSTOKDURUM GROUP BY LNGLOKASYONKOD,' + @TXTKONTROLSAHASI + ') AS STOKDURUM ON LOK.LNGKOD=STOKDURUM.LNGLOKASYONKOD 
	LEFT JOIN (SELECT DISTINCT LNGLOKASYONKOD,COUNT(LNGPALETID) AS MIKTAR FROM TBLSBSTOKDURUM GROUP BY LNGLOKASYONKOD,' + @TXTKONTROLSAHASI + ') AS PALETCOUNT ON LOK.LNGKOD=PALETCOUNT.LNGLOKASYONKOD 
	LEFT JOIN (SELECT TBLSBBELGEKAPSAM.LNGHEDEFLOKASYONKOD,' + @TXTKONTROLSAHASI + ',ISNULL(SUM(DBLMIKTAR),0)AS MIKTAR 
				FROM TBLSBBELGEKAPSAM 
					INNER JOIN TBLSBBELGEDETAY ON TBLSBBELGEDETAY.LNGBASLIKKOD=TBLSBBELGEKAPSAM.LNGBASLIKKOD AND TBLSBBELGEDETAY.LNGKOD=TBLSBBELGEKAPSAM.LNGDETAYKOD 
					INNER JOIN TBLSBBELGEBASLIK ON  TBLSBBELGEBASLIK.LNGKOD=TBLSBBELGEDETAY.LNGBASLIKKOD 
					INNER JOIN #LOC L ON L.LNGKOD=TBLSBBELGEKAPSAM.LNGHEDEFLOKASYONKOD
				WHERE TRHONAYTARIHI IS NULL 
				GROUP BY TBLSBBELGEKAPSAM.LNGHEDEFLOKASYONKOD,' + @TXTKONTROLSAHASI + '
				) AS KAPSAM ON LOK.LNGKOD=KAPSAM.LNGHEDEFLOKASYONKOD AND KAPSAM.' + @TXTKONTROLSAHASI + '= ''' + @KONTROLSAHASIDEGERI+ ''''
SET @SQL3=' LEFT JOIN (SELECT DISTINCT TBLSBBELGEKAPSAM.LNGHEDEFLOKASYONKOD,' + @TXTKONTROLSAHASI + ',COUNT(TBLSBBELGEKAPSAM.TXTPALETNO) AS MIKTAR 
						FROM TBLSBBELGEKAPSAM 
							INNER JOIN TBLSBBELGEDETAY ON TBLSBBELGEDETAY.LNGBASLIKKOD=TBLSBBELGEKAPSAM.LNGBASLIKKOD AND TBLSBBELGEDETAY.LNGKOD=TBLSBBELGEKAPSAM.LNGDETAYKOD 
							INNER JOIN TBLSBBELGEBASLIK ON  TBLSBBELGEBASLIK.LNGKOD=TBLSBBELGEDETAY.LNGBASLIKKOD 
							INNER JOIN #LOC L ON L.LNGKOD=TBLSBBELGEKAPSAM.LNGHEDEFLOKASYONKOD
						WHERE TRHONAYTARIHI IS NULL 
						GROUP BY TBLSBBELGEKAPSAM.LNGHEDEFLOKASYONKOD,' + @TXTKONTROLSAHASI + '
						) AS KAPSAMPALET ON LOK.LNGKOD=KAPSAMPALET.LNGHEDEFLOKASYONKOD 
WHERE  CASE WHEN NOT KAPASITE.DBLMIKTAR IS NULL AND KAPASITE.DBLMIKTAR<>0 AND KAPASITE.DBLMIKTAR>=' + CONVERT(NVARCHAR(20),@DBLOKUTULANMIKTAR) + '+ISNULL(STOKDURUM.MIKTAR,0)+ISNULL(KAPSAM.MIKTAR,0) THEN 1 
			WHEN (KAPASITE.DBLMIKTAR IS NULL OR KAPASITE.DBLMIKTAR=0) AND (KAPASITE.DBLPALETMIKTAR IS NULL OR KAPASITE.DBLPALETMIKTAR = 0) THEN 1 
			WHEN (KAPASITE.DBLMIKTAR IS NULL OR KAPASITE.DBLMIKTAR=0) AND (KAPASITE.DBLPALETMIKTAR IS NOT NULL AND KAPASITE.DBLPALETMIKTAR <> 0) AND ''' + @TXTPALETNO + ''' <>'''' 
				AND ISNULL(PALETCOUNT.MIKTAR,0) + ISNULL(KAPSAMPALET.MIKTAR,0) +1 <= KAPASITE.DBLPALETMIKTAR THEN 1
ELSE 0 END=1 
ORDER BY KAYITDURUM DESC,LOKASYON'
IF @BYTARTANSIRALAMA=0 SET @SQL2 +=' DESC'


PRINT(@SQL)
PRINT(@SQL2)
PRINT(@SQL3)

EXEC (@SQL+@SQL2+@SQL3)