CREATE PROCEDURE [dbo].[SSP_SBLOKASYONKAPASITEKONTROL]  
(  
 @LNGLOKASYONKOD int,  
 @LNGMALZEMEKOD int,  
 @DBLKAPASITEMIKTAR decimal,  
 @DBLPALETMIKTAR decimal,  
 @TXTPALETNO nvarchar(20),  
 @DBLTOLERANSMIKTAR decimal,  
 @DBLOKUTULANMIKTAR decimal,
 @BYTTUMMALZEMELER TINYINT = 0
)  
AS  
  
DECLARE @STOKMIKTAR AS DECIMAL=0  
DECLARE @KAPSAMMIKTAR AS DECIMAL=0  
DECLARE @LNGPALETID AS INT=0  
DECLARE @SQL NVARCHAR(4000)  
  
IF @DBLPALETMIKTAR>0   
BEGIN  
SELECT @LNGPALETID=LNGKOD FROM TBLSBPALET WHERE TXTPALETNO=@TXTPALETNO  
IF @LNGPALETID=0  
BEGIN  
SET @STOKMIKTAR = (SELECT COUNT(LNGPALETID) P FROM (SELECT  DISTINCT LNGPALETID FROM TBLSBSTOKDURUM WHERE LNGLOKASYONKOD=@LNGLOKASYONKOD) A)  
END  
ELSE  
SET @STOKMIKTAR = (SELECT  DISTINCT COUNT(LNGPALETID) FROM TBLSBSTOKDURUM WHERE LNGLOKASYONKOD=@LNGLOKASYONKOD AND LNGPALETID<>@LNGPALETID)  
  
SET @KAPSAMMIKTAR= (SELECT DISTINCT COUNT(TBLSBBELGEKAPSAM.TXTPALETNO) 
FROM TBLSBBELGEBASLIK   
		INNER JOIN TBLSBBELGEDETAY ON TBLSBBELGEBASLIK.LNGKOD=TBLSBBELGEDETAY.LNGBASLIKKOD AND TRHONAYTARIHI IS NULL 
		INNER JOIN TBLSBBELGEKAPSAM ON  TBLSBBELGEDETAY.LNGKOD=TBLSBBELGEKAPSAM.LNGDETAYKOD   
WHERE TBLSBBELGEKAPSAM.LNGHEDEFLOKASYONKOD=@LNGLOKASYONKOD AND TBLSBBELGEKAPSAM.TXTPALETNO<>ISNULL(@TXTPALETNO,''))  
END  
ELSE  
BEGIN  
IF @BYTTUMMALZEMELER=0
BEGIN
	SELECT @STOKMIKTAR=ISNULL(SUM(DBLANAMIKTAR),0) FROM TBLSBSTOKDURUM WHERE LNGLOKASYONKOD=@LNGLOKASYONKOD AND LNGMALZEMEKOD=@LNGMALZEMEKOD  
	SELECT @KAPSAMMIKTAR=ISNULL(SUM(DBLMIKTAR),0) 
	FROM TBLSBBELGEBASLIK   
			INNER JOIN TBLSBBELGEDETAY ON TBLSBBELGEBASLIK.LNGKOD=TBLSBBELGEDETAY.LNGBASLIKKOD AND TRHONAYTARIHI IS NULL 
			INNER JOIN TBLSBBELGEKAPSAM ON  TBLSBBELGEDETAY.LNGKOD=TBLSBBELGEKAPSAM.LNGDETAYKOD   
	WHERE TBLSBBELGEKAPSAM.LNGHEDEFLOKASYONKOD=@LNGLOKASYONKOD AND LNGMALZEMEKOD=@LNGMALZEMEKOD
END
ELSE
BEGIN
	SELECT @STOKMIKTAR=ISNULL(SUM(DBLANAMIKTAR),0) FROM TBLSBSTOKDURUM WHERE LNGLOKASYONKOD=@LNGLOKASYONKOD
	SELECT @KAPSAMMIKTAR=ISNULL(SUM(DBLMIKTAR),0) 
	FROM TBLSBBELGEBASLIK   
			INNER JOIN TBLSBBELGEDETAY ON TBLSBBELGEBASLIK.LNGKOD=TBLSBBELGEDETAY.LNGBASLIKKOD AND TRHONAYTARIHI IS NULL 
			INNER JOIN TBLSBBELGEKAPSAM ON  TBLSBBELGEDETAY.LNGKOD=TBLSBBELGEKAPSAM.LNGDETAYKOD   
	WHERE TBLSBBELGEKAPSAM.LNGHEDEFLOKASYONKOD=@LNGLOKASYONKOD
END
	

END  
  
PRINT '@STOKMIKTAR=' + CONVERT(NVARCHAR(10),@STOKMIKTAR)  
PRINT '@KAPSAMMIKTAR=' + CONVERT(NVARCHAR(10),@KAPSAMMIKTAR)  
PRINT '@DBLOKUTULANMIKTAR=' + CONVERT(NVARCHAR(10),@DBLOKUTULANMIKTAR)  
PRINT '@DBLKAPASITEMIKTAR=' + CONVERT(NVARCHAR(10),@DBLKAPASITEMIKTAR)  
PRINT '@DBLPALETMIKTAR=' + CONVERT(NVARCHAR(10),@DBLPALETMIKTAR)  
PRINT '@DBLTOLERANSMIKTAR=' + CONVERT(NVARCHAR(10),@DBLTOLERANSMIKTAR)  
PRINT @STOKMIKTAR + @KAPSAMMIKTAR + @DBLOKUTULANMIKTAR  
  
IF @DBLPALETMIKTAR>0   
BEGIN  
PRINT 'PALET'  
IF @STOKMIKTAR + @KAPSAMMIKTAR + @DBLOKUTULANMIKTAR<= @DBLPALETMIKTAR + @DBLTOLERANSMIKTAR  
SELECT 'TRUE' AS KAPASITEUYGUN  
END  
ELSE  
BEGIN  
IF @STOKMIKTAR + @KAPSAMMIKTAR + @DBLOKUTULANMIKTAR<= @DBLKAPASITEMIKTAR + @DBLTOLERANSMIKTAR  
SELECT 'TRUE' AS KAPASITEUYGUN  
END