CREATE PROCEDURE [dbo].[SSP_SBSTOKKONTROLU]        
(        
  @TXTMUSTERI NVARCHAR(1000),        
  @TXTMALZEME NVARCHAR(100),        
  @TXTSTATU NVARCHAR(100),        
  @TXTPALET NVARCHAR(1000),        
  @TXTMIKTAR NVARCHAR(100),        
  @TXTLOKASYON NVARCHAR(100),        
  @TXTREZERVEBELGE NVARCHAR(100),        
  @TXTREZERVEBELGETIP NVARCHAR(100),        
  @TXTPO NVARCHAR(100),        
  @TXTPOLINE NVARCHAR(100),        
  @TXTBATCHNO NVARCHAR(100),        
  @TXTSERINO NVARCHAR(100)        
)        
AS        
DECLARE @WHERE AS NVARCHAR(4000)        
DECLARE @SQL AS NVARCHAR(4000)        
DECLARE @CNT INT        
DECLARE @BELGENO AS NVARCHAR(1000)  
DECLARE @PALETBILDNO AS NVARCHAR(1000)  
  
  
CREATE TABLE #TEMP (LNGKOD INT,LNGLOKASYON INT,LNGREZERVEBELGE INT,LNGMUSTERIKOD INT,LNGMALZEMEKOD INT, LNGSTATUKOD INT, TXTBATCHNO NVARCHAR(50), TXTSERINO NVARCHAR(50), TXTPO NVARCHAR(10), TXTPOLINE NVARCHAR(6), LNGREZERVEBELGEKOD INT, LNGREZERVEBELGETIPKOD INT)        
SET @SQL = 'DELETE FROM #TEMP        
   INSERT INTO #TEMP SELECT LNGKOD,LNGLOKASYONKOD,LNGREZERVEBELGEKOD,LNGMUSTERIKOD,LNGMALZEMEKOD,LNGSTATUKOD,TXTBATCHNO,TXTSERINO,TXTPO,TXTPOLINE,LNGREZERVEBELGEKOD,LNGREZERVEBELGETIPKOD FROM TBLSBSTOKDURUM WITH(NOLOCK) WHERE '         
IF @TXTMALZEME<>''    
BEGIN    
 EXEC (@SQL + @TXTMALZEME )        
 SET @WHERE = @TXTMALZEME        
 PRINT(1)        
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN        
 PRINT(2)        
 PRINT(@SQL + @WHERE)        
 --EXEC (@SQL + @TXTMALZEME)         
          
 --MalzemeStoktaYok  
 PRINT('AA')      
 SELECT '1' AS MSGNO   
 PRINT('BB')     
 RETURN        
 END    
 END    
 ELSE    
 BEGIN    
 PRINT(' 1=1 ')    
 SET @WHERE = ' 1=1 '    
 END       
        
IF @TXTSTATU <> ''        
BEGIN        
 PRINT(3)        
 PRINT(@SQL + @WHERE)        
 EXEC (@SQL + @WHERE + ' AND ' + @TXTSTATU)        
 SET @WHERE = @WHERE + ' AND ' + @TXTSTATU        
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN        
  --StatuStoktaYok        
  SELECT '2' AS MSGNO        
  RETURN        
 END        
END        
        
IF @TXTPALET <> ''        
BEGIN        
 PRINT(4)        
 PRINT(@SQL)    
 PRINT(@WHERE)        
 EXEC (@SQL + @WHERE + ' AND ' + @TXTPALET)        
 SET @WHERE = @WHERE + ' AND ' + @TXTPALET        
  SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN        
  --PaletStoktaYok        
  SELECT '3' AS MSGNO        
  RETURN        
 END        
END        
        
IF @TXTBATCHNO <> ''        
BEGIN        
 PRINT(@SQL + @WHERE)        
 EXEC (@SQL + @WHERE + ' AND ' + @TXTBATCHNO)        
 SET @WHERE = @WHERE + ' AND ' + @TXTBATCHNO        
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN        
  --BatchStok        
  SELECT '4' AS MSGNO        
  RETURN        
 END        
END        
        
IF @TXTSERINO <> ''        
BEGIN        
 PRINT(@SQL + @WHERE)        
 EXEC (@SQL + @WHERE + ' AND ' + @TXTSERINO)        
 SET @WHERE = @WHERE + ' AND ' + @TXTSERINO        
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN        
  --SeriStok        
  SELECT '5' AS MSGNO        
  RETURN        
 END        
END        
            
IF @TXTLOKASYON <> ''        
BEGIN        
 PRINT(@SQL + @WHERE)        
 EXEC (@SQL + @WHERE + ' AND ' +@TXTLOKASYON)        
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN        
  EXEC (@SQL + @WHERE)        
  --UygunLokasyondaStoktaYok        
  SELECT '7' AS MSGNO,  LNGKOD, LNGLOKASYON FROM #TEMP        
  RETURN        
 END        
 SET @WHERE = @WHERE + ' AND ' + @TXTLOKASYON        
END        
    
IF @TXTMIKTAR <> ''        
BEGIN        
 PRINT(@SQL + @WHERE)        
 EXEC (@SQL + @WHERE + ' AND ' + @TXTMIKTAR)        
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN   
  EXEC (@SQL + @WHERE)  
  --SELECT * FROM #TEMP  
SELECT @BELGENO = CONVERT(NVARCHAR(1000),(
 SELECT DISTINCT B.TXTKOD + ' ,'  
 FROM TBLSBBELGEKAPSAM K  WITH(NOLOCK)
  INNER JOIN TBLSBBELGEBASLIK B WITH(NOLOCK) ON K.LNGBASLIKKOD=B.LNGKOD AND B.TRHONAYTARIHI IS NULL  
  INNER JOIN TBLSBBELGEDETAY D WITH(NOLOCK) ON K.LNGDETAYKOD=D.LNGKOD  
  INNER JOIN #TEMP T ON  T.LNGMALZEMEKOD=D.LNGMALZEMEKOD AND T.TXTBATCHNO=K.TXTBATCHNO AND T.LNGLOKASYON=K.LNGKAYNAKLOKASYONKOD   
     AND T.LNGSTATUKOD=K.LNGKAYNAKSTATU AND T.TXTSERINO=K.TXTSERINO   
     AND CASE WHEN T.TXTPO IS NULL THEN '' ELSE T.TXTPO END = CASE WHEN K.TXTPO IS NULL THEN '' ELSE K.TXTPO END   
     AND CASE WHEN T.TXTPOLINE IS NULL THEN '' ELSE T.TXTPOLINE END = CASE WHEN K.TXTPOLINE IS NULL THEN '' ELSE K.TXTPOLINE END   
     AND CASE WHEN T.LNGMUSTERIKOD IS NULL THEN 0 ELSE T.LNGMUSTERIKOD END= CASE WHEN K.LNGCARIKOD IS NULL THEN 0 ELSE K.LNGCARIKOD END   
     AND CASE WHEN T.LNGREZERVEBELGEKOD IS NULL THEN 0 ELSE T.LNGREZERVEBELGEKOD END =  
      CASE WHEN K.LNGREZERVEBELGEKOD IS NULL THEN 0 ELSE K.LNGREZERVEBELGEKOD END   
     AND CASE WHEN T.LNGREZERVEBELGETIPKOD IS NULL THEN 0 ELSE T.LNGREZERVEBELGETIPKOD END =  
      CASE WHEN K.LNGREZERVEBELGETIPKOD IS NULL THEN 0 ELSE K.LNGREZERVEBELGETIPKOD END
	   FOR XML PATH('')
	  ))
 PRINT(@BELGENO)  
   
 SELECT @PALETBILDNO = CONVERT(NVARCHAR(1000),(SELECT CONVERT(NVARCHAR,B.LNGKOD) + '-' + B.TXTPALETNO + ' ,'  
 FROM TBLSBPALETBILDIRIMDETAY D  WITH(NOLOCK)
  INNER JOIN TBLSBPALETBILDIRIMBASLIK B WITH(NOLOCK) ON D.LNGBASLIKKOD=B.LNGKOD AND B.TRHONAYTARIHI IS NULL  
 WHERE EXISTS (SELECT SD.LNGKOD   
    FROM TBLSBSTOKDURUM SD WITH(NOLOCK)  
     INNER JOIN #TEMP T ON SD.LNGKOD=T.LNGKOD  
    WHERE SD.LNGMALZEMEKOD=D.LNGURUNKOD AND SD.TXTBATCHNO=D.TXTBATCHNO AND SD.LNGLOKASYONKOD=D.LNGLOKASYONKOD   
     AND SD.LNGSTATUKOD=D.LNGSTATUKOD AND SD.TXTSERINO=D.TXTSERINO   
     AND CASE WHEN SD.TXTPO IS NULL THEN '' ELSE SD.TXTPO END= CASE WHEN D.TXTPO IS NULL THEN '' ELSE D.TXTPO END   
     AND CASE WHEN SD.TXTPOLINE IS NULL THEN '' ELSE SD.TXTPOLINE END= CASE WHEN D.TXTPOLINE IS NULL THEN '' ELSE D.TXTPOLINE END   
     AND CASE WHEN SD.LNGMUSTERIKOD IS NULL THEN 0 ELSE SD.LNGMUSTERIKOD END= CASE WHEN D.LNGCARIKOD IS NULL THEN 0 ELSE D.LNGCARIKOD END   
     AND CASE WHEN SD.LNGREZERVEBELGEKOD IS NULL THEN 0 ELSE SD.LNGREZERVEBELGEKOD END =  
      CASE WHEN D.LNGREZERVEBELGEKOD IS NULL THEN 0 ELSE D.LNGREZERVEBELGEKOD END    
     AND CASE WHEN SD.LNGREZERVEBELGETIPKOD IS NULL THEN 0 ELSE SD.LNGREZERVEBELGETIPKOD END =  
      CASE WHEN D.LNGREZERVEBELGETIPKOD IS NULL THEN 0 ELSE D.LNGREZERVEBELGETIPKOD END)  
        FOR XML PATH('')))         
  PRINT(@PALETBILDNO)  
    
  IF @BELGENO IS NOT NULL   
  SET @BELGENO= 'Okutulan Belge(ler):   
  ' + SUBSTRING(@BELGENO,1,LEN(@BELGENO) - 1) + ' '  
  ELSE  
  SET @BELGENO=''  
  IF @PALETBILDNO <> ''  
  SET @BELGENO=@BELGENO + 'Okutulan Palet Bildirim Belge(ler):   
  ' + SUBSTRING(@PALETBILDNO,1,LEN(@PALETBILDNO)-1)  
  --MiktaraUygunStoktaYok      
        
  SELECT '6' AS MSGNO  ,  LNGKOD, LNGLOKASYON,@BELGENO AS OKUTULAN   FROM #TEMP        
  RETURN        
 END      
  SET @WHERE = @WHERE + ' AND ' + @TXTMIKTAR         
END    
    
IF @TXTREZERVEBELGE <> ''        
BEGIN   
PRINT('8')     
 PRINT(@SQL + @WHERE)   
 DECLARE @BELGEKOD AS NVARCHAR(20)=''
  SELECT @BELGEKOD=BB.TXTKOD FROM #TEMP
  INNER JOIN TBLSBBELGEBASLIK BB ON #TEMP.LNGREZERVEBELGE=BB.LNGKOD
 EXEC (@SQL + @WHERE + ' AND ' + @TXTREZERVEBELGE)        
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN        

  EXEC (@SQL + @WHERE)        
  --RezerveliStok     
  
  SELECT '8' AS MSGNO, @BELGEKOD AS TXTKOD-- #TEMP.LNGKOD,LNGREZERVEBELGE ,BB.TXTKOD
  FROM #TEMP        
	
  RETURN        
 END        
 SET @WHERE = @WHERE + ' AND ' + @TXTREZERVEBELGE 
END        
        
IF @TXTREZERVEBELGETIP <> ''        
BEGIN 
PRINT('9')        
 PRINT(@SQL + @WHERE)        
 EXEC (@SQL + @WHERE  + ' AND ' + @TXTREZERVEBELGETIP)        
 SET @WHERE = @WHERE + ' AND ' + @TXTREZERVEBELGETIP        
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN        
  --RezerveTipliStok        
  SELECT '9' AS MSGNO       
  RETURN   
 END        
END        
       
IF @TXTPO <> ''        
BEGIN        
 PRINT(@SQL + @WHERE)        
 EXEC (@SQL + @WHERE + ' AND ' + @TXTPO)        
 SET @WHERE = @WHERE + ' AND ' + @TXTPO        
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN        
  --PoStok        
  SELECT '10' AS MSGNO        
  RETURN        
 END        
END        
        
IF @TXTPOLINE <> ''        
BEGIN        
 PRINT(@SQL + @WHERE)        
 EXEC (@SQL + @WHERE + ' AND ' + @TXTPOLINE)        
 SET @WHERE = @WHERE + ' AND ' + @TXTPOLINE        
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP        
 IF @CNT=0        
 BEGIN        
  --PoLineStok        
  SELECT '11' AS MSGNO        
  RETURN        
 END        
END 
IF @TXTMUSTERI <> ''        
BEGIN        
 PRINT(@SQL + @WHERE)        
 EXEC (@SQL + @WHERE + ' AND ' + @TXTMUSTERI)        
      
 SELECT @CNT=COUNT(LNGKOD) FROM #TEMP             
  IF @CNT=0        
 BEGIN        
  EXEC (@SQL + @WHERE)        
      
  SELECT '12' AS MSGNO,LNGMUSTERIKOD FROM #TEMP        
  RETURN        
 END        
 SET @WHERE = @WHERE + ' AND ' + @TXTMUSTERI              
END 
