CREATE PROCEDURE [dbo].[SSP_SBPPCKONTROLLUSAYIM]
(      
 @LNGBELGEKOD NVARCHAR (MAX),
 @TXTREFBELGEKOD NVARCHAR(200)
)      
AS
DECLARE @SQL NVARCHAR (MAX)  
DECLARE @SAYIMJOIN NVARCHAR(2000)=''


IF @TXTREFBELGEKOD<>''
BEGIN
SET @SAYIMJOIN= 'LEFT JOIN TBLSBKONTROLSAYIMBASLIK SB ON SB.TXTREFBELGEKOD=''' + @TXTREFBELGEKOD + ''''
END
ELSE
BEGIN
SET @SAYIMJOIN= 'LEFT JOIN TBLSBKONTROLSAYIMBASLIK SB ON SB.LNGBELGEKOD=' + @LNGBELGEKOD
END


SET @SQL='SELECT ROW_NUMBER() over (order by BELGE.LNGMALZEMEKOD )LNGKOD, (SELECT TXTKOD FROM TBLURUN WHERE LNGKOD=BELGE.LNGMALZEMEKOD) TXTURUNKOD,BELGE.DBLISLEMMIKTARI AS DBLSEVKIYATMIKTAR,(SELECT TXTKOD FROM TBLSBBIRIM WHERE LNGKOD= BELGE.LNGISLEMOLCUBIRIMKOD) TXTBIRIM,ISNULL(SD.DBLISLEMMIKTAR,0) AS DBLSAYILANMIKTAR,ISNULL(BELGE.DBLISLEMMIKTARI,0)-ISNULL(SD.DBLISLEMMIKTAR,0) AS DBLFARK
       FROM (
	select DET.LNGMALZEMEKOD,SUM(DET.DBLISLEMMIKTARI) AS DBLISLEMMIKTARI,DET.LNGISLEMOLCUBIRIMKOD 
	from TBLSBBELGEDETAY DET INNER JOIN TBLSBBELGEBASLIK BAS ON DET.LNGBASLIKKOD=BAS.LNGKOD 
	 WHERE BAS.LNGKOD IN('+@LNGBELGEKOD+')
	 GROUP BY DET.LNGMALZEMEKOD,DET.LNGISLEMOLCUBIRIMKOD ) BELGE '
+ @SAYIMJOIN +
'LEFT JOIN TBLSBKONTROLSAYIMDETAY SD ON SB.LNGKOD=SD.LNGBASLIKKOD AND SD.LNGMALZEMEKOD=BELGE.LNGMALZEMEKOD'



PRINT @SQL
EXEC (@SQL)