CREATE PROCEDURE [dbo].[SSP_SBONAYIPTALSTOKKONTROL]  
(  
@LNGBELGEKOD INT  
)  
AS  
SELECT ISNULL(MIN(CASE WHEN (S.DBLANAMIKTAR-S.DBLREZERVEMIKTAR- D.DBLANAMIKTAR)>= 0 THEN 1 ELSE 0 END ),0)AS BYTUYGUN  
FROM TBLSBSTOKDURUM S  
LEFT JOIN TBLSBPALET P ON P.LNGKOD = S.LNGPALETID  
INNER JOIN TBLSBOPERASYONBELGEDETAY D ON D.BYTGIRISCIKIS=1 AND D.LNGURUNKOD=S.LNGMALZEMEKOD  AND ISNULL(P.TXTPALETNO,'') = ISNULL(D.TXTPALETNO,'') AND S.LNGLOKASYONKOD = D.LNGLOKASYONKOD AND   
ISNULL(D.TXTBATCHNO,'') = ISNULL(S.TXTBATCHNO,'') AND ISNULL(D.TXTSERINO,'') = ISNULL(S.TXTSERINO,'') AND ISNULL(D.TXTPO,'')= ISNULL(S.TXTPO,'')  AND ISNULL(D.TXTPOLINE,'') = ISNULL(S.TXTPOLINE,'')  
--INNER JOIN TBLSBOPERASYONBELGEBASLIK OB ON OB.LNGKOD = D.LNGBASLIKKOD   
INNER JOIN (SELECT MAX(LNGKOD) AS LNGKOD, LNGREFBELGENO FROM TBLSBOPERASYONBELGEBASLIK GROUP BY LNGREFBELGENO) OB ON OB.LNGKOD=D.LNGBASLIKKOD  
INNER JOIN TBLSBBELGEBASLIK B ON OB.LNGREFBELGENO = B.LNGKOD  
INNER JOIN TBLSBOPERASYONTIPI O ON B.LNGOPERASYONTIPKOD = O.LNGKOD  
WHERE  B.LNGKOD =@LNGBELGEKOD 