CREATE PROCEDURE [dbo].[SSP_SBKAPASITEORAN]  
(  
 @USTLOKASYON INT,
 @KULLANICI INT
)  
AS  
DECLARE @LOKASYON INT  
DECLARE @ALTLOKASYON INT  
DECLARE @MALZEME INT  
DECLARE @MIKTAR INT  
DECLARE @PALETSAYI INT  
DECLARE @BIRIM INT  
DECLARE @STOKMIKTAR DECIMAL(28,3)  
DECLARE @TOPLAMSTOKMIKTAR DECIMAL(28,3)  
DECLARE @ORAN DECIMAL(28,3)  
DECLARE @LOKASYONTEXT NVARCHAR(20)  
DECLARE @BIRIMTEXT NVARCHAR(10)  
  
DECLARE @KAPASITE Table(LOKASYON INT,LOKASYONTEXT NVARCHAR(20),DBLORAN DECIMAL(28,3),DBLMIKTAR DECIMAL(28,8),LNGBIRIM INT,BIRIMTEXT NVARCHAR(10))  


DECLARE TEMPLOK CURSOR SCROLL FOR    
	SELECT LNGKOD,TXTLOKASYONKOD FROM TBLSBLOKASYON WHERE LNGUSTKOD=@USTLOKASYON  
OPEN TEMPLOK    
 FETCH FIRST FROM TEMPLOK INTO @LOKASYON,@LOKASYONTEXT 
 WHILE  @@FETCH_STATUS = 0    
 BEGIN     
   
		 SET @ORAN=0  
		 SET @TOPLAMSTOKMIKTAR=0  
		 SET @BIRIM=0  
		 SET @BIRIMTEXT=''  
		 print('ilkCursor')   
		 DECLARE TEMPALTLOK CURSOR SCROLL FOR    
			WITH LOC(LNGKOD) AS   
				 (  
				  SELECT LNGKOD  
				  FROM TBLSBLOKASYON WHERE LNGUSTKOD =@LOKASYON OR LNGKOD =@LOKASYON  
					AND LNGDISTKOD IN (SELECT CONVERT(INT,TXTKOD) 
										FROM TBLKULLANICIYETKIDETAY 
										WHERE LNGKULLANICIKOD = @KULLANICI AND LNGYETKIKOD = (SELECT LNGKOD FROM TBLYETKI WHERE LNGREHBERLISTEKOD=34))
				  UNION ALL  
				  SELECT E.LNGKOD  
				  FROM TBLSBLOKASYON AS e  
						 INNER JOIN LOC AS d  
				   ON e.LNGUSTKOD = D.LNGKOD
				  WHERE LNGDISTKOD IN (SELECT CONVERT(INT,TXTKOD) 
										FROM TBLKULLANICIYETKIDETAY 
										WHERE LNGKULLANICIKOD = @KULLANICI AND LNGYETKIKOD = (SELECT LNGKOD FROM TBLYETKI WHERE LNGREHBERLISTEKOD=34))  
				 )SELECT * FROM loc  
				  WHERE LNGKOD not in(SELECT LNGUSTKOD FROM TBLSBLOKASYON)  
    
		 OPEN TEMPALTLOK    
		 FETCH FIRST FROM TEMPALTLOK INTO @ALTLOKASYON  
		 WHILE  @@FETCH_STATUS = 0    
		BEGIN  
			print(@ALTLOKASYON)  
			SELECT TOP 1 @MALZEME=LNGMALZEMEKOD  
			FROM TBLSBSTOKDURUM S   
			WHERE LNGLOKASYONKOD=@ALTLOKASYON  
			--print('malzeme' + convert(nvarchar,@MALZEME))  
			IF @MALZEME IS NULL  
			BEGIN  
			print('malzeme null')  
			SET @MALZEME=''  
			--CLOSE TEMPALTLOK    
			--DEALLOCATE TEMPALTLOK    
			goto ContinueCursor  
			END  
				SET @MIKTAR=NULL  
				SET @BIRIM=NULL  
			SELECT TOP 1 @MIKTAR=CASE WHEN LK.DBLPALETMIKTAR =0 THEN LK.DBLMIKTAR ELSE LK.DBLPALETMIKTAR END,@BIRIM=LK.LNGBIRIM ,@PALETSAYI=LK.DBLPALETMIKTAR
			FROM TBLSBLOKASYONKAPASITE LK  
			LEFT OUTER JOIN TBLSBLOKASYONGRUPBAGLANTI LG ON LG.LNGLOKASYONKOD=LK.LNGLOKASYONBAGLANTIKODU AND LK.BYTLOKASYONBAGLANTITIPI=1  
			INNER JOIN TBLSBLOKASYON L ON (LK.LNGLOKASYONBAGLANTIKODU=L.LNGKOD AND LK.BYTLOKASYONBAGLANTITIPI=1) OR (LK.LNGKOD=LG.LNGLOKASYONKOD AND LK.BYTLOKASYONBAGLANTITIPI=0)  
			LEFT OUTER JOIN TBLSBURUNEKGRUPBAGLANTI UEB WITH(NOLOCK) ON LK.BYTMALZEMEBAGLANTITIPI = UEB.LNGSIRANO + 2 AND LK.LNGMALZEMEBAGLANTIKODU=UEB.LNGGRUPKOD AND UEB.LNGURUNKOD = @MALZEME  
			LEFT OUTER JOIN TBLURUN U WITH(NOLOCK) ON LK.BYTMALZEMEBAGLANTITIPI=1 AND U.LNGDETAYTIPI=LK.LNGMALZEMEBAGLANTIKODU    
			WHERE L.LNGKOD=@ALTLOKASYON AND ((LK.BYTMALZEMEBAGLANTITIPI=0 AND LK.LNGMALZEMEBAGLANTIKODU=@MALZEME) OR (LK.BYTMALZEMEBAGLANTITIPI > 0 AND UEB.LNGKOD IS NOT NULL) OR   
					(LK.BYTMALZEMEBAGLANTITIPI=99) OR (LK.BYTMALZEMEBAGLANTITIPI=1 AND U.LNGKOD=@MALZEME))  
			ORDER BY LK.BYTMALZEMEBAGLANTITIPI  
     
			Print('bulunan miktar'+ convert(nvarchar,@MIKTAR))  
    
			IF @MIKTAR IS NULL  AND @PALETSAYI IS NULL
			BEGIN  
				print('continue')  
				SET @ORAN=0  
				SET @TOPLAMSTOKMIKTAR=0  
				SET @BIRIM=0  
				SET @BIRIMTEXT=''  
				CLOSE TEMPALTLOK    
				DEALLOCATE TEMPALTLOK    
				goto kapasiteInsert  
			END  
			IF @PALETSAYI = 0
			BEGIN
				SELECT @BIRIMTEXT=TXTKOD FROM TBLSBBIRIM WHERE LNGKOD=@BIRIM  
     
				SELECT @STOKMIKTAR=SUM(S.DBLANAMIKTAR/UOB.DBLCARPAN*UOB.DBLBOLEN)  
				FROM TBLSBSTOKDURUM S  
				INNER JOIN TBLURUN U ON U.LNGKOD=S.LNGMALZEMEKOD  
				INNER JOIN TBLSBURUNOLCUBIRIM UOB ON UOB.LNGURUNKOD=U.LNGKOD AND UOB.LNGBIRIMKOD=@BIRIM  
				WHERE LNGLOKASYONKOD=@ALTLOKASYON  
			END
			ELSE
			SELECT @STOKMIKTAR= COUNT(DISTINCT P.LNGKOD)  
				FROM TBLSBSTOKDURUM S  
				INNER JOIN TBLSBPALET P On S.LNGPALETID=P.LNGKOD
				WHERE LNGLOKASYONKOD=@ALTLOKASYON  
			PRINT('Oran')
			PRINT(@STOKMIKTAR)
			PRINT(@MIKTAR  )
			SET @TOPLAMSTOKMIKTAR=@TOPLAMSTOKMIKTAR+ @STOKMIKTAR  
			IF @ORAN=0  
			BEGIN  
				SET @ORAN=@STOKMIKTAR*100/@MIKTAR  
			END  
			ELSE  
			BEGIN  
				SET @ORAN=(@ORAN+(@STOKMIKTAR*100/@MIKTAR))/2  
			END  
			PRINT(@ORAN)
			ContinueCursor:  
		 FETCH NEXT FROM TEMPALTLOK INTO @ALTLOKASYON  
		 END    
		 CLOSE TEMPALTLOK    
		 DEALLOCATE TEMPALTLOK    
		 kapasiteInsert:  
			INSERT INTO @KAPASITE(LOKASYON,LOKASYONTEXT,DBLORAN,DBLMIKTAR,LNGBIRIM,BIRIMTEXT) VALUES (@LOKASYON,@LOKASYONTEXT,@ORAN,@TOPLAMSTOKMIKTAR,@BIRIM,@BIRIMTEXT)  
			Print('atılan miktar'+ convert(nvarchar,@TOPLAMSTOKMIKTAR))  
		FETCH NEXT FROM TEMPLOK INTO @LOKASYON,@LOKASYONTEXT
		 END    
CLOSE TEMPLOK    
DEALLOCATE TEMPLOK    
  
SELECT * FROM @KAPASITE