CREATE PROCEDURE [dbo].[SSP_SBKLTSERBESTGECISKONTROL]
( 
	@DISTKOD INT,
	@CARIKOD INT,
	@LNGOPBASLIKKOD INT
)
AS
DECLARE @SERBESTGECIS AS TABLE(LNGOPERASYONDETAYKOD INT)
DECLARE @LNGOPERASYONDETAYKOD INT
DECLARE @URUNKOD INT
DECLARE @BATCHNO NVARCHAR(30)
DECLARE @DBLANAMIKTAR DECIMAL(28,8)
DECLARE @STATU INT
DECLARE @OKOPTIPI INT

DECLARE URUNBATCH CURSOR SCROLL FOR                            
	SELECT LNGKOD,LNGURUNKOD,TXTBATCHNO,SUM(DBLANAMIKTAR) DBLANAMIKTAR,LNGSTATU FROM TBLSBOPERASYONBELGEDETAY WHERE LNGBASLIKKOD=@LNGOPBASLIKKOD AND BYTGIRISCIKIS=1
	GROUP BY LNGKOD,LNGURUNKOD,TXTBATCHNO,LNGSTATU
OPEN URUNBATCH                            
FETCH FIRST FROM URUNBATCH INTO @LNGOPERASYONDETAYKOD,@URUNKOD,@BATCHNO,@DBLANAMIKTAR,@STATU
WHILE  @@FETCH_STATUS = 0                            
BEGIN 

DECLARE @SAYAC INT;

PRINT @LNGOPBASLIKKOD
PRINT @CARIKOD
PRINT @URUNKOD
PRINT @DISTKOD

SET @SAYAC=(SELECT COUNT(*)
	FROM TBLSBKLTSERBESTGECISTANIM FB WITH(NOLOCK)  
	WHERE   
	    ((FB.BYTCARIBAGLANTITIPI=99)   
	   OR (FB.BYTCARIBAGLANTITIPI=0 AND FB.LNGCARIBAGLANTIKODU=@CARIKOD)   
	   OR (FB.BYTCARIBAGLANTITIPI > 0 AND EXISTS(SELECT LNGKOD FROM TBLSBMUSTERIEKGRUPBAGLANTI MEB WITH(NOLOCK)   
		  WHERE FB.BYTCARIBAGLANTITIPI = MEB.LNGSIRANO + 2 AND FB.LNGCARIBAGLANTIKODU=MEB.LNGGRUPKOD AND MEB.LNGMUSTERIKOD = @CARIKOD)))  
	  AND ((FB.BYTMALZEMEBAGLANTITIPI=99)   
	   OR (FB.BYTMALZEMEBAGLANTITIPI=0 AND FB.LNGMALZEMEBAGLANTIKODU=@URUNKOD)   
	   OR (FB.BYTMALZEMEBAGLANTITIPI > 1 AND EXISTS(SELECT LNGKOD FROM TBLSBURUNEKGRUPBAGLANTI UEB WITH(NOLOCK)   
		  WHERE FB.BYTMALZEMEBAGLANTITIPI = UEB.LNGSIRANO + 2 AND FB.LNGMALZEMEBAGLANTIKODU=UEB.LNGGRUPKOD AND UEB.LNGURUNKOD = @URUNKOD))  
	   OR (FB.BYTMALZEMEBAGLANTITIPI=1 AND EXISTS(SELECT LNGKOD FROM TBLURUN U WITH(NOLOCK)   
		  WHERE FB.BYTMALZEMEBAGLANTITIPI=0 AND U.LNGDETAYTIPI=FB.LNGMALZEMEBAGLANTIKODU AND U.LNGKOD=@URUNKOD)))  
	  AND CASE WHEN LNGDISTKOD IS NULL THEN @DISTKOD ELSE LNGDISTKOD END = @DISTKOD)                      
	PRINT @SAYAC
	 IF(@SAYAC>0)
	 BEGIN
	 PRINT 'A'
	 INSERT INTO @SERBESTGECIS(LNGOPERASYONDETAYKOD)
	 VALUES(@LNGOPERASYONDETAYKOD)
	 END

	FETCH NEXT FROM URUNBATCH INTO @LNGOPERASYONDETAYKOD,@URUNKOD,@BATCHNO,@DBLANAMIKTAR,@STATU
END                                                        
CLOSE URUNBATCH                            
DEALLOCATE URUNBATCH  

SELECT @OKOPTIPI=LNGOKOPERASYONTIPKOD from TBLSBKLTPARAMETRE WHERE LNGDISTKOD=@DISTKOD

SELECT @OKOPTIPI AS OPERASYONTIPKOD,O.LNGURUNKOD,O.DBLANAMIKTAR AS DBLMIKTAR,O.LNGANAOLCUBIRIMKOD AS LNGOLCUBIRIMKOD,O.LNGLOKASYONKOD AS LNGKAYNAKLOKASYONKOD,
	NULL AS LNGHEDEFLOKASYONKOD,O.TXTBATCHNO,O.TXTSERINO,O.TXTPO,O.TXTPOLINE,O.LNGSTATU AS LNGKAYNAKSTATU,NULL AS LNGHEDEFSTATU,O.DBLANAMIKTAR AS DBLISLEMMIKTAR,
	O.LNGANAOLCUBIRIMKOD AS LNGISLEMBIRIMKOD,DBLNETAGIRLIK,DBLBRUTAGIRLIK,LNGAGIRLIKOLCUBIRIMKOD,LNGKOD AS LNGREFDETAYNO,LNGOPERASYONNEDENKOD,TXTPALETNO AS TXTKAYNAKPALETNO,
	TXTPALETNO AS TXTHEDEFPALETNO,TRHSONKULLANMATARIHI,TRHURETIMTARIHI,LNGMUSTERIKOD AS LNGKAYNAKCARIKOD,LNGMUSTERIKOD AS LNGHEDEFCARIKOD,  
	LNGREZERVEBELGEKOD AS LNGHEDEFREZERVEBELGEKOD,LNGREZERVEBELGEKOD AS LNGKAYNAKREZERVEBELGEKOD,LNGREZERVEBELGETIPKOD AS LNGKAYNAKREZERVEBELGETIPKOD,LNGREZERVEBELGETIPKOD AS LNGHEDEFREZERVEBELGETIPKOD
FROM TBLSBOPERASYONBELGEDETAY O
	INNER JOIN @SERBESTGECIS F ON O.LNGKOD=F.LNGOPERASYONDETAYKOD
WHERE O.LNGBASLIKKOD=@LNGOPBASLIKKOD AND O.BYTGIRISCIKIS=1
