CREATE PROCEDURE [dbo].[SSP_SBCKFIFOLIFO]              
(
 @LNGOPERASYONTIPI INT,                 
 @LNGMALZEME INT,              
 @LNGMUSTERIKOD VARCHAR(4000),              
 @LNGREZERVEMUSTERIKOD INT,              
 @LNGLOKASYON INT,
 @BYTLOKASYONTIPI INT,              
 @LNGSTATU INT,              
 @TXTBATCHNO NVARCHAR(50),              
 @TXTSERINO NVARCHAR(50),              
 @TXTPO NVARCHAR(50),              
 @TXTPOLINE NVARCHAR(50),              
 @LNGPALETID INT,              
 @TXTKONTROLSAHASI NVARCHAR(50),              
 @DTKONTROLSAHASIDEGERI DATETIME,              
 @LNGTOLERANS INT,              
 @LNGYUZDEDEGER INT,              
 @LNGRAFOMRUSURESI INT,              
 @FIFOEZILSIN NVARCHAR(1),              
 @BYTKONTROLTIPI SMALLINT ,
 @LNGBELGEBASLIKKOD INT              
)              
AS    
 --BEGIN TRANSACTION
DECLARE @SQL NVARCHAR(4000)    
DECLARE @SQL2 NVARCHAR(4000)
DECLARE @OPERATOR NVARCHAR(1)   
DECLARE @WHERE NVARCHAR(4000)
DECLARE @SQLSAYIMFARK NVARCHAR(4000)=''
DECLARE @RESULT NVARCHAR(4000)
DECLARE @BYTONAYLISAYIMKONTROLUYAPILSIN TINYINT
DECLARE @KONTROLSAHASIKRITER NVARCHAR(500)
DECLARE @GUN INT



--Sayimda Onayli Sayim Kontrolü Yapilacak mi ?
SELECT @BYTONAYLISAYIMKONTROLUYAPILSIN=BYTONAYLISAYIMKONTROLU FROM TBLSBOPERASYONTIPI WHERE LNGKOD=@LNGOPERASYONTIPI

PRINT 'ONAYLISAYIMPARAMETRESI = '+Convert(nvarchar,@BYTONAYLISAYIMKONTROLUYAPILSIN)

IF @BYTKONTROLTIPI=1 SET @OPERATOR='<' ELSE IF @BYTKONTROLTIPI=2 SET @OPERATOR='>'              
IF @BYTKONTROLTIPI=5 SET @OPERATOR='<'         
PRINT (@OPERATOR)              
CREATE TABLE #TBL (LOKASYON INT PRIMARY KEY)     

CREATE TABLE #STOKLAR(LNGLOKASYONKOD INT,LNGPALETID INT, TXTBATCHNO NVARCHAR(50),TXTSERINO NVARCHAR(50),TXTPO NVARCHAR(50),TXTPOLINE NVARCHAR(50),LNGKOD INT,LNGMALZEMEKOD INT,LNGSTATUKOD INT,LNGMUSTERIKOD INT,DBLANAMIKTAR DECIMAL(28,8),DBLREZERVEMIKTAR DECIMAL(28,8),          
 LNGANAOLCUBIRIMI INT,DBLNETAGIRLIK DECIMAL(28,8),DBLBRUTAGIRLIK DECIMAL(28,8),LNGAGIRLIKOLCUBIRIMI INT,TRHSONKULLANMATARIHI DATETIME,TRHURETIMTARIHI DATETIME,LNGREZERVEBELGEKOD INT,LNGREZERVEBELGETIPKOD INT,TRHILKISLEMTARIHI DATETIME,TRHSONISLEMTARIHI DATETIME)

 IF @LNGTOLERANS <24
 BEGIN
 SET @GUN=0
 END
 ELSE IF @LNGTOLERANS >=24 AND @LNGTOLERANS <48
 BEGIN
 SET @GUN=1
 END
 ELSE IF @LNGTOLERANS>=48 AND @LNGTOLERANS <72
 BEGIN
 SET @GUN=2
 END
 ELSE IF @LNGTOLERANS>=72 AND @LNGTOLERANS <96
 BEGIN
 SET @GUN=3
 END
 ELSE
 BEGIN
 SET @GUN=0
 END

  IF @TXTKONTROLSAHASI='TRHSONKULLANMATARIHI' AND CONVERT(DATE,@DTKONTROLSAHASIDEGERI) < GETDATE()
  SET @DTKONTROLSAHASIDEGERI =CONVERT(DATETIME, CONVERT(NVARCHAR(10), CONVERT(DATE,GETDATE())) + ' 00:00:00')

  PRINT(@DTKONTROLSAHASIDEGERI)

SET @KONTROLSAHASIKRITER = 'AND dateadd(dd,' +CONVERT(NVARCHAR(10),@GUN)+ ',' + 'SD.'+@TXTKONTROLSAHASI + ') '             
     + @OPERATOR + ' ''' + CONVERT(NVARCHAR(100),@DTKONTROLSAHASIDEGERI) + ''''


IF @BYTLOKASYONTIPI=1  --Lokasyon kodu     
BEGIN
SET @SQL ='            
  WITH LOC(LNGKOD,LNGUSTKOD) AS (              
   SELECT LNGKOD,LNGUSTKOD FROM TBLSBLOKASYON WHERE LNGKOD = ' + CONVERT(NVARCHAR(50),@LNGLOKASYON) + ' UNION ALL              
   SELECT E.LNGKOD,E.LNGUSTKOD             
   FROM TBLSBLOKASYON AS e              
   INNER JOIN LOC AS d ON e.LNGUSTKOD = D.LNGKOD )              
     INSERT INTO #TBL SELECT DISTINCT LNGKOD AS LOKASYON FROM LOC  
	
  SELECT SD.LNGLOKASYONKOD ,SD.LNGPALETID, SD.TXTBATCHNO,SD.TXTSERINO,SD.TXTPO,SD.TXTPOLINE,SD.LNGKOD,SD.LNGMALZEMEKOD,SD.LNGSTATUKOD,SD.LNGMUSTERIKOD,SD.DBLANAMIKTAR,SD.DBLREZERVEMIKTAR,          
SD.LNGANAOLCUBIRIMI,SD.DBLNETAGIRLIK,SD.DBLBRUTAGIRLIK,SD.LNGAGIRLIKOLCUBIRIMI,SD.TRHSONKULLANMATARIHI,SD.TRHURETIMTARIHI,
SD.LNGREZERVEBELGEKOD,SD.LNGREZERVEBELGETIPKOD,SD.TRHILKISLEMTARIHI,SD.TRHSONISLEMTARIHI 
 FROM TBLSBSTOKDURUM SD WITH(NOLOCK)
 LEFT JOIN TBLSBPALET PAL ON PAL.LNGKOD=SD.LNGPALETID
 '
 
 SET @WHERE=' WHERE EXISTS(SELECT T.LOKASYON FROM #TBL T WHERE SD.LNGLOKASYONKOD=T.LOKASYON) 
     AND LNGMALZEMEKOD=' + CONVERT(NVARCHAR(50),@LNGMALZEME) + ' AND LNGSTATUKOD=' + CONVERT(NVARCHAR(50),@LNGSTATU) + '           
     AND DBLANAMIKTAR-DBLREZERVEMIKTAR>0  '     
	 
SET @SQL2 ='            
  INSERT INTO #STOKLAR
  SELECT LNGLOKASYONKOD ,LNGPALETID, TXTBATCHNO,TXTSERINO,TXTPO,TXTPOLINE,LNGKOD,LNGMALZEMEKOD,LNGSTATUKOD,LNGMUSTERIKOD,DBLANAMIKTAR,DBLREZERVEMIKTAR,          
 LNGANAOLCUBIRIMI,DBLNETAGIRLIK,DBLBRUTAGIRLIK,LNGAGIRLIKOLCUBIRIMI,TRHSONKULLANMATARIHI,TRHURETIMTARIHI,LNGREZERVEBELGEKOD,LNGREZERVEBELGETIPKOD,TRHILKISLEMTARIHI,TRHSONISLEMTARIHI 
 FROM TBLSBSTOKDURUM SD WITH(NOLOCK)            
  WHERE DBLANAMIKTAR-DBLREZERVEMIKTAR>0  '  
END
ELSE
BEGIN			--Lokasyon grubu 
SET @SQL ='            
  WITH LOC(LNGKOD,LNGUSTKOD) AS (              
   SELECT LNGKOD,LNGUSTKOD FROM TBLSBLOKASYON WHERE EXISTS(SELECT LB.LNGLOKASYONKOD FROM TBLSBLOKASYONGRUPBAGLANTI LB WHERE TBLSBLOKASYON.LNGKOD=LB.LNGLOKASYONKOD AND LNGGRUPKOD=' + CONVERT(NVARCHAR(50),@LNGLOKASYON) + ' )   UNION ALL              
   SELECT E.LNGKOD,E.LNGUSTKOD             
   FROM TBLSBLOKASYON AS e              
   INNER JOIN LOC AS d ON e.LNGUSTKOD = D.LNGKOD )              
     INSERT INTO #TBL SELECT DISTINCT LNGKOD AS LOKASYON FROM LOC   
    SELECT SD.LNGLOKASYONKOD ,SD.LNGPALETID, SD.TXTBATCHNO,SD.TXTSERINO,SD.TXTPO,SD.TXTPOLINE,SD.LNGKOD,SD.LNGMALZEMEKOD,SD.LNGSTATUKOD,SD.LNGMUSTERIKOD,SD.DBLANAMIKTAR,SD.DBLREZERVEMIKTAR,          
SD.LNGANAOLCUBIRIMI,SD.DBLNETAGIRLIK,SD.DBLBRUTAGIRLIK,SD.LNGAGIRLIKOLCUBIRIMI,SD.TRHSONKULLANMATARIHI,SD.TRHURETIMTARIHI,
SD.LNGREZERVEBELGEKOD,SD.LNGREZERVEBELGETIPKOD,SD.TRHILKISLEMTARIHI,SD.TRHSONISLEMTARIHI 
 FROM TBLSBSTOKDURUM SD WITH(NOLOCK) 
 LEFT JOIN TBLSBPALET PAL ON PAL.LNGKOD=SD.LNGPALETID
 '
 
 SET @WHERE='            WHERE EXISTS(SELECT T.LOKASYON FROM #TBL T WHERE SD.LNGLOKASYONKOD=T.LOKASYON             
     AND LNGMALZEMEKOD=' + CONVERT(NVARCHAR(50),@LNGMALZEME) + ' AND LNGSTATUKOD=' + CONVERT(NVARCHAR(50),@LNGSTATU) + ')            
     AND DBLANAMIKTAR-DBLREZERVEMIKTAR>0  '                   

	SET @SQL2 ='            
 INSERT INTO #STOKLAR
    SELECT LNGLOKASYONKOD ,LNGPALETID, TXTBATCHNO,TXTSERINO,TXTPO,TXTPOLINE,LNGKOD,LNGMALZEMEKOD,LNGSTATUKOD,LNGMUSTERIKOD,DBLANAMIKTAR,DBLREZERVEMIKTAR,          
 LNGANAOLCUBIRIMI,DBLNETAGIRLIK,DBLBRUTAGIRLIK,LNGAGIRLIKOLCUBIRIMI,TRHSONKULLANMATARIHI,TRHURETIMTARIHI,LNGREZERVEBELGEKOD,LNGREZERVEBELGETIPKOD,TRHILKISLEMTARIHI,TRHSONISLEMTARIHI 
 FROM TBLSBSTOKDURUM SD WITH(NOLOCK)            
  WHERE DBLANAMIKTAR-DBLREZERVEMIKTAR>0  '   
END


IF @BYTONAYLISAYIMKONTROLUYAPILSIN=1
 BEGIN
 SET @SQLSAYIMFARK=' LEFT JOIN (SELECT FARK.DBLSAYILANMIKTAR,FARK.TXTPALETNO,FARK.TXTBATCHNO,FARK.TXTSERINO,FARK.TXTPO,FARK.TXTPOLINE,FARK.BYTONAYDURUM,FARK.DBLFARK,FARK.TXTSAYIMGRUPNO 
 FROM TBLSBSAYIMFARKONAY FARK INNER JOIN 
 (SELECT MAX(BAS.LNGKOD) LNGBASLIKKOD,BAS.TXTSAYIMGRUPNO,DET.TXTPALETNO,DET.TXTSERINO,DET.TXTPO,DET.TXTPOLINE,DET.TXTBATCHNO FROM TBLSBSAYIMBELGEDETAY DET INNER JOIN 
 TBLSBSAYIMBELGEBASLIK BAS ON DET.LNGBASLIKKOD=BAS.LNGKOD
 GROUP BY BAS.LNGKOD,BAS.TXTSAYIMGRUPNO,DET.TXTPALETNO,DET.TXTSERINO,DET.TXTPO,DET.TXTPOLINE,DET.TXTBATCHNO  
 ) AS TBL2 ON 1=1 AND 
 ISNULL(FARK.TXTPALETNO COLLATE Turkish_CI_AS,'''')=ISNULL(TBL2.TXTPALETNO COLLATE Turkish_CI_AS,'''') 
 AND ISNULL(FARK.TXTBATCHNO COLLATE Turkish_CI_AS,'''')=ISNULL(TBL2.TXTBATCHNO COLLATE Turkish_CI_AS,'''') 
 AND ISNULL(FARK.TXTSERINO COLLATE Turkish_CI_AS,'''')=ISNULL(TBL2.TXTSERINO COLLATE Turkish_CI_AS,'''') 
 AND ISNULL(FARK.TXTPO COLLATE Turkish_CI_AS,'''')=ISNULL(TBL2.TXTPO COLLATE Turkish_CI_AS,'''') 
 AND ISNULL(FARK.TXTPOLINE COLLATE Turkish_CI_AS,'''')=ISNULL(TBL2.TXTPOLINE COLLATE Turkish_CI_AS,'''')
 WHERE FARK.TXTSAYIMGRUPNO=TBL2.TXTSAYIMGRUPNO AND FARK.TXTPALETNO= ISNULL(TBL2.TXTPALETNO COLLATE Turkish_CI_AS,'''')
 ) 
 AS SAY ON  ISNULL(PAL.TXTPALETNO COLLATE Turkish_CI_AS,'''')=ISNULL(PAL.TXTPALETNO COLLATE Turkish_CI_AS,'''') 
 AND ISNULL(SD.TXTBATCHNO COLLATE Turkish_CI_AS,'''')=ISNULL(SAY.TXTBATCHNO COLLATE Turkish_CI_AS,'''') 
 AND ISNULL(SD.TXTSERINO COLLATE Turkish_CI_AS,'''')=ISNULL(SAY.TXTSERINO COLLATE Turkish_CI_AS,'''') 
 AND ISNULL(SD.TXTPO COLLATE Turkish_CI_AS,'''')=ISNULL(SAY.TXTPO COLLATE Turkish_CI_AS,'''') 
 AND ISNULL(SD.TXTPOLINE COLLATE Turkish_CI_AS,'''')=ISNULL(SAY.TXTPOLINE COLLATE Turkish_CI_AS,'''')'
SET @WHERE+=' AND (((SAY.BYTONAYDURUM<>0 AND SAY.BYTONAYDURUM<>3 AND SAY.BYTONAYDURUM IS NOT NULL) OR (SAY.DBLFARK=0 OR SAY.DBLSAYILANMIKTAR=-1) ) OR SAY.DBLFARK IS NULL)   '
 END

PRINT('@FIFOEZILSIN') 
PRINT(@FIFOEZILSIN)            
IF @FIFOEZILSIN ='E'               
BEGIN              
 IF @LNGMUSTERIKOD IS NOT NULL               
 BEGIN              
   IF @LNGREZERVEMUSTERIKOD IS NOT NULL AND @LNGREZERVEMUSTERIKOD<>0 
   BEGIN
   SET @WHERE+=' AND 1=2 ' 
   SET @SQL2+=' AND 1=2 '
   PRINT('@FIFOEZILSIN where') 
   END
   ELSE SET @wHERE+=' AND LNGMUSTERIKOD IN (' + CONVERT(NVARCHAR(50),@LNGMUSTERIKOD) +')'            
 END              
 ELSE IF @LNGMUSTERIKOD IS NULL 
 BEGIN
 SET @WHERE+= ' AND LNGMUSTERIKOD IS NULL '  
 SET @SQL2+= ' AND LNGMUSTERIKOD IS NULL ' 
 END
END              
Print(@LNGRAFOMRUSURESI)            
Print(@TXTKONTROLSAHASI)            
Print(@LNGYUZDEDEGER)            
IF @LNGYUZDEDEGER>0 AND @LNGRAFOMRUSURESI>0 -- Raf Ömrü Kontrolü                
BEGIN                
  IF @TXTKONTROLSAHASI='TRHSONKULLANMATARIHI'  
  BEGIN
  SET @WHERE+= ' AND CONVERT(DECIMAL,(DateDiff(day,dateadd(dd,-' + CONVERT(NVARCHAR(50),@LNGRAFOMRUSURESI) + ',SD.' + @TXTKONTROLSAHASI + '),GETDATE())))/' + CONVERT(NVARCHAR(50),@LNGRAFOMRUSURESI) + '*100 <= ' + CONVERT(NVARCHAR(50),@LNGYUZDEDEGER)           
  SET @SQL2+= ' AND CONVERT(DECIMAL,(DateDiff(day,dateadd(dd,-' + CONVERT(NVARCHAR(50),@LNGRAFOMRUSURESI) + ',SD.' + @TXTKONTROLSAHASI + '),GETDATE())))/' + CONVERT(NVARCHAR(50),@LNGRAFOMRUSURESI) + '*100 <= ' + CONVERT(NVARCHAR(50),@LNGYUZDEDEGER)           
  END
    
     
  ELSE IF @TXTKONTROLSAHASI='TRHURETIMTARIHI'
  BEGIN
   SET @WHERE+= ' AND CONVERT(DECIMAL,(DateDiff(day,SD.' + @TXTKONTROLSAHASI + ',GETDATE())))/' + CONVERT(NVARCHAR(50),@LNGRAFOMRUSURESI) + '*100 <= ' + CONVERT(NVARCHAR(50),@LNGYUZDEDEGER) 
   SET @SQL2+= ' AND CONVERT(DECIMAL,(DateDiff(day,SD.' + @TXTKONTROLSAHASI + ',GETDATE())))/' + CONVERT(NVARCHAR(50),@LNGRAFOMRUSURESI) + '*100 <= ' + CONVERT(NVARCHAR(50),@LNGYUZDEDEGER) 

  END
END

--SET @SQL=@SQL + @KONTROLSAHASIKRITER  
IF ISNULL(@LNGBELGEBASLIKKOD,0) > 0 
  
  
  BEGIN
	   DECLARE @TXTBELGEKAYNAKBATCH NVARCHAR(50)           
	   DECLARE @TXTBELGEHEDEFBATCH NVARCHAR(50)           
	   DECLARE @LNGBELGEPALETID INT
	   DECLARE @TXTBELGESERINO NVARCHAR(50)
	   DECLARE @TXTBELGEPO NVARCHAR(50)             
	   DECLARE @TXTBELGEPOLINE NVARCHAR(50)

	   SELECT top 1 @TXTBELGEKAYNAKBATCH = D.TXTKAYNAKBATCHNO, @TXTBELGEHEDEFBATCH = D.TXTHEDEFBATCHNO, @LNGBELGEPALETID = P.LNGKOD, @TXTBELGESERINO = D.TXTSERINO, 
	          @TXTBELGEPO = D.TXTPO, @TXTBELGEPOLINE = D.TXTPOLINE
	   FROM TBLSBBELGEDETAY D (NOLOCK)
	   LEFT JOIN TBLSBPALET P (NOLOCK) ON P.TXTPALETNO = D.TXTPALETNO
	   INNER JOIN TBLSBSTOKDURUM S (NOLOCK) ON S.LNGMALZEMEKOD=D.LNGMALZEMEKOD 
	   AND CASE WHEN D.TXTHEDEFBATCHNO <>'' AND S.TXTBATCHNO=D.TXTHEDEFBATCHNO THEN 1 WHEN D.TXTHEDEFBATCHNO ='' THEN 1 ELSE 0 END = 1
	   AND CASE WHEN D.TXTSERINO <>'' AND S.TXTSERINO=D.TXTSERINO THEN 1 WHEN D.TXTSERINO ='' THEN 1 ELSE 0 END = 1
	   AND CASE WHEN D.TXTPO <>'' AND S.TXTPO=D.TXTPO THEN 1 WHEN D.TXTPO ='' THEN 1 ELSE 0 END = 1
	   AND CASE WHEN D.TXTPOLINE <>'' AND S.TXTPOLINE=D.TXTPO THEN 1 WHEN D.TXTPOLINE ='' THEN 1 ELSE 0 END = 1
	   AND CASE WHEN D.TXTPALETNO <>'' AND P.TXTPALETNO=D.TXTPALETNO THEN 1 WHEN D.TXTPALETNO ='' THEN 1 ELSE 0 END = 1
	   WHERE LNGBASLIKKOD = @LNGBELGEBASLIKKOD AND D.LNGMALZEMEKOD = @LNGMALZEME	  
	   	   
	   IF ISNULL(@TXTBELGEHEDEFBATCH,'') <> '' 
		   BEGIN
		   SET @TXTBATCHNO = @TXTBELGEHEDEFBATCH
		   SET @SQL+= ' AND TXTBATCHNO=''' + @TXTBELGEHEDEFBATCH + ''''   
		   END
	   IF ISNULL(@TXTBELGEKAYNAKBATCH,'') <> '' 
		   BEGIN
		   SET @TXTBATCHNO = @TXTBELGEKAYNAKBATCH
		   SET @SQL+= ' AND TXTBATCHNO=''' + @TXTBELGEKAYNAKBATCH + ''''  
		   END
	   IF ISNULL(@LNGBELGEPALETID,0) > 0 
		   BEGIN
		   SET @LNGPALETID = @LNGBELGEPALETID
		   SET @SQL+=  ' AND LNGPALETID=' + CONVERT(NVARCHAR,@LNGBELGEPALETID)    
		   END
	   IF ISNULL(@TXTBELGESERINO,'') <> '' 
		   BEGIN
		   SET @TXTSERINO = @TXTBELGESERINO
		   SET @SQL+=' AND TXTSERINO=''' + @TXTBELGESERINO + '''' 
		   END
	   IF ISNULL(@TXTBELGEPO,'') <> '' 
		   BEGIN
		   SET @TXTPO = @TXTBELGEPO
		   SET @SQL+=  ' AND TXTPO=''' + @TXTBELGEPO + ''''   
		   END
	   IF ISNULL(@TXTBELGEPOLINE,'') <> '' 
		   BEGIN
		   SET @TXTPOLINE = @TXTBELGEPOLINE	    
		   SET @SQL+=   ' AND @TXTPOLINE=''' + @TXTBELGEPOLINE + ''''   	
		   END
  END  


IF @TXTBATCHNO<>'' AND @TXTBATCHNO IS NOT NULL
BEGIN
SET @SQL2+= ' AND TXTBATCHNO=''' + @TXTBATCHNO + '''' 
END

IF @TXTSERINO<>'' AND @TXTSERINO IS NOT NULL
BEGIN
SET @SQL2+=' AND TXTSERINO=''' + @TXTSERINO + '''' 
END

IF @TXTPO<>'' AND @TXTPO IS NOT NULL
BEGIN
SET @SQL2+=  ' AND TXTPO=''' + @TXTPO + '''' 
END

IF @TXTPOLINE<>'' AND @TXTPOLINE IS NOT NULL
BEGIN
SET @SQL2+=   ' AND @TXTPOLINE=''' + @TXTPOLINE + '''' 
END

IF @LNGPALETID<>'' AND @LNGPALETID IS NOT NULL
BEGIN
SET @SQL2+=  ' AND LNGPALETID=' + CONVERT(NVARCHAR,@LNGPALETID)  
END

SET @RESULT = @SQL+@SQLSAYIMFARK+@WHERE +@KONTROLSAHASIKRITER 

IF @BYTKONTROLTIPI=1  
SET @RESULT+=' ORDER BY ' + 'SD.'+@TXTKONTROLSAHASI + ' ASC '  
IF @BYTKONTROLTIPI=2  
SET @RESULT+=' ORDER BY ' + 'SD.'+@TXTKONTROLSAHASI + ' DESC '  

PRINT 'SON'
PRINT @RESULT

PRINT (@SQL2)              
EXEC (@SQL2)

IF  @FIFOEZILSIN <> 'E' and NOT EXISTS(SELECT * FROM #STOKLAR) 
BEGIN 
RAISERROR('Fifoya uygun degil!',16,1)
--rollback transaction
END
ELSE

PRINT (@RESULT)  
EXEC (@RESULT)

