CREATE  PROCEDURE [dbo].[SSP_SBDETAYTOLERANS]      
(      
 @BELGENO NVARCHAR(20),  
 @DISTKOD INT,
 @LNGMALZEMEKOD  INT,
 @LNGBELGEDETAYKOD INT
)      
AS      
SELECT BD.LNGKOD, BD.TRHTESLIMTARIHI, 
  --(SELECT OT.TXTKOD FROM TBLSBOPERASYONTIPI OT WITH(NOLOCK) WHERE OT.LNGKOD=BB.LNGOPERASYONTIPKOD) TXTBELGETIPI, 
  U.LNGKOD AS LNGMALZEMEKOD ,U.TXTKOD AS TXTMALZEMEKOD,U.TXTAD AS TXTAD,
  ISNULL(STKAYNAK.TXTTANIMI,'') AS TXTKAYNAKSTATUTANIM, ISNULL(STKAYNAK.TXTKOD,'') AS TXTKAYNAKSTATUKOD  , ISNULL(STKAYNAK.LNGKOD,0) AS LNGKAYNAKSTATUKOD,  
  ISNULL(STHEDEF.TXTTANIMI,'') AS  TXTHEDEFSTATUTANIM, ISNULL(STHEDEF.TXTKOD,'') AS TXTHEDEFSTATUKOD  , ISNULL(STHEDEF.LNGKOD,0) AS LNGHEDEFSTATUKOD,
  --UG.TXTKOD AS TXTURUNGRUPKOD,/*U.TXTURUNGRUPKOD, UBB.TXTBARKOD,*/
  BD.DBLISLEMMIKTARI as DBLANAMIKTAR, /* BD.DBLANAMIKTAR,*/    
  (SELECT TXTKOD     
  FROM TBLSBBIRIM B WITH(NOLOCK)     
  WHERE B.LNGKOD=BD.LNGISLEMOLCUBIRIMKOD) TXTISLEMOLCUBIRIMKOD     
  --,CONVERT(DECIMAL(28,8),(CONVERT(DECIMAL(16,8),BD.DBLTOPLANANMIKTAR)*CONVERT(DECIMAL(16,8),UOB.DBLBOLEN)/CONVERT(DECIMAL(16,8),UOB.DBLCARPAN))) as DBLTOPLANANMIKTAR,    
  --(SELECT TXTKOD    FROM TBLSBBIRIM B WITH(NOLOCK) WHERE B.LNGKOD=BD.LNGANAOLCUBIRIMKOD) TXTANAOLCUBIRIMKOD,    
  --BD.TXTKAYNAKBATCHNO,BD.TXTHEDEFBATCHNO, BD.DBLNETAGIRLIK, 
  --BD.LNGDETAYKOD,    
  --(SELECT TXTKOD FROM TBLURUN U WITH(NOLOCK) WHERE U.LNGKOD=BD.LNGANAURUNKOD) TXTANAURUNKOD,    
  --(SELECT TXTKOD FROM TBLSBBIRIM B WITH(NOLOCK) WHERE B.LNGKOD=BD.LNGAGIRLIKOLCUBIRIMKOD) TXTAGIRLIKOLCUBIRIMKOD,    
  --BD.LNGMUADILBAGLANTI,U.TXTREFERANS as MalzemeEntegrasyonKodu,
 -- U.TXTAD  
  --round(BD.DBLISLEMMIKTARI,4) - round(BD.DBLTOPLANANMIKTAR*UOB.DBLBOLEN/UOB.DBLCARPAN,4) AS DBLKALAN     
  
FROM TBLSBBELGEBASLIK BB WITH(NOLOCK)     
 INNER JOIN TBLSBBELGEDETAY BD WITH(NOLOCK) ON BB.LNGKOD=BD.LNGBASLIKKOD      
 INNER JOIN TBLURUN U WITH(NOLOCK) ON BD.LNGMALZEMEKOD=U.LNGKOD      
 LEFT OUTER JOIN TBLSBURUNOLCUBIRIM UOB WITH(NOLOCK) ON BD.LNGMALZEMEKOD =UOB.LNGURUNKOD AND BD.LNGISLEMOLCUBIRIMKOD = UOB.LNGBIRIMKOD      
 LEFT OUTER JOIN TBLSBURUNBIRIMBARKOD UBB WITH(NOLOCK) ON UBB.LNGURUNBIRIMKOD=UOB.LNGBIRIMKOD      
 LEFT OUTER JOIN TBLSBURUNEKGRUPBAGLANTI UEB WITH(NOLOCK) ON UEB.LNGURUNKOD=U.LNGKOD AND UEB.LNGSIRANO=0    
 LEFT OUTER JOIN TBLSBGRUP UG WITH(NOLOCK) ON UG.LNGKOD=UEB.LNGGRUPKOD  
 LEFT OUTER JOIN TBLSBSTATU STHEDEF WITH(NOLOCK) ON STHEDEF.LNGKOD=BD.LNGHEDEFSTATU 
 LEFT OUTER JOIN TBLSBSTATU STKAYNAK WITH(NOLOCK) ON STKAYNAK.LNGKOD=BD.LNGKAYNAKSTATU 
WHERE (BB.TXTKOD =@BELGENO)   AND BB.LNGDISTKOD=@DISTKOD  AND TRHTESLIMTARIHI IS NOT NULL AND LNGMALZEMEKOD=@LNGMALZEMEKOD 
AND CASE WHEN  @LNGBELGEDETAYKOD <>0 THEN BD.LNGKOD  ELSE 0 END=@LNGBELGEDETAYKOD
ORDER BY CASE WHEN BD.DBLANAMIKTAR-BD.DBLTOPLANANMIKTAR >0 THEN 0 ELSE 1 END ,UG.TXTKOD ASC

