CREATE PROCEDURE [dbo].[SSP_SBHAZIRLANANMIKTAR]  
(  
       @TXTMALZEMEKODLARI VARCHAR(MAX),  
       @BELGENOLARI VARCHAR(MAX)  
)  
AS  
DECLARE @SQL VARCHAR(MAX)  
DECLARE @DIST INT  
DECLARE @SQL2 VARCHAR(MAX)=''  

SELECT @DIST = LNGDISTKOD FROM TBLSBBELGEBASLIK WHERE LNGKOD = (SELECT TOP 1 value FROM FNC_STRINGSPLIT(@BELGENOLARI,',')) 
 

IF (select COUNT(TXTKOD) from TBLSBPARAMETRE where TXTKOD = 'HazirlananMiktarOperasyonTipiLokasyonaGoreHesapla') > 0
BEGIN
SELECT LNGOPERASYONTIPKOD INTO #TBLOPERASYONTIPLERI FROM TBLSBOPERASYONTIPILOKASYON WHERE LNGKAYNAKLOKASYONBAGLANTIKODU 
IN
(
select LNGKAYNAKLOKASYONBAGLANTIKODU from TBLSBOPERASYONTIPILOKASYON OPL 
INNER JOIN TBLSBBELGEBASLIK BB ON BB.LNGOPERASYONTIPKOD = OPL.LNGOPERASYONTIPKOD 
WHERE BB.LNGKOD IN (SELECT value FROM FNC_STRINGSPLIT(@BELGENOLARI,','))
)
set @SQL2 =' AND BB.LNGOPERASYONTIPKOD IN (SELECT LNGOPERASYONTIPKOD FROM #TBLOPERASYONTIPLERI)'
print @SQL2
END

SET @SQL= 'SELECT ISNULL(SUM(DBLHAZIRLANANMIKTAR),0) AS DBLHAZIRLANANMIKTAR FROM TBLSBBELGEDETAY BD WITH(NOLOCK)  
INNER JOIN TBLSBBELGEBASLIK BB WITH(NOLOCK) ON BB.LNGKOD = BD.LNGBASLIKKOD  
WHERE  BB.TRHONAYTARIHI IS NULL AND BB.LNGKOD NOT IN ('+@BELGENOLARI+') '+@SQL2+ 
' AND EXISTS (SELECT 1 FROM VIEWSBYUKLEMEEMRIBELGEBASLIK V WHERE ISNULL(V.LNGYUKLEMEKOD ,0) > 0 AND V.LNGKOD = BB.LNGKOD)
AND BB.LNGDISTKOD ='+CONVERT(NVARCHAR,@DIST)+'   
AND BD.LNGMALZEMEKOD IN ('+@TXTMALZEMEKODLARI+')'  
  
PRINT(@SQL)  
EXEC(@SQL)  