CREATE PROCEDURE [dbo].[SSP_SBISEMRIBELGEHAZIRLA]
(    
 @LNGOPERASYONTIPKOD INT,    
 @TXTBELGEKOD NVARCHAR(MAX)    
)    
AS    
   
   
IF EXISTS(    
 SELECT * FROM TBLSBBELGEBASLIK B    
 INNER JOIN (SELECT VALUE FROM FNC_STRINGSPLIT(@TXTBELGEKOD,',')) T ON T.VALUE = B.LNGKOD    
 WHERE BYTONAYASAMA <> 0    
)    
BEGIN    
 RAISERROR('Seçilen belgeler için daha önce is emri olusturulmustur.',16,1)    
 RETURN    
END    
   
    
    
IF EXISTS(    
 SELECT * FROM (SELECT VALUE FROM FNC_STRINGSPLIT(@TXTBELGEKOD,',')) T    
 LEFT JOIN _nakliyeci_bilgileri N ON T.value =N.belge_no    
 WHERE N.belge_no IS NULL    
)    
BEGIN    
 RAISERROR('Seçilen belgeler için nakliyeci bilgileri bulunamadi.',16,1)    
 RETURN    
END    
    
DECLARE @SQL NVARCHAR(MAX)    
--DECLARE @TXTBELGEKOD NVARCHAR(MAX) = '451924,451925,451926,451927'    
    
    
    
CREATE TABLE #BUTUNDETAYLAR(LNGKOD INT IDENTITY(1,1),LNGMALZEMEKOD INT, DBLANAMIKTAR DECIMAL(28,8) , LNGANAOLCUBIRIMKOD INT,TXTSEFERNO NVARCHAR(50) , LNGCARIKOD INT,DBLMAXAGIRLIK1 DECIMAL(28,8),TXTURETICIKODU NVARCHAR(50),BYTKARGOPARSIYEL TINYINT)    
CREATE TABLE #BUTUNDETAYLARMESAJ(LNGMALZEMEKOD INT, DBLANAMIKTAR DECIMAL(28,8))    
CREATE TABLE #DETAYLAR(LNGKOD INT IDENTITY(1,1),LNGMALZEMEKOD INT, DBLANAMIKTAR DECIMAL(28,8) , LNGANAOLCUBIRIMKOD INT,TXTSEFERNO NVARCHAR(50) , LNGCARIKOD INT,DBLMAXAGIRLIK1 DECIMAL(28,8),TXTURETICIKODU NVARCHAR(50))    
CREATE TABLE #KULLANILANSTOKLAR(LNGKOD INT,LNGCARIKOD INT,BYTRAMPA TINYINT,TXTSEFERNO NVARCHAR(50))    
CREATE TABLE #ELLECLEMESTOK (LNGSIRA INT IDENTITY(1,1) , DBLMIKTAR DECIMAL(28,8), LNGMALZEMEKOD INT, LNGBIRIMKOD INT)    
CREATE TABLE #DROPLIST( LNGLOKASYONKOD INT,TXTLOKASYONKOD NVARCHAR(50),LNGLINE INT,TXTGRUPKOD NVARCHAR(50),LNGSTOKSAYI INT)    
  
  
CREATE TABLE #RAFSTOK( LNGKOD INT , LNGLOKASYONKOD INT, LNGMALZEMEKOD INT, LNGSTATUKOD INT, TXTBATCHNO NVARCHAR(50), TXTSERINO NVARCHAR(50), TXTPO NVARCHAR(50), TXTPOLINE NVARCHAR(50), LNGPALETID INT, LNGMUSTERIKOD INT,    
    DBLANAMIKTAR DECIMAL(28, 8), DBLREZERVEMIKTAR DECIMAL(28, 8), LNGANAOLCUBIRIMI INT, DBLNETAGIRLIK DECIMAL(28, 8), DBLBRUTAGIRLIK DECIMAL(28, 8), LNGAGIRLIKOLCUBIRIMI INT, TRHSONKULLANMATARIHI DATETIME, TRHURETIMTARIHI DATETIME,     
    LNGREZERVEBELGEKOD INT, LNGREZERVEBELGETIPKOD INT, TRHILKISLEMTARIHI DATETIME, TRHSONISLEMTARIHI DATETIME)    
    
    
    
/*__________________DROP POINTLER ÇEKILIYOR, EN SON STOKLARA GÖRE ILGILI ELLEÇLEME VEYA RAMPA DROPLARINA ATAMA YAPILACAK_________________________________________________*/    
INSERT INTO #DROPLIST    
SELECT L.LNGKOD AS LNGLOKASYONKOD,L.TXTLOKASYONKOD,SUBSTRING(TXTLOKASYONKOD,1,CHARINDEX('-',TXTLOKASYONKOD)-2) AS LNGLINE,G.TXTKOD AS TXTGRUPKOD , 0 AS LNGSTOKSAYI   
 FROM TBLSBLOKASYON L    
INNER JOIN TBLSBLOKASYONGRUPBAGLANTI B ON L.LNGKOD = B.LNGLOKASYONKOD    
INNER JOIN TBLSBLOKASYONGRUP G ON B.LNGGRUPKOD = G.LNGKOD    
WHERE G.TXTKOD IN ('RL','EL')  AND L.BYTDURUM = 1  
  
--GOKHAN  
  
DECLARE @DROPLOK INT  
DECLARE CRSDROP1 CURSOR FOR  select LNGLOKASYONKOD FROM #DROPLIST  
  
OPEN CRSDROP1  
FETCH NEXT FROM CRSDROP1 INTO @DROPLOK  
WHILE @@FETCH_STATUS =0  BEGIN   DECLARE @STOKSAYI INT = 0  
  IF EXISTS(SELECT LNGLOKASYONKOD FROM TBLSBSTOKDURUM  WITH(NOLOCK) WHERE LNGLOKASYONKOD = @DROPLOK)   
  BEGIN  
   SET @STOKSAYI = @STOKSAYI+1  
  END  
  DECLARE @DROPSTOKSAYI INT   
  select  @DROPSTOKSAYI = ISNULL(COUNT(LNGKOD),0) from TBLSBISEMRIHAVUZU  WITH(NOLOCK) WHERE DBLMIKTAR > 0 AND LNGHEDEFLOKASYONKOD = @DROPLOK  
  SET @STOKSAYI = @STOKSAYI+@DROPSTOKSAYI  
  
  SET @DROPSTOKSAYI = 0  
  
  SELECT @DROPSTOKSAYI = ISNULL(COUNT(K.LNGKOD),0) from TBLSBBELGEBASLIK B  
  INNER JOIN TBLSBBELGEKAPSAM  K ON B.LNGKOD = K.LNGBASLIKKOD  
  WHERE B.TRHONAYTARIHI IS NULL AND K.LNGHEDEFLOKASYONKOD = @DROPLOK  
  
  SET @STOKSAYI = @STOKSAYI+@DROPSTOKSAYI  
  
  UPDATE #DROPLIST SET LNGSTOKSAYI = @STOKSAYI WHERE LNGLOKASYONKOD = @DROPLOK  
  
FETCH NEXT FROM CRSDROP1 INTO @DROPLOK    END  
CLOSE CRSDROP1  
DEALLOCATE CRSDROP1  
  
  
  
--DELETE FROM #DROPLIST WHERE LNGLOKASYONKOD IN (SELECT DISTINCT LNGLOKASYONKOD FROM TBLSBSTOKDURUM  WITH(NOLOCK))  
--DELETE FROM #DROPLIST WHERE LNGLOKASYONKOD IN (select DISTINCT LNGHEDEFLOKASYONKOD from TBLSBISEMRIHAVUZU  WITH(NOLOCK) WHERE DBLMIKTAR > 0 )  
--DELETE FROM #DROPLIST WHERE LNGLOKASYONKOD IN (  
-- SELECT DISTINCT K.LNGHEDEFLOKASYONKOD from TBLSBBELGEBASLIK B  
-- INNER JOIN TBLSBBELGEKAPSAM  K ON B.LNGKOD = K.LNGBASLIKKOD  
-- WHERE B.TRHONAYTARIHI IS NULL AND K.LNGHEDEFLOKASYONKOD IS NOT NULL)  
  
   
  
    
SET @SQL = 'INSERT INTO #BUTUNDETAYLAR    
  SELECT     
  BD.LNGMALZEMEKOD, SUM(BD.DBLANAMIKTAR ) AS DBLANAMIKTAR,BD.LNGANAOLCUBIRIMKOD, BB.TXTSEFERNO ,BB.LNGCARIKOD,U.DBLMAXAGIRLIK1*UOB.DBLCARPAN/UOB.DBLBOLEN AS DBLMAXAGIRLIK1,U.TXTURETICIKODU,    
  CASE WHEN N.ana_gonderi_tipi  IN (13,14) THEN 1 ELSE 0 END AS BYTKARGOPARSIYEL    
  FROM TBLSBBELGEDETAY BD    
  INNER JOIN TBLSBBELGEBASLIK BB ON BB.LNGKOD = BD.LNGBASLIKKOD       
  INNER JOIN _nakliyeci_bilgileri N ON BB.LNGKOD = N.belge_no    
  INNER JOIN TBLURUN U ON U.LNGKOD=BD.LNGMALZEMEKOD AND U.TXTURETICIKODU <> ''VRL''     
  INNER JOIN TBLSBURUNOLCUBIRIM UOB ON UOB.LNGBIRIMKOD  = 1  AND UOB.LNGURUNKOD = BD.LNGMALZEMEKOD   
  WHERE BB.LNGKOD IN ('+@TXTBELGEKOD+')    
  GROUP BY BB.LNGCARIKOD,BD.LNGMALZEMEKOD,BD.LNGANAOLCUBIRIMKOD,BB.TXTSEFERNO,BB.LNGCARIKOD,U.DBLMAXAGIRLIK1,U.TXTURETICIKODU,UOB.DBLCARPAN,UOB.DBLBOLEN,N.ana_gonderi_tipi'    
    
  PRINT(@SQL)    
  EXEC(@SQL)    
 
 INSERT INTO #BUTUNDETAYLARMESAJ
 SELECT LNGMALZEMEKOD, SUM(DBLANAMIKTAR) DBLANAMIKTAR FROM #BUTUNDETAYLAR GROUP BY LNGMALZEMEKOD
    
    
/* _________________________KARGO PARSIYELLER HARIC TAM PALETLER RAMPAYA GONDERILECEK____________________________________*/    
    
  DELETE FROM #DETAYLAR    
    
  INSERT INTO #DETAYLAR (LNGMALZEMEKOD , DBLANAMIKTAR, LNGANAOLCUBIRIMKOD ,TXTSEFERNO, LNGCARIKOD ,DBLMAXAGIRLIK1 ,TXTURETICIKODU)    
  SELECT LNGMALZEMEKOD , DBLANAMIKTAR, LNGANAOLCUBIRIMKOD ,TXTSEFERNO, LNGCARIKOD ,DBLMAXAGIRLIK1 ,TXTURETICIKODU    
  FROM #BUTUNDETAYLAR     
  WHERE BYTKARGOPARSIYEL = 0     
  ORDER BY DBLANAMIKTAR DESC     
      
    
      
     
      
      
    
  /* ___________________________________________________________TAM PALET HESAPLAMASI ____________________________________________________________________________________*/    
    
   DECLARE @LNGKOD INT,@LNGMALZEMEKOD INT,@LNGCARIKOD INT    
   DECLARE @DBLMIKTAR DECIMAL(28,8),@DBLMAXAGIRLIK DECIMAL(28,8)    
   DECLARE @TXTSEFERNO NVARCHAR(50)    
    
   --IHTIYAC SATIRLARINDA DÖNÜLÜYOR    
   DECLARE CRS CURSOR FOR      
    SELECT LNGKOD, DBLANAMIKTAR,LNGMALZEMEKOD,DBLMAXAGIRLIK1, TXTSEFERNO, LNGCARIKOD FROM #DETAYLAR     
    
   OPEN CRS    
   FETCH NEXT FROM CRS INTO @LNGKOD,@DBLMIKTAR,@LNGMALZEMEKOD,@DBLMAXAGIRLIK,@TXTSEFERNO ,@LNGCARIKOD    
   WHILE @@FETCH_STATUS =0    
    BEGIN    
       
     ---HER IHTIYAÇ IÇIN ÖNERI ÇALISTIRILIYOR    
      INSERT INTO #RAFSTOK EXEC SSP_SBISEMRIONERI @LNGMALZEMEKOD    
          
           
    -- TAM PALET IÇIN ÖNERI LISTESINDEN STOK ALINIYOR.    
    DECLARE @STOKKOD INT ,@STOKLOKASYONKOD INT,@STOKMIKTAR DECIMAL(28,8)    
    DECLARE CRS_TAM CURSOR FOR    
     SELECT LNGKOD,LNGLOKASYONKOD,DBLANAMIKTAR     
     FROM #RAFSTOK     
     WHERE DBLANAMIKTAR = @DBLMAXAGIRLIK     
     AND LNGKOD NOT IN (SELECT LNGKOD FROM #KULLANILANSTOKLAR)     
     --ORDER BY DBLANAMIKTAR DESC    
    
     OPEN CRS_TAM    
     FETCH NEXT FROM CRS_TAM INTO @STOKKOD,@STOKLOKASYONKOD,@STOKMIKTAR    
    
    WHILE @@FETCH_STATUS =0    
    BEGIN      
    
    
/*DEBUG___DEBUG___DEBUG___DEBUG___DEBUG___DEBUG___DEBUG___DEBUG___DEBUG___DEBUG___DEBUG___DEBUG___*/        
    --select 'DETAY',* from #DETAYLAR WHERE LNGMALZEMEKOD = @LNGMALZEMEKOD    
    --  select 'RAFSTOK',* from #RAFSTOK  WHERE LNGMALZEMEKOD = @LNGMALZEMEKOD AND LNGKOD NOT IN (SELECT LNGKOD FROM #KULLANILANSTOKLAR)    
    --  select 'KULLANILAN',* from #KULLANILANSTOKLAR  K    
    --  INNER JOIN TBLSBSTOKDURUM S ON K.LNGKOD = S.LNGKOD     
    --  WHERE LNGMALZEMEKOD = @LNGMALZEMEKOD         
    
    
     IF @DBLMIKTAR <= 0 OR @DBLMIKTAR < @DBLMAXAGIRLIK BREAK     
     --KULLANILAN STOKLAR LISTESI, TEKRAR TEKRAR KULLANIMINI ÖNLEMEK IÇIN    
     INSERT INTO #KULLANILANSTOKLAR (LNGKOD,LNGCARIKOD,BYTRAMPA,TXTSEFERNO)    
     VALUES(@STOKKOD,@LNGCARIKOD,CASE WHEN @DBLMAXAGIRLIK = 99  THEN 0 ELSE 1 END,    
            CASE WHEN @DBLMAXAGIRLIK = 99  THEN NULL ELSE @TXTSEFERNO END)               
         
         
     UPDATE #DETAYLAR SET DBLANAMIKTAR = DBLANAMIKTAR-@STOKMIKTAR WHERE LNGKOD = @LNGKOD    
     SET @DBLMIKTAR = @DBLMIKTAR - @STOKMIKTAR    
     --IF @DBLMIKTAR <= 0 OR @DBLMIKTAR < @DBLMAXAGIRLIK BREAK    
         
               
     FETCH NEXT FROM CRS_TAM INTO @STOKKOD,@STOKLOKASYONKOD,@STOKMIKTAR       
    END    
    CLOSE CRS_TAM    
    DEALLOCATE CRS_TAM    
                 
    DELETE FROM #RAFSTOK    
    -- TAM PALET ALMA ISLEMI TAMAMLANDI.    
      
   FETCH NEXT FROM CRS INTO @LNGKOD,@DBLMIKTAR,@LNGMALZEMEKOD,@DBLMAXAGIRLIK,@TXTSEFERNO,@LNGCARIKOD    
   END      
   CLOSE CRS    
   DEALLOCATE CRS    
    
       
    
    
 /* ____________________________________ELLEÇLEME STOGU DÜSÜLECEK VE ELLEÇLEMEYE GIDECEK PALETLER HESAPLANACAK__________________________________________________________*/    
     
 -- KARGO PARSIYEL KAYITLARI EKLENIYOR    
 --IHTIYACLAR SEFER VE CARIDEN BAGIMSIZ MALZEME MIKTAR SEKLINE ÇEVRILIYOR.     
 --DETAY TABLOSUNDAKI VERILER BU HALIYLE DEGISTIRILIYOR.    
     
 INSERT INTO #DETAYLAR (LNGMALZEMEKOD , DBLANAMIKTAR, LNGANAOLCUBIRIMKOD ,TXTSEFERNO, LNGCARIKOD ,DBLMAXAGIRLIK1 ,TXTURETICIKODU)    
 SELECT LNGMALZEMEKOD , DBLANAMIKTAR, LNGANAOLCUBIRIMKOD ,TXTSEFERNO, LNGCARIKOD ,DBLMAXAGIRLIK1 ,TXTURETICIKODU    
 FROM #BUTUNDETAYLAR WHERE BYTKARGOPARSIYEL = 1    
    
 DECLARE @MAX INT    
 SELECT @MAX=MAX(LNGKOD) FROM #DETAYLAR    
    
 INSERT INTO #DETAYLAR(LNGMALZEMEKOD, DBLANAMIKTAR, LNGANAOLCUBIRIMKOD ,TXTSEFERNO , LNGCARIKOD ,DBLMAXAGIRLIK1 ,TXTURETICIKODU )    
 SELECT LNGMALZEMEKOD, SUM(DBLANAMIKTAR) AS DBLANAMIKTAR , LNGANAOLCUBIRIMKOD,NULL,NULL, DBLMAXAGIRLIK1 ,TXTURETICIKODU     
 FROM #DETAYLAR    
 GROUP BY LNGMALZEMEKOD,LNGANAOLCUBIRIMKOD, DBLMAXAGIRLIK1 ,TXTURETICIKODU    
    
 DELETE FROM #DETAYLAR WHERE LNGKOD <= @MAX  OR DBLANAMIKTAR =0  
    
    
 --ZT02 OPERASYONU HARICINDE ELLEÇLEME STOGU DIKKATE ALINMAYACAK    
 IF EXISTS(SELECT * FROM TBLSBOPERASYONTIPI WHERE LNGKOD = @LNGOPERASYONTIPKOD AND TXTKOD ='ZT36')    
 BEGIN     
  --ELLEÇLEME ALANINDAKI KÜMÜLE STOK BULUNUP, IHTIYAÇLARDAN DÜSÜLECEK (FIFO VS. BAKILMADAN)    
  INSERT INTO #ELLECLEMESTOK(DBLMIKTAR,LNGBIRIMKOD,LNGMALZEMEKOD)    
  SELECT SUM(S.DBLANAMIKTAR) AS DBLANAMIKTAR, S.LNGANAOLCUBIRIMI,S.LNGMALZEMEKOD     
  FROM TBLSBSTOKDURUM S    
  INNER JOIN #DETAYLAR T ON T.LNGMALZEMEKOD= S.LNGMALZEMEKOD --sadece ihtiyaç olan malzemeler için stoga bakilsin    
  WHERE S.DBLANAMIKTAR > 0 AND LNGLOKASYONKOD IN(SELECT LNGKOD FROM TBLSBLOKASYON WHERE LNGALANKOD=43)--MELIH 20190521  
  GROUP BY S.LNGANAOLCUBIRIMI,S.LNGMALZEMEKOD    
     
  UPDATE D    
  SET D.DBLANAMIKTAR = D.DBLANAMIKTAR - ISNULL(E.DBLMIKTAR,0)    
  FROM #DETAYLAR D    
  LEFT JOIN #ELLECLEMESTOK E ON D.LNGMALZEMEKOD = E.LNGMALZEMEKOD    
    
  --IHTIYACI ELLEÇLEME ALANINDAN KARSILANANLARI SIL    
  DELETE FROM #DETAYLAR WHERE DBLANAMIKTAR <= 0     
 END    
    
     
 DECLARE CRS2 CURSOR FOR      
  SELECT LNGKOD, DBLANAMIKTAR,LNGMALZEMEKOD,DBLMAXAGIRLIK1 FROM #DETAYLAR    
    
 OPEN CRS2    
 FETCH NEXT FROM CRS2 INTO @LNGKOD,@DBLMIKTAR,@LNGMALZEMEKOD,@DBLMAXAGIRLIK    
 WHILE @@FETCH_STATUS =0    
  BEGIN      
    INSERT INTO #RAFSTOK EXEC SSP_SBISEMRIONERI @LNGMALZEMEKOD    
         
       
  -- --IHTIYACI TAM OLARAK KARSILAYAN STOK VARSA SIRADAN BAKMADAN ELLEÇLEMEYE DIREKT ONU YOLLASIN    
    
  -- IF EXISTS(SELECT * FROM #RAFSTOK WHERE LNGMALZEMEKOD = @LNGMALZEMEKOD AND DBLANAMIKTAR= @DBLMIKTAR)    
  -- BEGIN    
      
  --SELECT     
  --@STOKKOD = LNGKOD ,    
  --@STOKMIKTAR = DBLANAMIKTAR    
  --FROM  #RAFSTOK     
  --WHERE LNGMALZEMEKOD = @LNGMALZEMEKOD AND DBLANAMIKTAR= @DBLMIKTAR    
    
  --INSERT INTO #KULLANILANSTOKLAR (LNGKOD,LNGCARIKOD,BYTRAMPA,TXTSEFERNO)VALUES(@STOKKOD,NULL,0,NULL)     
      
  --DELETE FROM #DETAYLAR WHERE LNGKOD = @LNGKOD    
    
  -- END    
  -- ELSE    
  -- BEGIN    
    
    -- ELLEÇLEMEYE GIDECEK PALET ATAMA      
    DECLARE CRS_EL CURSOR FOR    
     SELECT LNGKOD,LNGLOKASYONKOD,DBLANAMIKTAR FROM #RAFSTOK ORDER BY TRHURETIMTARIHI ASC,DBLANAMIKTAR ASC    
    
     OPEN CRS_EL    
     FETCH NEXT FROM CRS_EL INTO @STOKKOD,@STOKLOKASYONKOD,@STOKMIKTAR    
    
    WHILE @@FETCH_STATUS =0    
    BEGIN     
         
     INSERT INTO #KULLANILANSTOKLAR (LNGKOD,LNGCARIKOD,BYTRAMPA,TXTSEFERNO)VALUES(@STOKKOD,NULL,0,NULL)    
       
     SET @DBLMIKTAR = @DBLMIKTAR-@STOKMIKTAR    
    
     UPDATE #DETAYLAR SET DBLANAMIKTAR = DBLANAMIKTAR-@STOKMIKTAR WHERE LNGKOD = @LNGKOD    
         
     IF @DBLMIKTAR = 0 OR @DBLMIKTAR < 0 BREAK       
         
    FETCH NEXT FROM CRS_EL INTO @STOKKOD,@STOKLOKASYONKOD,@STOKMIKTAR       
    END    
    CLOSE CRS_EL    
    DEALLOCATE CRS_EL    
   --END    
    
  DELETE FROM #RAFSTOK    
  -- ELLEÇLEMEYE GIDECEK PALET ATAMA BITTI    
      
 FETCH NEXT FROM CRS2 INTO @LNGKOD,@DBLMIKTAR,@LNGMALZEMEKOD,@DBLMAXAGIRLIK    
 END      
 CLOSE CRS2    
 DEALLOCATE CRS2    



 /* Eksik ürünler sevkiyat depoda varsa hata verilmesin, is emri kullanilmadan manuel ve öneri listesiyle toplayacaklar */
 UPDATE D
  SET D.DBLANAMIKTAR = D.DBLANAMIKTAR - ISNULL(S.DBLANAMIKTAR,0)
 FROM #DETAYLAR D 
 LEFT JOIN (SELECT SUM(DBLANAMIKTAR) AS DBLANAMIKTAR,LNGMALZEMEKOD FROM TBLSBSTOKDURUM WHERE LNGLOKASYONKOD = 12443 GROUP BY LNGMALZEMEKOD) S ON D.LNGMALZEMEKOD = S.LNGMALZEMEKOD
 WHERE D.DBLANAMIKTAR > 0 
 /* Eksik ürünler sevkiyat depoda varsa hata verilmesin, is emri kullanilmadan manuel ve öneri listesiyle toplayacaklar */
   
    
 IF EXISTS(SELECT * FROM #DETAYLAR WHERE DBLANAMIKTAR > 0)
 BEGIN    
 DECLARE @MSG NVARCHAR(MAX) = 'Stok yetersiz, is emri olusturulamiyor. Eksik Stoklar; '    
 DECLARE @YETERSIZ NVARCHAR(MAX)    
  SELECT  @YETERSIZ=STUFF((SELECT ', '+ A.MESAJ     
  FROM (    
  select U.TXTKOD + ': ' + CONVERT(NVARCHAR,CONVERT(DECIMAL(28,2),D.DBLANAMIKTAR)) + ' / '+  CONVERT(NVARCHAR,CONVERT(DECIMAL(28,2),BD.DBLANAMIKTAR)) + ' ' +B.TXTKOD   AS MESAJ    
  from #DETAYLAR D   
  INNER JOIN #BUTUNDETAYLARMESAJ BD ON D.LNGMALZEMEKOD = BD.LNGMALZEMEKOD  
  LEFT JOIN TBLURUN U ON U.LNGKOD = D.LNGMALZEMEKOD    
  INNER JOIN TBLSBBIRIM B ON D.LNGANAOLCUBIRIMKOD = B.LNGKOD    
  WHERE D.DBLANAMIKTAR > 0    
  ) A    
  FOR XML PATH('')),1,1,'')    
  SET @MSG = @MSG + @YETERSIZ    
  RAISERROR(@MSG,16,1)    
  RETURN    
 END    
     
  
--ALTER TABLE #KULLANILANSTOKLAR ADD LNGHEDEFLOKASYONKOD INT  
ALTER TABLE #KULLANILANSTOKLAR ADD TXTHEDEFLOKASYONKOD NVARCHAR(50)  
  
  
  
DECLARE @STOKKODU INT DECLARE @TXTKAYNAKLOKKOD VARCHAR(50)  
  
DECLARE CRSDROP CURSOR FOR  select K.LNGKOD,L.TXTLOKASYONKOD  
FROM #KULLANILANSTOKLAR K    
INNER JOIN TBLSBSTOKDURUM S On K.LNGKOD = S.LNGKOD    
INNER JOIN TBLSBLOKASYON L ON S.LNGLOKASYONKOD = L.LNGKOD    
  
OPEN CRSDROP  
FETCH NEXT FROM CRSDROP INTO @STOKKODU,@TXTKAYNAKLOKKOD  
WHILE @@FETCH_STATUS =0  BEGIN   DECLARE @TXTTEMPLOKASYON NVARCHAR(50)   DECLARE @LNGMINSTOKSAYI INT     select @LNGMINSTOKSAYI = MIN(LNGSTOKSAYI )   
  FROM #KULLANILANSTOKLAR K    
  INNER JOIN TBLSBSTOKDURUM S On K.LNGKOD = S.LNGKOD    
  INNER JOIN TBLSBLOKASYON L ON S.LNGLOKASYONKOD = L.LNGKOD    
  LEFT JOIN #DROPLIST D ON CASE WHEN K.BYTRAMPA = CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2))%2   THEN CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2))    
        WHEN K.BYTRAMPA <> 0 AND CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2))%2 =0 THEN CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2)) -1             
  ELSE CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2)) +1 END =D.LNGLINE   
  WHERE K.LNGKOD = @STOKKODU    select @TXTTEMPLOKASYON= MIN(D.TXTLOKASYONKOD )   
  FROM #KULLANILANSTOKLAR K    
  INNER JOIN TBLSBSTOKDURUM S On K.LNGKOD = S.LNGKOD    
  INNER JOIN TBLSBLOKASYON L ON S.LNGLOKASYONKOD = L.LNGKOD    
  LEFT JOIN #DROPLIST D ON CASE WHEN K.BYTRAMPA = CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2))%2   THEN CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2))    
        WHEN K.BYTRAMPA <> 0 AND CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2))%2 =0 THEN CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2)) -1             
  ELSE CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2)) +1 END =D.LNGLINE   
  WHERE K.LNGKOD = @STOKKODU AND D.LNGSTOKSAYI = @LNGMINSTOKSAYI  
     
   UPDATE #KULLANILANSTOKLAR SET TXTHEDEFLOKASYONKOD = @TXTTEMPLOKASYON  WHERE LNGKOD = @STOKKODU  
   UPDATE #DROPLIST SET LNGSTOKSAYI = LNGSTOKSAYI + 1 WHERE TXTLOKASYONKOD = @TXTTEMPLOKASYON  
  
  
FETCH NEXT FROM CRSDROP INTO @STOKKODU,@TXTKAYNAKLOKKOD    END  
CLOSE CRSDROP  
DEALLOCATE CRSDROP  
  
  
   
select K.BYTRAMPA,L2.LNGKOD AS LNGHEDEFLOKASYONKOD,K.TXTHEDEFLOKASYONKOD AS TXTHEDEFLOKASYONKOD ,L.TXTLOKASYONKOD AS TXTKAYNAKLOKASYONKOD,P.TXTPALETNO,K.LNGCARIKOD,K.TXTSEFERNO,S.*     
FROM #KULLANILANSTOKLAR K    
INNER JOIN TBLSBSTOKDURUM S On K.LNGKOD = S.LNGKOD    
INNER JOIN TBLSBLOKASYON L ON S.LNGLOKASYONKOD = L.LNGKOD    
LEFT JOIN TBLSBPALET P ON P.LNGKOD = S.LNGPALETID    
INNER JOIN TBLSBLOKASYON L2 ON L2.TXTLOKASYONKOD = K.TXTHEDEFLOKASYONKOD  
  
    
    
  
    /*  
select K.BYTRAMPA/*,D.LNGLOKASYONKOD AS LNGHEDEFLOKASYONKOD,D.TXTLOKASYONKOD AS TXTHEDEFLOKASYONKOD */,L.TXTLOKASYONKOD AS TXTKAYNAKLOKASYONKOD,P.TXTPALETNO,K.LNGCARIKOD,K.TXTSEFERNO,S.*     
FROM #KULLANILANSTOKLAR K    
INNER JOIN TBLSBSTOKDURUM S On K.LNGKOD = S.LNGKOD    
INNER JOIN TBLSBLOKASYON L ON S.LNGLOKASYONKOD = L.LNGKOD    
LEFT JOIN TBLSBPALET P ON P.LNGKOD = S.LNGPALETID    
LEFT JOIN #DROPLIST D ON CASE WHEN K.BYTRAMPA = CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2))%2   THEN CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2))    
         WHEN K.BYTRAMPA <> 0 AND CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2))%2 =0 THEN CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2)) -1    
         ELSE CONVERT(INT,SUBSTRING(L.TXTLOKASYONKOD,1,CHARINDEX('-',L.TXTLOKASYONKOD)-2)) +1 END =D.LNGLINE   
    
  */  
    
DROP TABLE #DETAYLAR    
DROP TABLE #ELLECLEMESTOK    
DROP TABLE #RAFSTOK    
-- SSP_SBISEMRIBELGEHAZIRLA 263, '451924' ,451925,451926,451927'    