CREATE PROCEDURE [dbo].[SSP_SBSEPETDAGIT_ORJ] (@LNGDISTKOD INT, @LNGBELGEKODLIST NVARCHAR(MAX), @DEVMODE TINYINT = 0)
AS
BEGIN

CREATE TABLE #BELGELIST (LNGKOD INTEGER, LNGOPERASYONTIPKOD INTEGER, TXTPLAKA NVARCHAR(50), TXTDAGITIMYONU NVARCHAR(1), TXTDURUM NVARCHAR(50))
CREATE TABLE #BELGEDETAYLIST (LNGBASLIKKOD INTEGER, LNGDETAYKOD INTEGER, TXTURUNGRUP NVARCHAR(10), TXTURUNUSTGRUP NVARCHAR(10),DBLDETAYHACIM DECIMAL(28,8), LNGURUNKOD INT, 
 DBLMIKTAR DECIMAL(28,8), DBLISLEMBIRIMHACIM DECIMAL(28,8), LNGISLEMOLCUBIRIM INT, TXTDAGITIMYONU NVARCHAR(1), DBLKALANMIKTAR DECIMAL(28,8))
CREATE TABLE #SEPETLER (TXTPLAKA NVARCHAR(50), TXTANASEPET NVARCHAR(50), TXTALTSEPET NVARCHAR(50), DBLSEPETHACIM DECIMAL(28,8), DBLYUKLENENHACIM DECIMAL(28,8) DEFAULT 0, TXTSEPETDAGITIMYONU NVARCHAR(1) 
 , TXTSEPETURUNGRUBU NVARCHAR(50), TXTSEPETURUNUSTGRUBU NVARCHAR(50))
CREATE TABLE #SEPETBELGE (LNGBELGEKOD INT, LNGBELGEDETAYKOD INT, TXTGECICISEPET NVARCHAR(50), LNGURUNKOD INT, DBLMIKTAR DECIMAL(28,8), DBLOLCUBIRIMHACIM DECIMAL(28,8), LNGISLEMOLCUBIRIM INT
   , TXTURUNGRUP NVARCHAR(50), TXTURUNUSTGRUP NVARCHAR(50))


DECLARE @DONULECEKPLAKA AS NVARCHAR(20)
      DECLARE XPLAKA CURSOR FAST_FORWARD FOR SELECT DISTINCT TXTPLAKANO FROM VIEWSBSEPETDAGITIM WHERE LNGKOD IN (SELECT * FROM STRING_SPLIT(@LNGBELGEKODLIST, ',') )
      OPEN XPLAKA
      FETCH NEXT FROM XPLAKA INTO @DONULECEKPLAKA
      WHILE(@@FETCH_STATUS = 0)
      BEGIN
      
  /*** VERİHAZIRLANIYOR, KONTROLLER YAPILIYOR***/
  DELETE FROM #BELGELIST
  INSERT INTO #BELGELIST (LNGKOD, LNGOPERASYONTIPKOD, TXTPLAKA, TXTDAGITIMYONU, TXTDURUM)
  SELECT BELGE.LNGKOD, BB.LNGOPERASYONTIPKOD, BELGE.TXTPLAKANO, SUBSTRING(EKSAHA.TXTEKSAHAACIKLAMA,1,1), BELGE.TXTDURUM 
    FROM VIEWSBSEPETDAGITIM BELGE
	INNER JOIN TBLSBBELGEBASLIK BB (NOLOCK) ON BB.LNGKOD = BELGE.LNGKOD
	LEFT OUTER JOIN TBLSBBELGEBASLIKEKSAHA EKSAHA (NOLOCK) ON EKSAHA.LNGBAGLANTIKOD = BELGE.LNGKOD AND EKSAHA.LNGEKSAHAKODU IN (SELECT LNGTAKIPKOD FROM TBLEKSAHATANIMLAMA WHERE TXTACIKLAMA = 'DagitimYonu')
   WHERE BELGE.LNGKOD IN (SELECT * FROM STRING_SPLIT(@LNGBELGEKODLIST, ','))
   AND BELGE.TXTPLAKANO = @DONULECEKPLAKA

   IF (SELECT COUNT(1) FROM #BELGELIST WHERE TXTDURUM = 'ATANMIŞ') > 0 AND @DEVMODE = 0 
   BEGIN
     RAISERROR('Atanmış kayıtlar için dağıtım yapılamaz',16,1)
	 RETURN
   END

  DECLARE @HEPSIYONDEGERI NVARCHAR(1) = 'H',@Mesaj NVARCHAR(MAX)
   
  DECLARE @DAGITIMYONUZORUNLU TINYINT
  SELECT @DAGITIMYONUZORUNLU = CASE WHEN ISNULL(TXTDEGER,'') = 'X' THEN 1 ELSE 0 END FROM TBLSBBELGEPARAMETRE WHERE BYTPARAMETRE = 43 AND LNGBELGETIPKOD IN (SELECT LNGOPERASYONTIPKOD FROM #BELGELIST)
  IF (@DAGITIMYONUZORUNLU = 1)
  BEGIN
   IF (SELECT COUNT(1) FROM #BELGELIST WHERE ISNULL(TXTDAGITIMYONU,'') = '') > 0
   BEGIN
    RAISERROR('Belgelerde dağıtım yönü bulunamadığı için işlem yapılamadı!',16,1)
    RETURN 
   END
  END

  /* GEÇİCİ OLARAK KAPATILDI AÇILACAK !!!!!!!!!!*/
  IF (
  SELECT COUNT(1) FROM VIEWSBSEPETDAGITIM V 
   WHERE V.LNGKOD NOT IN (SELECT B.LNGKOD FROM #BELGELIST B)
     AND V.TXTPLAKANO IN (SELECT B.TXTPLAKA FROM #BELGELIST B) ) > 0  AND @DEVMODE = 0 
	 BEGIN
	  RAISERROR('Plakaya ait tüm belgeler seçilmediğinden dağıtım yapılmayacak!',16,1)
      RETURN 
	 END
/**/
   IF (@DAGITIMYONUZORUNLU = 1)
   BEGIN
    UPDATE #BELGELIST
     SET TXTDAGITIMYONU = @HEPSIYONDEGERI
   WHERE ISNULL(TXTDAGITIMYONU,'') = ''
    END
   ELSE
   BEGIN
    SET @HEPSIYONDEGERI = 'X'
   UPDATE #BELGELIST
      SET TXTDAGITIMYONU = @HEPSIYONDEGERI
   END 

  DELETE FROM #BELGEDETAYLIST
  INSERT INTO #BELGEDETAYLIST (LNGBASLIKKOD, LNGDETAYKOD, TXTURUNGRUP, TXTURUNUSTGRUP, DBLDETAYHACIM, LNGURUNKOD, DBLMIKTAR, DBLISLEMBIRIMHACIM, LNGISLEMOLCUBIRIM, TXTDAGITIMYONU, DBLKALANMIKTAR)
  SELECT BD.LNGBASLIKKOD, BD.LNGKOD, UG.TXTKOD, UG2.TXTKOD, BD.DBLISLEMMIKTARI*ISNULL(OB.DBLHACIM,0) , BD.LNGMALZEMEKOD, BD.DBLISLEMMIKTARI, 
  ISNULL(OB.DBLHACIM,0), BD.LNGISLEMOLCUBIRIMKOD, 
   B.TXTDAGITIMYONU ,BD.DBLISLEMMIKTARI
    FROM TBLSBBELGEDETAY BD (NOLOCK)
 INNER JOIN TBLSBURUNOLCUBIRIM OB (NOLOCK) ON BD.LNGMALZEMEKOD = OB.LNGURUNKOD AND OB.LNGBIRIMKOD = BD.LNGISLEMOLCUBIRIMKOD 
 LEFT OUTER JOIN TBLSBURUNEKGRUPBAGLANTI UGB (NOLOCK) ON UGB.LNGSIRANO = 2 AND UGB.LNGURUNKOD = BD.LNGMALZEMEKOD
 LEFT OUTER JOIN TBLSBGRUP UG (NOLOCK) ON UG.LNGKOD = UGB.LNGGRUPKOD
 LEFT OUTER JOIN TBLSBURUNEKGRUPBAGLANTI UGB2 (NOLOCK) ON UGB2.LNGSIRANO = 1 AND UGB2.LNGURUNKOD = BD.LNGMALZEMEKOD
 LEFT OUTER JOIN TBLSBGRUP UG2 (NOLOCK) ON UG2.LNGKOD = UGB2.LNGGRUPKOD
 INNER JOIN #BELGELIST B ON B.LNGKOD = BD.LNGBASLIKKOD  

 --IF (SELECT COUNT(1) FROM #BELGEDETAYLIST WHERE ISNULL(DBLDETAYHACIM,0) = 0) > 0
 --BEGIN
 -- RAISERROR('Seçilen belge detaylarında hacim hesaplanmadığı için dağıtım yapılamamıştır. Ürün ölçü birim hacim değerlerini kontrol ediniz!',16,1)
 -- RETURN
 --END
  DECLARE @URUNKOD NVARCHAR(50) = ''
  IF (SELECT COUNT(1) FROM #BELGEDETAYLIST WHERE ISNULL(DBLDETAYHACIM,0) = 0) > 0
 BEGIN
 SELECT @URUNKOD=U.TXTKOD FROM #BELGEDETAYLIST D 
 INNER JOIN TBLURUN U ON U.LNGKOD=D.LNGURUNKOD
 WHERE ISNULL(DBLDETAYHACIM,0) = 0
 SET @Mesaj='Seçilen belge detaylarında hacim hesaplanmadığı için dağıtım yapılamamıştır. ' + @URUNKOD +' kodlu ürüne ait ölçü birim hacim değerlerini kontrol ediniz!'
  RAISERROR(@Mesaj,16,1)
  RETURN
 END
 
 IF (SELECT COUNT(1) FROM #BELGEDETAYLIST WHERE ISNULL(TXTURUNGRUP,'') = '') > 0
 BEGIN
  RAISERROR('Seçilen belge detaylarında ürün grup bağlantısı yapılmadığı için dağıtım yapılamamıştır!',16,1)
  RETURN
 END

  DELETE FROM #SEPETLER
  DECLARE @PLAKA NVARCHAR(50)
  DECLARE XCURSOR_ARAC CURSOR FAST_FORWARD FOR SELECT DISTINCT TXTPLAKA FROM #BELGELIST
  OPEN XCURSOR_ARAC
  FETCH NEXT FROM XCURSOR_ARAC INTO @PLAKA
  WHILE(@@FETCH_STATUS = 0)
  BEGIN     
         DECLARE @SEPET_ADI NVARCHAR(50), @SEPET_HACIM DECIMAL(28,8), @SEPET_SAYISI INT
		 DECLARE @i INT = 1
		 SELECT @SEPET_ADI = ST.TXTKOD, 
		        @SEPET_HACIM = ST.DBLHACIM + ISNULL(ST.DBLHACIMTOLERANS,0), 
				@SEPET_SAYISI = STB.LNGSEPETSAYISI
		   FROM TBLSBSEPETTIPI ST (NOLOCK)
	 INNER JOIN TBLSBARACTIPISEPETTIPIBAGLANTI STB (NOLOCK) ON STB.LNGSEPETTIPKOD = ST.LNGKOD
	 INNER JOIN TBLSBARAC ARAC (NOLOCK) ON ARAC.LNGARACTIPKOD = STB.LNGARACTIPKOD
		  WHERE ARAC.TXTPLAKA = @PLAKA

		  WHILE @i <= @SEPET_SAYISI
		  BEGIN
		    INSERT INTO #SEPETLER (TXTPLAKA, TXTANASEPET, TXTALTSEPET, DBLSEPETHACIM)
			SELECT @PLAKA, @SEPET_ADI, @SEPET_ADI+'_'+CONVERT(NVARCHAR,@i), @SEPET_HACIM
			SET @i = @i+1
		  END
        FETCH NEXT FROM XCURSOR_ARAC INTO @PLAKA
  END
  CLOSE XCURSOR_ARAC
  DEALLOCATE XCURSOR_ARAC
  
  DECLARE @SORUNLUARAC NVARCHAR(50), @SORUNLUARACHACIM  NVARCHAR(50), @SORUNLUARACBELGETOPLAMHACIM  NVARCHAR(50)
  SELECT TOP 1 @SORUNLUARAC = AA.TXTPLAKA, @SORUNLUARACHACIM = AA.ARACHACIM, @SORUNLUARACBELGETOPLAMHACIM = AA.BELGEHACIM  FROM (
  SELECT S.TXTPLAKA, SUM(DBLSEPETHACIM) ARACHACIM ,  (SELECT SUM(DBLDETAYHACIM)      
	FROM #BELGELIST B INNER JOIN #BELGEDETAYLIST BD ON BD.LNGBASLIKKOD = B.LNGKOD WHERE  B.TXTPLAKA = S.TXTPLAKA) BELGEHACIM
    FROM #SEPETLER S	
	GROUP BY S.TXTPLAKA ) AA
	WHERE AA.ARACHACIM - AA.BELGEHACIM < 0
	 
	IF (ISNULL(@SORUNLUARAC,'') <> '')
	BEGIN
	  DECLARE @MSJ NVARCHAR(250) = @SORUNLUARAC + ' plakalı araç hacmi=' + @SORUNLUARACHACIM  +' m3 ,seçilen siparişlerin hacmi='+@SORUNLUARACBELGETOPLAMHACIM+' m3 olduğundan işlem yapılamaz'
	  RAISERROR(@MSJ,16,1)
	  RETURN
	END

IF (SELECT COUNT(1) FROM #SEPETLER ) = 0 
 BEGIN
  RAISERROR('Sepet olmadığı için dağıtım yapılamamıştır. Sepet tanımlarını kontrol ediniz!',16,1)
  RETURN
 END

	DECLARE @SORUNLUPLAKA NVARCHAR(50) = NULL, @SORUNLUYON NVARCHAR(1)
	 SELECT DISTINCT  @SORUNLUPLAKA = TXTPLAKA, @SORUNLUYON = TXTDAGITIMYONU  FROM (
	 SELECT #BELGELIST.TXTPLAKA, SUM(#BELGEDETAYLIST.DBLDETAYHACIM) BELGEDETAYTOPLAMHACIM ,(SELECT SUM(#SEPETLER.DBLSEPETHACIM) 
	                                                        FROM #SEPETLER 
														WHERE #SEPETLER.TXTPLAKA = #BELGELIST.TXTPLAKA ) ARACHACIM 
	 , #BELGEDETAYLIST.TXTDAGITIMYONU  FROM #BELGEDETAYLIST 
	 INNER JOIN #BELGELIST ON #BELGELIST.LNGKOD =#BELGEDETAYLIST.LNGBASLIKKOD 
	 WHERE #BELGEDETAYLIST.TXTDAGITIMYONU <> @HEPSIYONDEGERI
	 GROUP BY #BELGEDETAYLIST.TXTDAGITIMYONU ,#BELGEDETAYLIST.LNGBASLIKKOD,#BELGELIST.TXTPLAKA )AA
	 GROUP BY TXTPLAKA, ARACHACIM,TXTDAGITIMYONU
	  HAVING  SUM (BELGEDETAYTOPLAMHACIM)  > ARACHACIM /2

 IF (@SORUNLUPLAKA IS NOT NULL) AND (@DAGITIMYONUZORUNLU = 1)
	  BEGIN
	  DECLARE @MSJ2 NVARCHAR(500) = @SORUNLUPLAKA + ' plakalı araçta '+@SORUNLUYON+' yönü araç hacmini aşıyor.Dağıtım yapılamaz! '
	   RAISERROR(@MSJ2,16,1)
       RETURN
	  END

    DELETE FROM #SEPETBELGE

	/*** DAĞITIM BAŞLIYOR ***/
	BEGIN
	  DECLARE @BELGEKOD INT, @BELGEDETAYKOD INT, @URUNGRUP NVARCHAR(50), @HACIM DECIMAL(28,8), @YON NVARCHAR, @URUNUSTGRUP NVARCHAR(50)
      DECLARE XBELGEDAGITIM CURSOR FAST_FORWARD FOR SELECT DISTINCT B.LNGKOD, BD.LNGDETAYKOD, BD.TXTURUNGRUP, BD.TXTURUNUSTGRUP, SUM(BD.DBLDETAYHACIM) , B.TXTDAGITIMYONU
	  FROM #BELGELIST B INNER JOIN #BELGEDETAYLIST BD ON BD.LNGBASLIKKOD = B.LNGKOD
	  GROUP BY B.LNGKOD, BD.LNGDETAYKOD, BD.TXTURUNGRUP, B.TXTDAGITIMYONU, BD.TXTURUNUSTGRUP 
	  ORDER BY 5 DESC
      OPEN XBELGEDAGITIM
      FETCH NEXT FROM XBELGEDAGITIM INTO @BELGEKOD, @BELGEDETAYKOD, @URUNGRUP, @URUNUSTGRUP, @HACIM, @YON
      WHILE(@@FETCH_STATUS = 0)
      BEGIN
            DECLARE @GECICISEPET NVARCHAR(50)=  NULL
            SELECT TOP 1 @GECICISEPET = S.TXTALTSEPET FROM #SEPETLER S
			WHERE (S.TXTSEPETURUNGRUBU IS NULL OR S.TXTSEPETURUNGRUBU  = @URUNGRUP)
			  AND ( @YON = @HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU IS NULL OR S.TXTSEPETDAGITIMYONU = @YON)
			  AND S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @HACIM
			  ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM ASC, TXTALTSEPET			
			  --ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET		' HOMOJEN DAĞITILACAKSA AÇILACAK	
			
			IF (@GECICISEPET IS NULL)
			BEGIN
			   SELECT TOP 1 @GECICISEPET = S.TXTALTSEPET FROM #SEPETLER S
			WHERE (S.TXTSEPETURUNUSTGRUBU IS NULL OR S.TXTSEPETURUNUSTGRUBU  = @URUNUSTGRUP)
			  AND ( @YON = @HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU IS NULL OR S.TXTSEPETDAGITIMYONU = @YON)
			  AND S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @HACIM
			  ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM ASC, TXTALTSEPET			
			  --ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET		' HOMOJEN DAĞITILACAKSA AÇILACAK	
			END	

			IF (@GECICISEPET IS NULL)
			BEGIN
			  SELECT TOP 1 @GECICISEPET = S.TXTALTSEPET FROM #SEPETLER S
			   WHERE S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @HACIM
			    AND (@YON = @HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU IS NULL OR S.TXTSEPETDAGITIMYONU = @YON)
			  ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM ASC, TXTALTSEPET			
			  --ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET		' HOMOJEN DAĞITILACAKSA AÇILACAK	
			END			
			
			IF (@GECICISEPET IS NOT NULL)			
			BEGIN
			  INSERT INTO #SEPETBELGE (LNGBELGEKOD, LNGBELGEDETAYKOD, TXTGECICISEPET, LNGURUNKOD, DBLMIKTAR, DBLOLCUBIRIMHACIM, LNGISLEMOLCUBIRIM, TXTURUNGRUP )
			  SELECT @BELGEKOD, @BELGEDETAYKOD, @GECICISEPET, BD.LNGURUNKOD, BD.DBLMIKTAR, BD.DBLISLEMBIRIMHACIM, BD.LNGISLEMOLCUBIRIM, @URUNGRUP
			    FROM #BELGEDETAYLIST BD
		       WHERE BD.LNGBASLIKKOD = @BELGEKOD AND BD.LNGDETAYKOD = @BELGEDETAYKOD

			  UPDATE #SEPETLER
			     SET DBLYUKLENENHACIM = DBLYUKLENENHACIM + @HACIM,
				     TXTSEPETDAGITIMYONU = CASE WHEN TXTSEPETDAGITIMYONU IS NULL THEN @YON ELSE TXTSEPETDAGITIMYONU END,
					 TXTSEPETURUNGRUBU = CASE WHEN TXTSEPETURUNGRUBU IS NULL THEN @URUNGRUP ELSE TXTSEPETURUNGRUBU END,
					 TXTSEPETURUNUSTGRUBU = CASE WHEN TXTSEPETURUNUSTGRUBU IS NULL THEN @URUNUSTGRUP ELSE TXTSEPETURUNUSTGRUBU END
			   WHERE TXTALTSEPET = @GECICISEPET

			   UPDATE #BELGEDETAYLIST
				    SET #BELGEDETAYLIST.DBLKALANMIKTAR = 0
					WHERE #BELGEDETAYLIST.LNGDETAYKOD =@BELGEDETAYKOD AND #BELGEDETAYLIST.LNGBASLIKKOD = @BELGEKOD 
			END
			
            FETCH NEXT FROM XBELGEDAGITIM INTO @BELGEKOD, @BELGEDETAYKOD, @URUNGRUP, @URUNUSTGRUP, @HACIM, @YON
      END
      CLOSE XBELGEDAGITIM
      DEALLOCATE XBELGEDAGITIM	
	END
	
/***R siparişi boşta kaldı ve H de sepet varsa***/
IF (SELECT COUNT(1)
  FROM #BELGEDETAYLIST BD 
 WHERE (BD.LNGDETAYKOD) NOT IN (SELECT S.LNGBELGEDETAYKOD FROM #SEPETBELGE S) AND BD.TXTDAGITIMYONU = 'R') > 0 
  AND (SELECT COUNT(1) FROM #SEPETLER WHERE TXTSEPETDAGITIMYONU = @HEPSIYONDEGERI AND DBLSEPETHACIM - DBLYUKLENENHACIM > 0) > 0
	BEGIN  
   DECLARE @RBELGEKOD INT, @RBELGEDETAYKOD INT, @RURUNGRUP NVARCHAR(50), @RURUNUSTGRUP NVARCHAR(50), @RHACIM DECIMAL(28,8)  
      DECLARE XRIGHT CURSOR FAST_FORWARD FOR SELECT DISTINCT B.LNGKOD, BD.LNGDETAYKOD, BD.TXTURUNGRUP, BD.TXTURUNUSTGRUP, SUM(BD.DBLDETAYHACIM)   
   FROM #BELGELIST B INNER JOIN #BELGEDETAYLIST BD ON BD.LNGBASLIKKOD = B.LNGKOD 
   WHERE (BD.LNGDETAYKOD) NOT IN (SELECT S.LNGBELGEDETAYKOD FROM #SEPETBELGE S) AND BD.TXTDAGITIMYONU = 'R'  
   GROUP BY B.LNGKOD, BD.LNGDETAYKOD, BD.TXTURUNGRUP, BD.TXTURUNUSTGRUP
   ORDER BY 5 DESC  
      OPEN XRIGHT  
      FETCH NEXT FROM XRIGHT INTO @RBELGEKOD, @RBELGEDETAYKOD, @RURUNGRUP, @RURUNUSTGRUP, @RHACIM  
      WHILE(@@FETCH_STATUS = 0)  
      BEGIN  
            DECLARE @RGECICISEPET NVARCHAR(50) =  NULL  
            SELECT TOP 1 @RGECICISEPET = S.TXTALTSEPET FROM #SEPETLER S  
   WHERE S.TXTSEPETURUNGRUBU = @RURUNGRUP
     AND S.TXTSEPETDAGITIMYONU  IN ('R', @HEPSIYONDEGERI)
     AND S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @RHACIM  
     ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM ASC, TXTALTSEPET     
     --ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET  ' HOMOJEN DAĞITILACAKSA AÇILACAK   

   IF (@RGECICISEPET IS NULL)  
   BEGIN  
      SELECT TOP 1 @RGECICISEPET = S.TXTALTSEPET FROM #SEPETLER S  
   WHERE S.TXTSEPETURUNUSTGRUBU = @RURUNUSTGRUP
     AND S.TXTSEPETDAGITIMYONU  IN ('R', @HEPSIYONDEGERI)
     AND S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @RHACIM  
     ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM ASC, TXTALTSEPET     
     --ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET  ' HOMOJEN DAĞITILACAKSA AÇILACAK   
   END     
          

   IF (@RGECICISEPET IS NULL)  
   BEGIN  
     SELECT TOP 1 @RGECICISEPET = S.TXTALTSEPET FROM #SEPETLER S  
      WHERE S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @RHACIM  
        AND S.TXTSEPETDAGITIMYONU  IN ('R', @HEPSIYONDEGERI)
     ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM ASC, TXTALTSEPET     
     --ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET  ' HOMOJEN DAĞITILACAKSA AÇILACAK   
   END     
     
   IF (@RGECICISEPET IS NOT NULL)     
   BEGIN  
    INSERT INTO #SEPETBELGE (LNGBELGEKOD, LNGBELGEDETAYKOD, TXTGECICISEPET, LNGURUNKOD, DBLMIKTAR, DBLOLCUBIRIMHACIM, LNGISLEMOLCUBIRIM, TXTURUNGRUP )  
     SELECT @RBELGEKOD, @RBELGEDETAYKOD, @RGECICISEPET, BD.LNGURUNKOD, BD.DBLMIKTAR, BD.DBLISLEMBIRIMHACIM, BD.LNGISLEMOLCUBIRIM  , @RURUNGRUP
       FROM #BELGEDETAYLIST BD  
         WHERE BD.LNGBASLIKKOD = @RBELGEKOD AND BD.LNGDETAYKOD = @RBELGEDETAYKOD  
  
     UPDATE #SEPETLER  
        SET DBLYUKLENENHACIM = DBLYUKLENENHACIM + @RHACIM,  
         TXTSEPETDAGITIMYONU = 'R',  
      TXTSEPETURUNGRUBU = CASE WHEN TXTSEPETURUNGRUBU IS NULL THEN @RURUNGRUP ELSE TXTSEPETURUNGRUBU END  ,
	  TXTSEPETURUNUSTGRUBU = CASE WHEN TXTSEPETURUNUSTGRUBU IS NULL THEN @RURUNUSTGRUP ELSE TXTSEPETURUNUSTGRUBU END  
      WHERE TXTALTSEPET = @RGECICISEPET  

	  UPDATE #BELGEDETAYLIST
         SET DBLKALANMIKTAR = 0
         WHERE LNGDETAYKOD =@RBELGEDETAYKOD AND LNGBASLIKKOD =  @RBELGEKOD
   END    
     
            FETCH NEXT FROM XRIGHT INTO @RBELGEKOD, @RBELGEDETAYKOD, @RURUNGRUP, @RURUNUSTGRUP, @RHACIM  
      END  
      CLOSE XRIGHT  
      DEALLOCATE XRIGHT   
 END  

/***L siparişi boşta kaldı ve H de sepet varsa***/
IF (SELECT COUNT(1)
  FROM #BELGEDETAYLIST BD 
 WHERE (BD.LNGDETAYKOD) NOT IN (SELECT S.LNGBELGEDETAYKOD FROM #SEPETBELGE S) AND BD.TXTDAGITIMYONU = 'L') > 0 
  AND (SELECT COUNT(1) FROM #SEPETLER WHERE TXTSEPETDAGITIMYONU = @HEPSIYONDEGERI AND DBLSEPETHACIM - DBLYUKLENENHACIM > 0) > 0
	BEGIN  
   DECLARE @LBELGEKOD INT, @LBELGEDETAYKOD INT, @LURUNGRUP NVARCHAR(50), @LURUNUSTGRUP NVARCHAR(50), @LHACIM DECIMAL(28,8)  
      DECLARE XLEFT CURSOR FAST_FORWARD FOR SELECT DISTINCT B.LNGKOD, BD.LNGDETAYKOD, BD.TXTURUNGRUP, BD.TXTURUNUSTGRUP, SUM(BD.DBLDETAYHACIM)   
   FROM #BELGELIST B INNER JOIN #BELGEDETAYLIST BD ON BD.LNGBASLIKKOD = B.LNGKOD 
   WHERE (BD.LNGDETAYKOD) NOT IN (SELECT S.LNGBELGEDETAYKOD FROM #SEPETBELGE S) AND BD.TXTDAGITIMYONU = 'R'  
   GROUP BY B.LNGKOD, BD.LNGDETAYKOD, BD.TXTURUNGRUP, BD.TXTURUNUSTGRUP  
   ORDER BY 5 DESC  
      OPEN XLEFT  
      FETCH NEXT FROM XLEFT INTO @LBELGEKOD, @LBELGEDETAYKOD, @LURUNGRUP, @LURUNUSTGRUP, @LHACIM  
      WHILE(@@FETCH_STATUS = 0)  
      BEGIN  
            DECLARE @LGECICISEPET NVARCHAR(50) =  NULL  
            SELECT TOP 1 @LGECICISEPET = S.TXTALTSEPET FROM #SEPETLER S  
   WHERE S.TXTSEPETURUNGRUBU = @LURUNGRUP
     AND S.TXTSEPETDAGITIMYONU  IN ('L', @HEPSIYONDEGERI)
     AND S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @LHACIM  
     ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM ASC, TXTALTSEPET     
     --ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET  ' HOMOJEN DAĞITILACAKSA AÇILACAK   
     
   IF (@LGECICISEPET IS NULL)  
   BEGIN  
      SELECT TOP 1 @LGECICISEPET = S.TXTALTSEPET FROM #SEPETLER S  
   WHERE S.TXTSEPETURUNUSTGRUBU = @LURUNUSTGRUP
     AND S.TXTSEPETDAGITIMYONU  IN ('L', @HEPSIYONDEGERI)
     AND S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @LHACIM  
     ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM ASC, TXTALTSEPET    
     --ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET  ' HOMOJEN DAĞITILACAKSA AÇILACAK   
   END 

   IF (@LGECICISEPET IS NULL)  
   BEGIN  
     SELECT TOP 1 @LGECICISEPET = S.TXTALTSEPET FROM #SEPETLER S  
      WHERE S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @LHACIM  
        AND S.TXTSEPETDAGITIMYONU   IN ('L', @HEPSIYONDEGERI)
     ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM ASC, TXTALTSEPET     
     --ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET  ' HOMOJEN DAĞITILACAKSA AÇILACAK   
   END     
     
   IF (@LGECICISEPET IS NOT NULL)     
   BEGIN  
    INSERT INTO #SEPETBELGE (LNGBELGEKOD, LNGBELGEDETAYKOD, TXTGECICISEPET, LNGURUNKOD, DBLMIKTAR, DBLOLCUBIRIMHACIM, LNGISLEMOLCUBIRIM, TXTURUNGRUP )  
     SELECT @LBELGEKOD, @LBELGEDETAYKOD, @LGECICISEPET, BD.LNGURUNKOD, BD.DBLMIKTAR, BD.DBLISLEMBIRIMHACIM, BD.LNGISLEMOLCUBIRIM  ,@LURUNGRUP
       FROM #BELGEDETAYLIST BD  
         WHERE BD.LNGBASLIKKOD = @LBELGEKOD AND BD.LNGDETAYKOD = @LBELGEDETAYKOD  
  
     UPDATE #SEPETLER  
        SET DBLYUKLENENHACIM = DBLYUKLENENHACIM + @LHACIM,  
         TXTSEPETDAGITIMYONU = 'L',  
      TXTSEPETURUNGRUBU = CASE WHEN TXTSEPETURUNGRUBU IS NULL THEN @LURUNGRUP ELSE TXTSEPETURUNGRUBU END  ,
	  TXTSEPETURUNUSTGRUBU = CASE WHEN TXTSEPETURUNUSTGRUBU IS NULL THEN @LURUNUSTGRUP ELSE TXTSEPETURUNUSTGRUBU END  
      WHERE TXTALTSEPET = @LGECICISEPET 
	  
    UPDATE #BELGEDETAYLIST
         SET DBLKALANMIKTAR = 0
         WHERE LNGDETAYKOD =@LBELGEDETAYKOD AND LNGBASLIKKOD =  @LBELGEKOD
   END  
            FETCH NEXT FROM XLEFT INTO @LBELGEKOD, @LBELGEDETAYKOD, @LURUNGRUP, @LURUNUSTGRUP, @LHACIM  
      END  
      CLOSE XLEFT  
      DEALLOCATE XLEFT   
 END


/*** BELGE DETAY HACMİ SEPETTEN BÜYÜKSE BÖLEREK SONRADAN DAĞIT ***/
DECLARE @BDAGITILAMAYAN INT
SELECT @BDAGITILAMAYAN = COUNT(1) 
  FROM #BELGEDETAYLIST BD 
 WHERE BD.DBLKALANMIKTAR > 0

 IF (@BDAGITILAMAYAN > 0)
 BEGIN    
      DECLARE @BDAGITILMASIGEREKENHACIM DECIMAL(28,8), @BDAGITILMASIGEREKENMIKTAR DECIMAL(28,8),@BDYON NVARCHAR(1), @BDURUNGRUP NVARCHAR(50), @BDURUNUSTGRUP NVARCHAR(50),
	          @BDBELGEKOD INT, @BDBELGEDETAYKOD INT, @BDISLEMBIRIMHACIM DECIMAL(28,8)
      DECLARE XBDAGITILAMAYAN CURSOR FAST_FORWARD FOR SELECT BD.DBLKALANMIKTAR, BD.DBLDETAYHACIM, BD.TXTDAGITIMYONU, BD.TXTURUNGRUP, BD.TXTURUNUSTGRUP, 
	                                                        BD.LNGBASLIKKOD, BD.LNGDETAYKOD , BD.DBLISLEMBIRIMHACIM 
													  FROM #BELGEDETAYLIST BD 
													 WHERE BD.DBLKALANMIKTAR > 0 
      OPEN XBDAGITILAMAYAN
      FETCH NEXT FROM XBDAGITILAMAYAN INTO @BDAGITILMASIGEREKENMIKTAR, @BDAGITILMASIGEREKENHACIM, @BDYON, @BDURUNGRUP, @BDURUNUSTGRUP, @BDBELGEKOD, @BDBELGEDETAYKOD, @BDISLEMBIRIMHACIM
      WHILE(@@FETCH_STATUS = 0)
      BEGIN	   
	    DECLARE @BOSSEPETHACIM DECIMAL(28,8) = 0		
		DECLARE @DSAY INT = 0
        WHILE (@BDAGITILMASIGEREKENMIKTAR > 0 AND @DSAY <= 999)
		  BEGIN
		      SET @DSAY += 1 
			  DECLARE @BDGECICISEPET NVARCHAR(50) =  NULL  
			  SELECT TOP 1 @BDGECICISEPET = S.TXTALTSEPET, 
			         @BOSSEPETHACIM = S.DBLSEPETHACIM - S.DBLYUKLENENHACIM
			    FROM #SEPETLER S  
		       WHERE ( S.TXTSEPETURUNGRUBU = @BDURUNGRUP or S.TXTSEPETURUNGRUBU IS NULL)
			    AND (@BDYON = @HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU =@HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU = @BDYON OR S.TXTSEPETDAGITIMYONU IS NULL)  
			    AND S.DBLSEPETHACIM - S.DBLYUKLENENHACIM > 0
			 ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET  

			IF (@BDGECICISEPET IS NULL)  
		   BEGIN  
			  SELECT TOP 1 @BDGECICISEPET = S.TXTALTSEPET, 
			         @BOSSEPETHACIM = S.DBLSEPETHACIM - S.DBLYUKLENENHACIM
			    FROM #SEPETLER S  
		       WHERE ( S.TXTSEPETURUNUSTGRUBU = @BDURUNUSTGRUP or S.TXTSEPETURUNUSTGRUBU IS NULL)
			    AND (@BDYON = @HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU =@HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU = @BDYON OR S.TXTSEPETDAGITIMYONU IS NULL)  
			    AND S.DBLSEPETHACIM - S.DBLYUKLENENHACIM > 0
			 ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET  
		   END 

		   IF (@BDGECICISEPET IS NULL)  
		   BEGIN  
			 SELECT TOP 1 @BDGECICISEPET = S.TXTALTSEPET, 
			              @BOSSEPETHACIM = S.DBLSEPETHACIM - S.DBLYUKLENENHACIM
			   FROM #SEPETLER S  
			  WHERE S.DBLSEPETHACIM - S.DBLYUKLENENHACIM > 0 
			  AND (@BDYON =@HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU =@HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU = @BDYON OR S.TXTSEPETDAGITIMYONU IS NULL) 
			ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET 
		   END   
		  DECLARE @ATANABILECEKMIKTAR INT = CONVERT(INT,@BOSSEPETHACIM/@BDISLEMBIRIMHACIM)		  
		   DECLARE @GUNCELMIKTAR DECIMAL(28,8) 
		    SELECT @GUNCELMIKTAR = DBLKALANMIKTAR FROM #BELGEDETAYLIST WHERE LNGDETAYKOD = @BDBELGEDETAYKOD AND LNGBASLIKKOD = @BDBELGEKOD
		   IF (@ATANABILECEKMIKTAR  > @GUNCELMIKTAR)
		   BEGIN 
		     SET @ATANABILECEKMIKTAR = @GUNCELMIKTAR
		   END 
          IF @ATANABILECEKMIKTAR <= 0 
		  BEGIN
		    SET @BDGECICISEPET = NULL
		  END
		     IF (@BDGECICISEPET IS NOT NULL)     
			   BEGIN  
				 INSERT INTO #SEPETBELGE (LNGBELGEKOD, LNGBELGEDETAYKOD, TXTGECICISEPET, LNGURUNKOD, DBLMIKTAR, DBLOLCUBIRIMHACIM, LNGISLEMOLCUBIRIM, TXTURUNGRUP, TXTURUNUSTGRUP  )  
				 SELECT @BDBELGEKOD, @BDBELGEDETAYKOD, @BDGECICISEPET, BD.LNGURUNKOD, @ATANABILECEKMIKTAR , BD.DBLISLEMBIRIMHACIM, BD.LNGISLEMOLCUBIRIM  , @BDURUNGRUP, @BDURUNUSTGRUP
				   FROM #BELGEDETAYLIST BD  
					 WHERE BD.LNGBASLIKKOD = @BDBELGEKOD AND BD.LNGDETAYKOD = @BDBELGEDETAYKOD  
  
				 UPDATE #SEPETLER  
					SET DBLYUKLENENHACIM = DBLYUKLENENHACIM + (@ATANABILECEKMIKTAR *@BDISLEMBIRIMHACIM ),  
					 TXTSEPETDAGITIMYONU = CASE WHEN @BDYON <> @HEPSIYONDEGERI AND TXTSEPETDAGITIMYONU =@HEPSIYONDEGERI THEN @BDYON ELSE ISNULL(TXTSEPETDAGITIMYONU,@BDYON) END ,
					 TXTSEPETURUNGRUBU  = CASE WHEN   TXTSEPETURUNGRUBU IS NULL THEN @BDURUNGRUP ELSE TXTSEPETURUNGRUBU END ,
					 TXTSEPETURUNUSTGRUBU  = CASE WHEN   TXTSEPETURUNUSTGRUBU IS NULL THEN @BDURUNUSTGRUP ELSE TXTSEPETURUNUSTGRUBU END 
				  WHERE TXTALTSEPET = @BDGECICISEPET 
				  
				  UPDATE #BELGEDETAYLIST
				    SET DBLKALANMIKTAR = DBLKALANMIKTAR - @ATANABILECEKMIKTAR
					WHERE LNGDETAYKOD = @BDBELGEDETAYKOD AND LNGBASLIKKOD = @BDBELGEKOD
			   END  
            
			SET @BDAGITILMASIGEREKENMIKTAR = @BDAGITILMASIGEREKENMIKTAR - @ATANABILECEKMIKTAR
			END

            FETCH NEXT FROM XBDAGITILAMAYAN INTO @BDAGITILMASIGEREKENMIKTAR, @BDAGITILMASIGEREKENHACIM, @BDYON, @BDURUNGRUP, @BDURUNUSTGRUP, @BDBELGEKOD, @BDBELGEDETAYKOD, @BDISLEMBIRIMHACIM
      END
      CLOSE XBDAGITILAMAYAN
      DEALLOCATE XBDAGITILAMAYAN
 END
  

/*** EN SON OLARAK KALAN BELGELERİ GEZİP BÖLEREK SEPETLERE DAĞITACAK ***/
DECLARE @DAGITILAMAYAN INT
SELECT @DAGITILAMAYAN = COUNT(1) 
  FROM #BELGEDETAYLIST BD 
 WHERE BD.DBLKALANMIKTAR > 0

 IF (@DAGITILAMAYAN > 0)
 BEGIN
   /**** DAĞITILAMAYANLAR BÖLÜNECEK ****/
  
      DECLARE @DAGITILMASIGEREKENMIKTAR DECIMAL(28,8), @BIRBIRIMHACIM DECIMAL(28,8), @DYON NVARCHAR(1), @DURUNGRUP NVARCHAR(50), @DURUNUSTGRUP NVARCHAR(50),
	          @DBELGEKOD INT, @DBELGEDETAYKOD INT
      DECLARE XDAGITILAMAYAN CURSOR FAST_FORWARD FOR SELECT BD.DBLKALANMIKTAR, BD.DBLISLEMBIRIMHACIM, BD.TXTDAGITIMYONU, BD.TXTURUNGRUP, BD.TXTURUNUSTGRUP, 
	                                                        BD.LNGBASLIKKOD, BD.LNGDETAYKOD  
													  FROM #BELGEDETAYLIST BD 
													 WHERE BD.DBLKALANMIKTAR > 0
      OPEN XDAGITILAMAYAN
      FETCH NEXT FROM XDAGITILAMAYAN INTO @DAGITILMASIGEREKENMIKTAR, @BIRBIRIMHACIM, @DYON, @DURUNGRUP, @DURUNUSTGRUP, @DBELGEKOD, @DBELGEDETAYKOD
      WHILE(@@FETCH_STATUS = 0)
      BEGIN	   
        WHILE (@DAGITILMASIGEREKENMIKTAR > 0)
		  BEGIN
			  DECLARE @DGECICISEPET NVARCHAR(50) =  NULL  
			  SELECT TOP 1 @DGECICISEPET = S.TXTALTSEPET FROM #SEPETLER S  
		       WHERE S.TXTSEPETURUNGRUBU = @DURUNGRUP--(S.TXTSEPETURUNGRUBU IS NULL OR S.TXTSEPETURUNGRUBU = @DURUNGRUP)  
			    AND (@DYON = @HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU =@HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU = @DYON)  
			    AND S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @BIRBIRIMHACIM     
			 ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET  

			 IF (@DGECICISEPET IS NULL)  
		   BEGIN  
			  SELECT TOP 1 @DGECICISEPET = S.TXTALTSEPET FROM #SEPETLER S  
		       WHERE S.TXTSEPETURUNUSTGRUBU = @DURUNUSTGRUP--(S.TXTSEPETURUNGRUBU IS NULL OR S.TXTSEPETURUNGRUBU = @DURUNGRUP)  
			    AND (@DYON = @HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU =@HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU = @DYON)  
			    AND S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @BIRBIRIMHACIM     
			 ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET  
		   END     
     

		   IF (@DGECICISEPET IS NULL)  
		   BEGIN  
			 SELECT TOP 1 @DGECICISEPET = S.TXTALTSEPET FROM #SEPETLER S  
			  WHERE S.DBLSEPETHACIM - S.DBLYUKLENENHACIM >= @BIRBIRIMHACIM  
			  AND (@DYON =@HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU =@HEPSIYONDEGERI OR S.TXTSEPETDAGITIMYONU = @DYON) 
			ORDER BY S.DBLSEPETHACIM - S.DBLYUKLENENHACIM DESC, TXTALTSEPET 
		   END     
     
			   IF (@DGECICISEPET IS NOT NULL)     
			   BEGIN  
				 INSERT INTO #SEPETBELGE (LNGBELGEKOD, LNGBELGEDETAYKOD, TXTGECICISEPET, LNGURUNKOD, DBLMIKTAR, DBLOLCUBIRIMHACIM, LNGISLEMOLCUBIRIM, TXTURUNGRUP, TXTURUNUSTGRUP  )  
				 SELECT @DBELGEKOD, @DBELGEDETAYKOD, @DGECICISEPET, BD.LNGURUNKOD, 1, BD.DBLISLEMBIRIMHACIM, BD.LNGISLEMOLCUBIRIM  , @DURUNGRUP, @DURUNUSTGRUP
				   FROM #BELGEDETAYLIST BD  
					 WHERE BD.LNGBASLIKKOD = @DBELGEKOD AND BD.LNGDETAYKOD = @DBELGEDETAYKOD  
  
				 UPDATE #SEPETLER  
					SET DBLYUKLENENHACIM = DBLYUKLENENHACIM + @BIRBIRIMHACIM,  
					 TXTSEPETDAGITIMYONU = CASE WHEN @DYON <> @HEPSIYONDEGERI AND TXTSEPETDAGITIMYONU =@HEPSIYONDEGERI THEN @DYON ELSE ISNULL(TXTSEPETDAGITIMYONU,@DYON) END 
				  WHERE TXTALTSEPET = @DGECICISEPET  

			  UPDATE #BELGEDETAYLIST
				 SET DBLKALANMIKTAR = DBLKALANMIKTAR - 1
				 WHERE LNGDETAYKOD = @DBELGEKOD AND LNGBASLIKKOD = @DBELGEDETAYKOD

			   END  
            
			SET @DAGITILMASIGEREKENMIKTAR = @DAGITILMASIGEREKENMIKTAR - 1
			END

            FETCH NEXT FROM XDAGITILAMAYAN INTO @DAGITILMASIGEREKENMIKTAR, @BIRBIRIMHACIM, @DYON, @DURUNGRUP, @DURUNUSTGRUP, @DBELGEKOD, @DBELGEDETAYKOD
      END
      CLOSE XDAGITILAMAYAN
      DEALLOCATE XDAGITILAMAYAN
 END

  IF (@DEVMODE = 1)
  /**SONUC GÖRME SORGULARI !! **/
 BEGIN
  SELECT * FROM #BELGELIST
  SELECT * FROM #BELGEDETAYLIST
  SELECT *, DBLSEPETHACIM - DBLYUKLENENHACIM KALAN FROM #SEPETLER
  SELECT SUM(DBLDETAYHACIM) BELGEDETAYTOPLAMHACIM FROM #BELGEDETAYLIST
  SELECT SUM(DBLDETAYHACIM) BELGEDETAYTOPLAMHACIM, TXTDAGITIMYONU  FROM #BELGEDETAYLIST GROUP BY TXTDAGITIMYONU 
  SELECT SUM (DBLYUKLENENHACIM) TOPLAMTUKLENENHACIM FROM #SEPETLER
  SELECT * FROM #SEPETBELGE order BY TXTGECICISEPET 
  --SELECT * FROM TBLSBSEPETDAGITIMBASLIK   
  --SELECT * FROM TBLSBSEPETDAGITIMDETAY
  END

 IF (@DEVMODE = 1)
  BEGIN
	  SELECT * 
	  FROM #BELGEDETAYLIST BD 
	 WHERE (BD.LNGDETAYKOD) NOT IN (SELECT S.LNGBELGEDETAYKOD FROM #SEPETBELGE S)

	 SELECT * FROM (
	 SELECT BD.LNGBASLIKKOD, BD.LNGDETAYKOD, BD.LNGURUNKOD, SUM(BD.DBLMIKTAR) TOPLAMBELGEDETAYMIKTAR, 
	  (SELECT SUM(S.DBLMIKTAR) FROM #SEPETBELGE S WHERE S.LNGBELGEDETAYKOD = BD.LNGDETAYKOD AND S.LNGBELGEKOD = BD.LNGBASLIKKOD AND S.LNGURUNKOD = BD.LNGURUNKOD ) DAGITILANBELGEDETAYMIKTAR
	   FROM #BELGEDETAYLIST BD 
	   GROUP BY BD.LNGBASLIKKOD, BD.LNGDETAYKOD, BD.LNGURUNKOD) AA
  END

  IF (SELECT COUNT(1) FROM #BELGEDETAYLIST WHERE DBLKALANMIKTAR > 0 ) > 0        
	   BEGIN
	     DECLARE @DAGITILAMAYANURUN NVARCHAR(150), @DAGITILAMAYANHACIM DECIMAL(28,8), @DAGITILAMAYANBELGE NVARCHAR(50)
		 SELECT TOP 1 @DAGITILAMAYANBELGE = BB.TXTKOD , @DAGITILAMAYANURUN = U.TXTKOD, @DAGITILAMAYANHACIM= DBLKALANMIKTAR
           FROM (
		 SELECT BD.LNGBASLIKKOD, BD.LNGDETAYKOD, BD.LNGURUNKOD, DBLKALANMIKTAR
		   FROM #BELGEDETAYLIST BD 
		    WHERE DBLKALANMIKTAR > 0 ) AA 
		   INNER JOIN TBLSBBELGEBASLIK BB ON BB.LNGKOD = AA.LNGBASLIKKOD 
		   INNER JOIN TBLURUN U ON U.LNGKOD = AA.LNGURUNKOD  		   
		   DECLARE @MSJ3 NVARCHAR(500) ='Tüm detaylar dağıtılamadığı için dağıtım yapılamamıştır. Belge : ' + @DAGITILAMAYANBELGE + ', Ürün : '+ @DAGITILAMAYANURUN + ', Dağıtılamayan Miktar : ' +  CONVERT(NVARCHAR,@DAGITILAMAYANHACIM)
	       RAISERROR(@MSJ3,16,1)
           RETURN
	   END

/*DAĞITIM TABLOLARINA KAYIT ATILIYOR*/
  DECLARE @DSIRA INT
  SELECT @DSIRA = ISNULL(MAX(LNGDAGITIMNO),0) FROM TBLSBSEPETDAGITIMBASLIK
  DECLARE @DPLAKA AS NVARCHAR(50)
      DECLARE XDAGITIM CURSOR FAST_FORWARD FOR SELECT DISTINCT TXTPLAKA FROM #SEPETLER
      OPEN XDAGITIM
      FETCH NEXT FROM XDAGITIM INTO @DPLAKA
      WHILE(@@FETCH_STATUS = 0)
      BEGIN
            SET @DSIRA = @DSIRA +1
 IF(@DEVMODE = 0)
 BEGIN
          INSERT INTO TBLSBSEPETDAGITIMBASLIK
			(LNGDAGITIMNO, LNGARACKOD, TXTPLAKA, TXTGECICISEPETKAPAK, TXTDAGITIMYONU, TRHILKISLEMTARIHI, LNGILKKULLANICIKOD) 
		    SELECT @DSIRA LNGDAGITIMNO, A.LNGKOD LNGARACKOD, @DPLAKA TXTPLAKA, S.TXTALTSEPET TXTGECICISEPETKAPAK, S.TXTSEPETDAGITIMYONU TXTDAGITIMYONU, 
			GETDATE() TRHILKISLEMTARIHI, 1 LNGILKKULLANICIKOD
			  FROM #SEPETLER S
		INNER JOIN TBLSBARAC A (NOLOCK) ON A.TXTPLAKA = S.TXTPLAKA AND A.LNGDISTKOD = @LNGDISTKOD
			 WHERE S.TXTPLAKA = @DPLAKA
			  
			INSERT INTO TBLSBSEPETDAGITIMDETAY
			(LNGSEPETBASLIKKOD, LNGBELGEBASLIKKOD, LNGBELGEDETAYKOD, LNGMALZEMEKOD, DBLMIKTAR, LNGBIRIMKOD, DBLTOPLANANMIKTAR, TRHILKISLEMTARIHI, LNGILKKULLANICIKOD)
		   SELECT LNGSEPETBASLIKKOD,  LNGBELGEBASLIKKOD,  LNGBELGEDETAYKOD, 
			        LNGMALZEMEKOD, SUM(DBLMIKTAR) DBLMIKTAR, LNGBIRIMKOD, DBLTOPLANANMIKTAR , 
				    TRHILKISLEMTARIHI, LNGILKKULLANICIKOD FROM (
			 SELECT DB.LNGKOD LNGSEPETBASLIKKOD, SB.LNGBELGEKOD LNGBELGEBASLIKKOD, SB.LNGBELGEDETAYKOD LNGBELGEDETAYKOD, 
			       SB.LNGURUNKOD LNGMALZEMEKOD, ((SB.DBLMIKTAR*UOB.DBLCARPAN)/UOB.DBLBOLEN) DBLMIKTAR, (SELECT UOB2.LNGBIRIMKOD 
				   FROM TBLSBURUNOLCUBIRIM UOB2 (NOLOCK) WHERE UOB2.LNGURUNKOD =SB.LNGURUNKOD AND UOB2.BYTANAOLCUBIRIMI = 1 ) LNGBIRIMKOD, 0 DBLTOPLANANMIKTAR , 
				   GETDATE() TRHILKISLEMTARIHI, 1 LNGILKKULLANICIKOD, SB.TXTGECICISEPET
			  FROM #SEPETLER S
		INNER JOIN #SEPETBELGE SB ON SB.TXTGECICISEPET = S.TXTALTSEPET
		LEFT OUTER JOIN TBLSBSEPETDAGITIMBASLIK DB (NOLOCK) ON DB.LNGDAGITIMNO = @DSIRA AND DB.TXTGECICISEPETKAPAK = SB.TXTGECICISEPET
		INNER JOIN TBLSBURUNOLCUBIRIM UOB(NOLOCK) ON UOB.LNGBIRIMKOD = SB.LNGISLEMOLCUBIRIM AND UOB.LNGURUNKOD = SB.LNGURUNKOD 
			 WHERE S.TXTPLAKA = @DPLAKA ) AA
			 GROUP BY LNGSEPETBASLIKKOD,  LNGBELGEBASLIKKOD,  LNGBELGEDETAYKOD, 
			        LNGMALZEMEKOD, LNGBIRIMKOD, DBLTOPLANANMIKTAR , 
				    TRHILKISLEMTARIHI, LNGILKKULLANICIKOD, TXTGECICISEPET
END
ELSE
BEGIN
           SELECT @DSIRA LNGDAGITIMNO, A.LNGKOD LNGARACKOD, @DPLAKA TXTPLAKA, S.TXTALTSEPET TXTGECICISEPETKAPAK, S.TXTSEPETDAGITIMYONU TXTDAGITIMYONU, 
			GETDATE() TRHILKISLEMTARIHI, 1 LNGILKKULLANICIKOD
			  FROM #SEPETLER S
		INNER JOIN TBLSBARAC A (NOLOCK) ON A.TXTPLAKA = S.TXTPLAKA AND A.LNGDISTKOD = @LNGDISTKOD
			 WHERE S.TXTPLAKA = @DPLAKA
			 
			 SELECT LNGSEPETBASLIKKOD,  LNGBELGEBASLIKKOD,  LNGBELGEDETAYKOD, 
			        LNGMALZEMEKOD, SUM(DBLMIKTAR) DBLMIKTAR, LNGBIRIMKOD, DBLTOPLANANMIKTAR , 
				    TRHILKISLEMTARIHI, LNGILKKULLANICIKOD FROM (
			 SELECT DB.LNGKOD LNGSEPETBASLIKKOD, SB.LNGBELGEKOD LNGBELGEBASLIKKOD, SB.LNGBELGEDETAYKOD LNGBELGEDETAYKOD, 
			       SB.LNGURUNKOD LNGMALZEMEKOD, ((SB.DBLMIKTAR*UOB.DBLCARPAN)/UOB.DBLBOLEN) DBLMIKTAR, (SELECT UOB2.LNGBIRIMKOD 
				   FROM TBLSBURUNOLCUBIRIM UOB2 (NOLOCK) WHERE UOB2.LNGURUNKOD =SB.LNGURUNKOD AND UOB2.BYTANAOLCUBIRIMI = 1 ) LNGBIRIMKOD, 0 DBLTOPLANANMIKTAR , 
				   GETDATE() TRHILKISLEMTARIHI, 1 LNGILKKULLANICIKOD, SB.TXTGECICISEPET
			  FROM #SEPETLER S
		INNER JOIN #SEPETBELGE SB ON SB.TXTGECICISEPET = S.TXTALTSEPET
		LEFT OUTER JOIN TBLSBSEPETDAGITIMBASLIK DB (NOLOCK) ON DB.LNGDAGITIMNO = @DSIRA AND DB.TXTGECICISEPETKAPAK = SB.TXTGECICISEPET
		INNER JOIN TBLSBURUNOLCUBIRIM UOB(NOLOCK) ON UOB.LNGBIRIMKOD = SB.LNGISLEMOLCUBIRIM AND UOB.LNGURUNKOD = SB.LNGURUNKOD 
			 WHERE S.TXTPLAKA = @DPLAKA ) AA
			 GROUP BY LNGSEPETBASLIKKOD,  LNGBELGEBASLIKKOD,  LNGBELGEDETAYKOD, 
			        LNGMALZEMEKOD, LNGBIRIMKOD, DBLTOPLANANMIKTAR , 
				    TRHILKISLEMTARIHI, LNGILKKULLANICIKOD, TXTGECICISEPET
END
            FETCH NEXT FROM XDAGITIM INTO @DPLAKA
      END
      CLOSE XDAGITIM
      DEALLOCATE XDAGITIM
	  
FETCH NEXT FROM XPLAKA INTO @DONULECEKPLAKA
      END
      CLOSE XPLAKA
      DEALLOCATE XPLAKA

END


