-- AlterTable
ALTER TABLE "TBLBUSINESSPARTNER" ADD COLUMN     "parentId" INTEGER,
ADD COLUMN     "partnerGroupId" INTEGER,
ADD COLUMN     "regionId" INTEGER;

-- AlterTable
ALTER TABLE "TBLWAREHOUSE" ADD COLUMN     "facilityId" INTEGER;

-- CreateTable
CREATE TABLE "TBLFACILITY" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "city" VARCHAR(60),
    "address" VARCHAR(255),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLFACILITY_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLPRODUCTUNITBARCODE" (
    "id" SERIAL NOT NULL,
    "productUnitId" INTEGER NOT NULL,
    "barcode" VARCHAR(100) NOT NULL,
    "labelAddress" VARCHAR(100),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLPRODUCTUNITBARCODE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLREGION" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(60) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLREGION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLPARTNERGROUP" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(60) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLPARTNERGROUP_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLFACILITY_companyId_idx" ON "TBLFACILITY"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLFACILITY_companyId_code_key" ON "TBLFACILITY"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLPRODUCTUNITBARCODE_productUnitId_idx" ON "TBLPRODUCTUNITBARCODE"("productUnitId");

-- CreateIndex
CREATE INDEX "TBLPRODUCTUNITBARCODE_barcode_idx" ON "TBLPRODUCTUNITBARCODE"("barcode");

-- CreateIndex
CREATE INDEX "TBLREGION_companyId_idx" ON "TBLREGION"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLREGION_companyId_code_key" ON "TBLREGION"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLPARTNERGROUP_companyId_idx" ON "TBLPARTNERGROUP"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "TBLPARTNERGROUP_companyId_code_key" ON "TBLPARTNERGROUP"("companyId", "code");

-- CreateIndex
CREATE INDEX "TBLBUSINESSPARTNER_regionId_idx" ON "TBLBUSINESSPARTNER"("regionId");

-- CreateIndex
CREATE INDEX "TBLBUSINESSPARTNER_partnerGroupId_idx" ON "TBLBUSINESSPARTNER"("partnerGroupId");

-- CreateIndex
CREATE INDEX "TBLBUSINESSPARTNER_parentId_idx" ON "TBLBUSINESSPARTNER"("parentId");

-- CreateIndex
CREATE INDEX "TBLWAREHOUSE_facilityId_idx" ON "TBLWAREHOUSE"("facilityId");

-- AddForeignKey
ALTER TABLE "TBLWAREHOUSE" ADD CONSTRAINT "TBLWAREHOUSE_facilityId_fkey" FOREIGN KEY ("facilityId") REFERENCES "TBLFACILITY"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLBUSINESSPARTNER" ADD CONSTRAINT "TBLBUSINESSPARTNER_regionId_fkey" FOREIGN KEY ("regionId") REFERENCES "TBLREGION"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLBUSINESSPARTNER" ADD CONSTRAINT "TBLBUSINESSPARTNER_partnerGroupId_fkey" FOREIGN KEY ("partnerGroupId") REFERENCES "TBLPARTNERGROUP"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLBUSINESSPARTNER" ADD CONSTRAINT "TBLBUSINESSPARTNER_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "TBLBUSINESSPARTNER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLFACILITY" ADD CONSTRAINT "TBLFACILITY_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPRODUCTUNITBARCODE" ADD CONSTRAINT "TBLPRODUCTUNITBARCODE_productUnitId_fkey" FOREIGN KEY ("productUnitId") REFERENCES "TBLPRODUCTUNIT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLREGION" ADD CONSTRAINT "TBLREGION_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPARTNERGROUP" ADD CONSTRAINT "TBLPARTNERGROUP_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "TBLCOMPANY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

