-- AlterTable
ALTER TABLE "TBLDOCUMENT" ADD COLUMN     "reasonId" INTEGER;

-- AlterTable
ALTER TABLE "TBLOPERATIONTYPE" ADD COLUMN     "operationGroupId" INTEGER,
ADD COLUMN     "sequenceId" INTEGER;

-- AlterTable
ALTER TABLE "TBLPALLETTYPE" ADD COLUMN     "sequenceId" INTEGER;

-- AlterTable
ALTER TABLE "TBLPRODUCT" ADD COLUMN     "productSubGroupId" INTEGER;

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPE_sequenceId_idx" ON "TBLOPERATIONTYPE"("sequenceId");

-- CreateIndex
CREATE INDEX "TBLOPERATIONTYPE_operationGroupId_idx" ON "TBLOPERATIONTYPE"("operationGroupId");

-- CreateIndex
CREATE INDEX "TBLPALLETTYPE_sequenceId_idx" ON "TBLPALLETTYPE"("sequenceId");

-- CreateIndex
CREATE INDEX "TBLPRODUCT_productSubGroupId_idx" ON "TBLPRODUCT"("productSubGroupId");

-- AddForeignKey
ALTER TABLE "TBLPRODUCT" ADD CONSTRAINT "TBLPRODUCT_productSubGroupId_fkey" FOREIGN KEY ("productSubGroupId") REFERENCES "TBLPRODUCTSUBGROUP"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPALLETTYPE" ADD CONSTRAINT "TBLPALLETTYPE_sequenceId_fkey" FOREIGN KEY ("sequenceId") REFERENCES "TBLSEQUENCE"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLOPERATIONTYPE" ADD CONSTRAINT "TBLOPERATIONTYPE_sequenceId_fkey" FOREIGN KEY ("sequenceId") REFERENCES "TBLSEQUENCE"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLOPERATIONTYPE" ADD CONSTRAINT "TBLOPERATIONTYPE_operationGroupId_fkey" FOREIGN KEY ("operationGroupId") REFERENCES "TBLOPERATIONGROUP"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENT" ADD CONSTRAINT "TBLDOCUMENT_reasonId_fkey" FOREIGN KEY ("reasonId") REFERENCES "TBLREASON"("id") ON DELETE SET NULL ON UPDATE CASCADE;

