
-- DropForeignKey
ALTER TABLE "TBLPRODUCT" DROP CONSTRAINT "TBLPRODUCT_unitId_fkey";

-- AlterTable
ALTER TABLE "TBLPRODUCT" ALTER COLUMN "unitId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "TBLPRODUCT" ADD CONSTRAINT "TBLPRODUCT_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "TBLUNIT"("id") ON DELETE SET NULL ON UPDATE CASCADE;

