-- Entegrasyon Aktarım altyapısı (legacy TBLSBTRANSACTIONLOGGELEN/GIDEN + TBLSBENTEGRASYONPAKET parite)
-- Paket: Logo versiyonu + çoklu firma aktarımı (BYTLOGOVERSIYON / BYTCOKLUFIRMAAKTARIMI)
ALTER TABLE wms."TBLINTEGRATIONPACKAGE"
  ADD COLUMN "logoVersion" SMALLINT,
  ADD COLUMN "multiCompanyTransfer" BOOLEAN NOT NULL DEFAULT false;

-- Log: paket/adres/belge/kullanıcı bağları + istek-yanıt gövdesi (TXTXMLTEXT karşılığı)
ALTER TABLE wms."TBLINTEGRATIONLOG"
  ADD COLUMN "packageId" INTEGER,
  ADD COLUMN "addressId" INTEGER,
  ADD COLUMN "documentId" INTEGER,
  ADD COLUMN "createdById" INTEGER,
  ADD COLUMN "payload" TEXT;

ALTER TABLE wms."TBLINTEGRATIONLOG"
  ADD CONSTRAINT "TBLINTEGRATIONLOG_packageId_fkey" FOREIGN KEY ("packageId")
    REFERENCES wms."TBLINTEGRATIONPACKAGE"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT "TBLINTEGRATIONLOG_addressId_fkey" FOREIGN KEY ("addressId")
    REFERENCES wms."TBLINTEGRATIONADDRESS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX "TBLINTEGRATIONLOG_packageId_idx" ON wms."TBLINTEGRATIONLOG"("packageId");
CREATE INDEX "TBLINTEGRATIONLOG_status_idx" ON wms."TBLINTEGRATIONLOG"("status");
