// Paylaşılan alan meta'sı — FK alan adı → kaynak (id çözümü) + Türkçe etiket.
// GenericList ve GenericDetail birlikte kullanır (tek kaynak, drift yok).

// FK alan adı → API kaynağı: ham id yerine ilgili tablodan "kod — ad" göster (formConfig olmasa da)
export const FK_RESOURCE: Record<string, string> = {
  operationTypeId: 'operation-types', reverseOperationTypeId: 'operation-types', linkedEntryOperationTypeId: 'operation-types',
  sourceOperationTypeId: 'operation-types', targetOperationTypeId: 'operation-types',
  entryOperationTypeId: 'operation-types', exitOperationTypeId: 'operation-types', transferOperationTypeId: 'operation-types',
  firstOperationId: 'operation-types', secondOperationId: 'operation-types',
  warehouseId: 'warehouses', areaId: 'areas',
  locationId: 'locations', sourceLocationId: 'locations', targetLocationId: 'locations',
  cancelLocationId: 'locations', sourceLocLinkId: 'locations', targetLocLinkId: 'locations', locationLinkId: 'locations',
  reasonId: 'reasons', reasonCategoryId: 'reason-categories',
  partnerId: 'partners', businessPartnerId: 'partners', cariLinkId: 'partners', sourcePartnerId: 'partners', targetPartnerId: 'partners',
  productId: 'products', materialLinkId: 'products',
  unitId: 'units', toleranceUnitId: 'units', dimensionUnitId: 'units', weightUnitId: 'units',
  statusId: 'statuses', sourceStatusId: 'statuses', targetStatusId: 'statuses',
  documentStatusId: 'document-statuses',
  palletTypeId: 'pallet-types', innerPalletTypeId: 'pallet-types',
  palletId: 'pallets', parentPalletId: 'pallets',
  customerId: 'partners', supplierId: 'partners',
  assignedToUserId: 'users', assignedUserId: 'users',
  vehicleId: 'vehicles', salesOrderId: 'sales-orders', purchaseOrderId: 'purchase-orders',
  operationGroupId: 'operation-groups',
  sequenceId: 'sequences', operationSequenceId: 'sequences', groupSequenceId: 'sequences',
  facilityId: 'facilities', sourceFacilityId: 'facilities', targetFacilityId: 'facilities', regionId: 'regions',
  userId: 'users', createdById: 'users',
  documentId: 'documents', referenceDocumentId: 'documents', extraFieldId: 'extra-fields',
  productGroupId: 'product-groups', productSubGroupId: 'product-subgroups',
  productTypeId: 'product-types', detailTypeId: 'product-detail-types',
  labelTypeId: 'label-types', barcodeTypeId: 'barcode-types',
  stockCountId: 'stock-counts', countId: 'stock-counts',
  baseUnitId: 'units', productUnitId: 'product-units',
  entryConditionTypeId: 'entry-condition-types', exitConditionTypeId: 'exit-condition-types',
  locationGroupId: 'location-groups', partnerGroupId: 'partner-groups', routingTypeId: 'routing-types',
  workOrderId: 'work-orders', shipmentId: 'shipments', invoiceId: 'invoices',
  labelTemplateId: 'label-templates', reportId: 'report-defs',
}

// FK alan adı → Türkçe etiket
export const FK_LABEL: Record<string, string> = {
  operationTypeId: 'Operasyon Tipi', warehouseId: 'Depo', areaId: 'Alan',
  locationId: 'Lokasyon', sourceLocationId: 'Kaynak Lokasyon', targetLocationId: 'Hedef Lokasyon',
  reasonId: 'Neden', reasonCategoryId: 'Neden Kategori', partnerId: 'Cari', businessPartnerId: 'Cari',
  productId: 'Ürün', unitId: 'Birim', statusId: 'Statü', sourceStatusId: 'Kaynak Statü', targetStatusId: 'Hedef Statü',
  documentStatusId: 'Belge Durumu',
  palletTypeId: 'Palet Tipi', innerPalletTypeId: 'İç Palet Tipi', operationGroupId: 'Operasyon Grubu',
  sequenceId: 'Sayaç', facilityId: 'Tesis', sourceFacilityId: 'Kaynak Tesis', targetFacilityId: 'Hedef Tesis',
  sourceOperationTypeId: 'Kaynak Operasyon', targetOperationTypeId: 'Hedef Operasyon',
  regionId: 'Bölge', userId: 'Kullanıcı', createdById: 'Oluşturan',
  documentId: 'Belge', referenceDocumentId: 'Referans Belge', linkedEntryOperationTypeId: 'Bağlı Giriş Operasyonu',
  parentId: 'Üst', extraFieldId: 'Ek Saha', productGroupId: 'Ürün Grubu',
  productSubGroupId: 'Alt Grup', productTypeId: 'Ürün Tipi', detailTypeId: 'Detay Tipi',
  // FK değil ama paylaşılan etiket (kod alanları — FK_RESOURCE'da yok, id çözümü denenmez)
  productGroupCode: 'Grup Kodu', manufacturerCode: 'Üretici Kodu',
  palletId: 'Palet', parentPalletId: 'Üst Palet', customerId: 'Müşteri', supplierId: 'Tedarikçi',
  assignedToUserId: 'Atanan', assignedUserId: 'Atanan', vehicleId: 'Araç',
  salesOrderId: 'Satış Sip.', purchaseOrderId: 'Satınalma Sip.', stockCountId: 'Sayım', countId: 'Sayım',
  baseUnitId: 'Ana Birim', productUnitId: 'Ürün Birimi',
  entryConditionTypeId: 'Giriş Koşul Tipi', exitConditionTypeId: 'Çıkış Koşul Tipi',
  locationGroupId: 'Lokasyon Grubu', partnerGroupId: 'Cari Grubu', routingTypeId: 'Yönlendirme Tipi',
  workOrderId: 'İş Emri', shipmentId: 'Sevkiyat', invoiceId: 'Fatura',
  labelTemplateId: 'Etiket Şablonu', reportId: 'Rapor',
}
