// Hangi kaynakların create/edit formu var + alanları (API create şemalarına birebir)
export interface FieldDef {
  name: string
  label: string
  type?: 'text' | 'number' | 'bool' | 'select' | 'ref' | 'color'
  required?: boolean
  options?: { value: string; label: string }[]
  refResource?: string // type 'ref' için seçenekleri buradan çeker
}

// Bağlantı kapsamı (LinkScope) — Hepsi/Grup/Belirli
export const SCOPE_OPTS = [{ value: 'ALL', label: 'Hepsi' }, { value: 'GROUP', label: 'Grup' }, { value: 'SPECIFIC', label: 'Belirli' }]

const codeName = (codeLabel = 'Kod', nameLabel = 'Ad'): FieldDef[] => [
  { name: 'code', label: codeLabel, type: 'text', required: true },
  { name: 'name', label: nameLabel, type: 'text', required: true },
  { name: 'isActive', label: 'Aktif', type: 'bool' },
]

export const FORM_CONFIG: Record<string, FieldDef[]> = {
  'document-statuses': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Tanım', type: 'text' },
    { name: 'color', label: 'Renk', type: 'color' },
    { name: 'sortOrder', label: 'Sıra', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  // ── Giriş Koşulları ──
  'entry-condition-break-passwords': [
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'password', label: 'Şifre', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'entry-condition-break-reasons': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'entry-condition-type-operations': [
    { name: 'entryConditionTypeId', label: 'Giriş Koşul Tipi', type: 'ref', required: true, refResource: 'entry-condition-types' },
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  // ── Çıkış Koşulları ──
  'exit-condition-control-fields': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'tableName', label: 'Tablo Adı', type: 'text' },
    { name: 'fieldName', label: 'Saha Adı', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'exit-condition-break-passwords': [
    { name: 'password', label: 'Şifre', type: 'text' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'exit-condition-break-reasons': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'exit-condition-type-operations': [
    { name: 'exitConditionTypeId', label: 'Çıkış Koşul Tipi', type: 'ref', required: true, refResource: 'exit-condition-types' },
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'locationLinkType', label: 'Lokasyon Bağ. Tipi', type: 'number' },
    { name: 'locationId', label: 'Lokasyon Kodu', type: 'number' },
    { name: 'fifoCheckOnReverseScan', label: 'Geri Okutmada FIFO Kontrolü', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  // ── Yönlendirme ──
  'routing-control-fields': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'fieldName', label: 'Saha Adı', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'routing-break-passwords': [
    { name: 'password', label: 'Şifre', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'routing-break-reasons': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'routing-type-operations': [
    { name: 'routingTypeId', label: 'Yönlendirme Tipi', type: 'ref', required: true, refResource: 'routing-types' },
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'locationLinkType', label: 'Lokasyon Bağ. Tipi', type: 'number' },
    { name: 'locationId', label: 'Lokasyon Kodu', type: 'number' },
    { name: 'taskPlanId', label: 'Görev Plan Kodu', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'routing-product-locations': [
    { name: 'materialLinkType', label: 'Malzeme Bağ. Tipi', type: 'number' },
    { name: 'additionalGroupOrder', label: 'Ek Grup Sırası', type: 'number' },
    { name: 'materialLinkId', label: 'Malzeme Bağ. Kodu', type: 'number' },
    { name: 'locationLinkType', label: 'Lokasyon Bağ. Tipi', type: 'number' },
    { name: 'locationLinkId', label: 'Lokasyon Bağ. Kodu', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  // ── Sayım ──
  'count-approval-user-groups': [
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'userGroupId', label: 'Kullanıcı Grup Kodu', type: 'number', required: true },
    { name: 'sortOrder', label: 'Sıra', type: 'number' },
    { name: 'mailTemplateId', label: 'Mail Şablon', type: 'number' },
    { name: 'mailGroupId', label: 'Mail Grubu', type: 'number' },
    { name: 'mailSp', label: 'Mail SP', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'count-criteria': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'fieldCode', label: 'Saha Kodu', type: 'text', required: true },
    { name: 'required', label: 'Zorunlu', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'count-parameters': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'countType', label: 'Sayım Tipi', type: 'number' },
    { name: 'entryOperationTypeId', label: 'Giriş Operasyon', type: 'ref', refResource: 'operation-types' },
    { name: 'exitOperationTypeId', label: 'Çıkış Operasyon', type: 'ref', refResource: 'operation-types' },
    { name: 'transferOperationTypeId', label: 'Transfer Operasyon', type: 'ref', refResource: 'operation-types' },
    { name: 'documentDetailCount', label: 'Belge Detay Sayısı', type: 'number' },
    { name: 'countDays', label: 'Sayım Gün Sayısı', type: 'number' },
    { name: 'equalize', label: 'Eşitleme Yapılsın', type: 'bool' },
    { name: 'weightDiff', label: 'Ağırlık Farkı Alınsın', type: 'bool' },
    { name: 'palletQtyPartialEntry', label: 'Palet Miktarı Parçalı Giriş', type: 'bool' },
    { name: 'stacked', label: 'Miktar Girişi İstifli', type: 'bool' },
    { name: 'partialPallet', label: 'Parçalı Palet Kullanımı', type: 'bool' },
    { name: 'partialPalletWarning', label: 'Parçalı Palet Uyarısı', type: 'bool' },
    { name: 'stockMoveOnActiveCount', label: 'Aktif Sayımda Stok Hareketi', type: 'bool' },
    { name: 'hideInnerPallets', label: 'İç Paletler Gösterilmesin', type: 'bool' },
    { name: 'hideMixedPallet', label: 'Karma Palet Gösterilmesin', type: 'bool' },
    { name: 'innerPalletCountCheck', label: 'Palet İçi Sayı Kontrolü', type: 'bool' },
    { name: 'hideInnerPalletStock', label: 'Palet İçi Stok Gösterilmesin', type: 'bool' },
    { name: 'dontRecountPallet', label: 'Palet Tekrar Sayılmasın', type: 'bool' },
    { name: 'askLocationOnScan', label: 'Okutmada Lokasyon Sorulsun', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  // ── Genel ek · İş Emri · Dinamik Etiketleme (StokBar) ──
  languages: [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'isDefault', label: 'Varsayılan', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  shifts: [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Tanım', type: 'text' },
    { name: 'startTime', label: 'Başlangıç (ISO)', type: 'text' },
    { name: 'endTime', label: 'Bitiş (ISO)', type: 'text' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'screen-report-links': [
    { name: 'screenButtonCode', label: 'Ekran Buton Kodu', type: 'text' },
    { name: 'reportCode', label: 'Rapor Kodu', type: 'text' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'stock-control-parameters': [
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'distributionType', label: 'Dağıtım Şekli', type: 'number' },
    { name: 'customerPriority', label: 'Müşteri Önceliği', type: 'number' },
    { name: 'shipmentPriority', label: 'Sevkiyat Önceliği', type: 'number' },
    { name: 'controlStatus', label: 'Kontrol Statü', type: 'text' },
    { name: 'controlLocation', label: 'Kontrol Lokasyon', type: 'text' },
    { name: 'askUser', label: 'Kullanıcıya Sorulsun', type: 'bool' },
    { name: 'dontUpdatePreparedQty', label: 'Hazırlanan Miktar Güncellenmesin', type: 'bool' },
    { name: 'errorOnAllSplit', label: 'Tümünü Bölmede Hata', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'document-planning-parameters': [
    { name: 'plannedDocStatusId', label: 'Planlanacak Belge Durumu', type: 'ref', refResource: 'document-statuses' },
    { name: 'planningOperationTypeId', label: 'Planlama Operasyonu', type: 'ref', refResource: 'operation-types' },
    { name: 'templateOperationTypeId', label: 'Şablon Operasyon', type: 'ref', refResource: 'operation-types' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'partCount', label: 'Parça Sayısı', type: 'number' },
    { name: 'splitByProductGroup', label: 'Ürün Grup Bazında Parçalansın', type: 'bool' },
    { name: 'fieldEntry', label: 'Alan Girişi Yapılsın', type: 'bool' },
    { name: 'updateMainQty', label: 'Ana Miktar Güncellensin', type: 'bool' },
    { name: 'locationAssign', label: 'Lokasyon Atama', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'pick-order-parameters': [
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'fullPalletOpId', label: 'Tam Palet Operasyonu', type: 'ref', refResource: 'operation-types' },
    { name: 'fullCaseOpId', label: 'Tam Koli Operasyonu', type: 'ref', refResource: 'operation-types' },
    { name: 'partialProductOpId', label: 'Parçalı Ürün Operasyonu', type: 'ref', refResource: 'operation-types' },
    { name: 'fullPalletUnitId', label: 'Tam Palet Birimi', type: 'ref', refResource: 'units' },
    { name: 'fullCaseUnitId', label: 'Tam Koli Birimi', type: 'ref', refResource: 'units' },
    { name: 'partialProductUnitId', label: 'Parçalı Ürün Birimi', type: 'ref', refResource: 'units' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'dashboard-reports': [
    { name: 'reportName', label: 'Rapor Tanım', type: 'text' },
    { name: 'reportSp', label: 'Rapor SP', type: 'text' },
    { name: 'type', label: 'Tip', type: 'number' },
    { name: 'defaultReport', label: 'Varsayılan Rapor', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'warehouse-vehicles': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Tanım', type: 'text' },
    { name: 'status', label: 'Durum', type: 'number' },
    { name: 'workType', label: 'İş Tipi', type: 'number' },
    { name: 'quantity', label: 'Miktar', type: 'number' },
    { name: 'unitId', label: 'Birim', type: 'ref', refResource: 'units' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'ipAddress', label: 'IP Adresi', type: 'text' },
    { name: 'pallet', label: 'Palet', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'work-order-general-parameters': [
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'alarmDuration', label: 'Alarm Süresi', type: 'number' },
    { name: 'alarmUnit', label: 'Alarm Süre Birimi', type: 'number' },
    { name: 'pickCancelOpId', label: 'Toplama İptal Operasyonu', type: 'ref', refResource: 'operation-types' },
    { name: 'rackFeedbackOpId', label: 'Raf Geri Besleme Operasyonu', type: 'ref', refResource: 'operation-types' },
    { name: 'askEntryLocation', label: 'Giriş Lokasyon Sorsun', type: 'bool' },
    { name: 'locationPriority', label: 'Lokasyon Önceliği', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'work-order-reasons': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'description', label: 'Açıklama', type: 'text' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'breakPassword', label: 'Kırma Şifresi', type: 'text' },
    { name: 'isCancel', label: 'İptal', type: 'bool' },
    { name: 'autoCreateOrder', label: 'Oto Emir Yarat', type: 'bool' },
    { name: 'createDocument', label: 'Belge Yarat', type: 'bool' },
    { name: 'clearSystemFault', label: 'Sistem Arızası Temizlensin', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'work-order-reference-operations': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'category', label: 'Kategori', type: 'number' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'headerId', label: 'Başlık Kodu', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'rack-feed-parameters': [
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'locationGroupId', label: 'Lokasyon Grubu', type: 'ref', refResource: 'location-groups' },
    { name: 'capacityPercent', label: 'Kapasite Yüzdesi', type: 'number' },
    { name: 'onStockEmpty', label: 'Stok Bitince', type: 'bool' },
    { name: 'palletBreaking', label: 'Palet Bozma', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'menu-groups': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'description', label: 'Açıklama', type: 'text' },
    { name: 'screenType', label: 'Ekran Tipi', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  // ── Operasyon config (StokBar) ──
  'reason-categories': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Tanım', type: 'text' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'operation-group-links': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'operationGroupId', label: 'Operasyon Grubu', type: 'ref', required: true, refResource: 'operation-groups' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'operation-tolerances': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', refResource: 'operation-types' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'cariLinkType', label: 'Cari Bağ. Tipi', type: 'number' },
    { name: 'cariLinkId', label: 'Cari Bağ. Kodu', type: 'number' },
    { name: 'materialLinkType', label: 'Malzeme Bağ. Tipi', type: 'number' },
    { name: 'materialLinkId', label: 'Malzeme Bağ. Kodu', type: 'number' },
    { name: 'ignoreSplit', label: 'Bölme Dikkate Alınsın', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'operation-forbidden-products': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'cariLinkType', label: 'Cari Bağ. Tipi', type: 'number' },
    { name: 'cariLinkId', label: 'Cari Bağ. Kodu', type: 'number' },
    { name: 'materialLinkType', label: 'Malzeme Bağ. Tipi', type: 'number' },
    { name: 'materialLinkId', label: 'Malzeme Bağ. Kodu', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'operation-conversions': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'statusId', label: 'Statü', type: 'ref', refResource: 'statuses' },
    { name: 'conversionCode', label: 'Dönüşüm Kodu', type: 'text', required: true },
    { name: 'outgoing', label: 'Giden', type: 'bool' },
    { name: 'sourceLocLinkType', label: 'Kaynak Lok. Bağ. Tipi', type: 'number' },
    { name: 'sourceLocLinkId', label: 'Kaynak Lok. Bağ. Kodu', type: 'number' },
    { name: 'targetLocLinkType', label: 'Hedef Lok. Bağ. Tipi', type: 'number' },
    { name: 'targetLocLinkId', label: 'Hedef Lok. Bağ. Kodu', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'sequential-operations': [
    { name: 'facilityId', label: 'Tesis', type: 'ref', refResource: 'facilities' },
    { name: 'firstOperationId', label: 'İlk Operasyon', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'secondOperationId', label: 'İkinci Operasyon', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'cariLinkType', label: 'Cari Bağ. Tipi', type: 'select', options: SCOPE_OPTS },
    { name: 'cariLinkId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'materialLinkType', label: 'Malzeme Bağ. Tipi', type: 'select', options: SCOPE_OPTS },
    { name: 'materialLinkId', label: 'Ürün', type: 'ref', refResource: 'products' },
    { name: 'locationLinkType', label: 'Lokasyon Bağ. Tipi', type: 'select', options: SCOPE_OPTS },
    { name: 'locationLinkId', label: 'Lokasyon', type: 'ref', refResource: 'locations' },
    { name: 'useInWorkOrder', label: 'İş Emrinde Kullanılsın', type: 'bool' },
    { name: 'spName', label: 'SP Adı', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'auto-reference-documents': [
    { name: 'sourcePartnerId', label: 'Kaynak Cari', type: 'ref', required: true, refResource: 'partners' },
    { name: 'sourceOperationTypeId', label: 'Kaynak Operasyon', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'sourceLocLinkType', label: 'Kaynak Lok. Bağ. Tipi', type: 'number' },
    { name: 'sourceLocLinkId', label: 'Kaynak Lok. Bağ. Kodu', type: 'number' },
    { name: 'targetPartnerId', label: 'Hedef Cari', type: 'ref', required: true, refResource: 'partners' },
    { name: 'targetOperationTypeId', label: 'Hedef Operasyon', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'targetLocLinkType', label: 'Hedef Lok. Bağ. Tipi', type: 'number' },
    { name: 'targetLocLinkId', label: 'Hedef Lok. Bağ. Kodu', type: 'number' },
    { name: 'facility', label: 'Tesis', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'operation-bulk-actions': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'bulkActionType', label: 'Toplu İşlem Tipi', type: 'number' },
    { name: 'description', label: 'Açıklama', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'product-additional-groups': [
    { name: 'productId', label: 'Ürün', type: 'ref', required: true, refResource: 'products' },
    { name: 'groupId', label: 'Grup', type: 'ref', required: true, refResource: 'product-groups' },
    { name: 'sortOrder', label: 'Sıra', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'product-based-collections': [
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', required: true, refResource: 'partners' },
    { name: 'sourceOperationTypeId', label: 'Kaynak Operasyon', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'targetOperationTypeId', label: 'Hedef Operasyon', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'exemptLocations', label: 'Muaf Lokasyonlar', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'trip-based-collections': [
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', required: true, refResource: 'partners' },
    { name: 'sourceOperationTypeId', label: 'Kaynak Operasyon', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'targetOperationTypeId', label: 'Hedef Operasyon', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'document-status-actions': [
    { name: 'documentStatusId', label: 'Belge Durumu', type: 'ref', required: true, refResource: 'document-statuses' },
    { name: 'actionType', label: 'İşlem Tipi', type: 'number', required: true },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'document-status-criteria': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'businessPartnerId', label: 'Cari', type: 'ref', refResource: 'partners' },
    { name: 'criteria', label: 'Kriter (ifade)', type: 'text', required: true },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'document-approval-types': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'approvalType', label: 'Onay Tipi', type: 'number', required: true },
    { name: 'controlCollection', label: 'Toplama Kontrolü', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'label-types': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'labelName', label: 'Etiket Adı', type: 'text' },
    { name: 'screenTitle', label: 'Ekran Başlığı', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  units: codeName(),
  reasons: codeName(),
  'product-groups': codeName(),
  'product-subgroups': codeName(),
  'product-types': codeName(),
  'product-detail-types': codeName(),
  'operation-groups': codeName(),
  'partner-groups': codeName(),
  regions: codeName(),
  statuses: codeName(),
  'pallet-types': [
    { name: 'code', label: 'Palet No Öneki (Kod)', type: 'text', required: true },
    { name: 'name', label: 'Tanım', type: 'text', required: true },
    { name: 'facilityId', label: 'Tesis', type: 'ref', refResource: 'facilities' },
    { name: 'sequenceId', label: 'Sayaç', type: 'ref', refResource: 'sequences' },
    { name: 'palletNoLength', label: 'Palet No Uzunluğu', type: 'number' },
    { name: 'mixingType', label: 'Tip', type: 'select', options: [{ value: 'SINGLE_PRODUCT', label: 'Tek Ürün Palet' }, { value: 'MIXED', label: 'Karma Palet' }] },
    { name: 'isDivisible', label: 'Bölünebilir', type: 'bool' },
    { name: 'partialUse', label: 'Parçalı Kullanım Yapılsın', type: 'bool' },
    { name: 'singleProductControl', label: 'Tek Ürün Kontrolü', type: 'bool' },
    { name: 'batchControl', label: 'Batch Kontrol Yapılsın', type: 'bool' },
    { name: 'newNoOnEdit', label: 'Düzenlemede Yeni No Alsın', type: 'bool' },
    { name: 'breakParentPallet', label: 'Üst Palet Bozulsun', type: 'bool' },
    { name: 'breakPartialPallet', label: 'Parçalı Palet Bozulsun', type: 'bool' },
    { name: 'breakPalletOnTransfer', label: 'Transferde Palet Bozulsun', type: 'bool' },
    { name: 'removeFromPalletOnTransfer', label: 'Transferde Paletten Çıkarılsın', type: 'bool' },
    { name: 'keepFullPalletOnTransfer', label: 'Transferde Tamamı Hareket Eden Üst Palet Bozulmasın', type: 'bool' },
    { name: 'logging', label: 'Loglama', type: 'bool' },
    { name: 'logControl', label: 'Log Kontrol', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'operation-type-statuses': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'sourceStatusId', label: 'Kaynak Statü (boş=dış)', type: 'ref', refResource: 'statuses' },
    { name: 'targetStatusId', label: 'Hedef Statü', type: 'ref', required: true, refResource: 'statuses' },
    { name: 'sortOrder', label: 'Sıra', type: 'number' },
  ],
  'operation-type-locations': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'sourceLocationId', label: 'Kaynak Lokasyon', type: 'ref', refResource: 'locations' },
    { name: 'targetLocationId', label: 'Hedef Lokasyon', type: 'ref', refResource: 'locations' },
    { name: 'fixLocation', label: 'Lokasyon Sabit', type: 'bool' },
  ],
  'operation-type-reasons': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'reasonId', label: 'Neden', type: 'ref', required: true, refResource: 'reasons' },
    { name: 'isAutomatic', label: 'Otomatik', type: 'bool' },
  ],
  'location-capacities': [
    { name: 'locationLinkType', label: 'Lokasyon Bağ. Tipi', type: 'select', required: true, options: [{ value: 'LOCATION', label: 'Göz / Lokasyon' }, { value: 'LOCATION_GROUP', label: 'Lokasyon Grup' }] },
    { name: 'locationLinkCode', label: 'Lokasyon', type: 'ref', required: true, refResource: 'locations' },
    { name: 'materialLinkType', label: 'Malzeme Bağ. Tipi', type: 'select', options: [{ value: 'PRODUCT', label: 'Ürün' }, { value: 'PRODUCT_GROUP', label: 'Ürün Grup' }] },
    { name: 'materialLinkCode', label: 'Ürün/Grup', type: 'ref', refResource: 'products' },
    { name: 'quantity', label: 'Miktar', type: 'number' },
    { name: 'unitId', label: 'Birim', type: 'ref', refResource: 'units' },
    { name: 'palletQty', label: 'Palet Miktarı', type: 'number' },
    { name: 'toleranceQty', label: 'Tolerans Miktar', type: 'number' },
    { name: 'toleranceUnitId', label: 'Tolerans Birim', type: 'ref', refResource: 'units' },
    { name: 'width', label: 'En', type: 'number' },
    { name: 'length', label: 'Boy', type: 'number' },
    { name: 'height', label: 'Yükseklik', type: 'number' },
    { name: 'placementHeight', label: 'Yerleştirme Yüks.', type: 'number' },
    { name: 'dimensionUnitId', label: 'Boyut Birimi', type: 'ref', refResource: 'units' },
    { name: 'weight', label: 'Ağırlık', type: 'number' },
    { name: 'weightUnitId', label: 'Ağırlık Birim', type: 'ref', refResource: 'units' },
    { name: 'messageType', label: 'Mesaj Tipi', type: 'select', options: [{ value: 'ERROR', label: 'Hata' }, { value: 'WARNING', label: 'Uyarı' }] },
    { name: 'distributeToCells', label: 'Gözlere Dağıtılsın', type: 'bool' },
  ],
  'operation-type-pallet-types': [
    { name: 'operationTypeId', label: 'Operasyon Tipi', type: 'ref', required: true, refResource: 'operation-types' },
    { name: 'palletTypeId', label: 'Palet Tipi', type: 'ref', required: true, refResource: 'pallet-types' },
    { name: 'innerPalletTypeId', label: 'İç Palet Tipi', type: 'ref', refResource: 'pallet-types' },
  ],
  'entry-condition-types': codeName('Kod', 'Açıklama'),
  'exit-condition-types': codeName('Kod', 'Açıklama'),
  'routing-types': codeName('Kod', 'Açıklama'),
  warehouses: [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Ad', type: 'text', required: true },
    { name: 'facilityId', label: 'Tesis', type: 'ref', refResource: 'facilities' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  areas: [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Ad', type: 'text' },
    { name: 'warehouseId', label: 'Depo', type: 'ref', required: true, refResource: 'warehouses' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  locations: [
    { name: 'warehouseId', label: 'Depo', type: 'ref', required: true, refResource: 'warehouses' },
    { name: 'areaId', label: 'Alan', type: 'ref', refResource: 'areas' },
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Ad', type: 'text' },
    { name: 'type', label: 'Tip', type: 'select', options: [
      { value: 'SHELF', label: 'Raf' }, { value: 'FLOOR', label: 'Zemin' }, { value: 'RECEIVING', label: 'Mal Kabul' },
      { value: 'SHIPPING', label: 'Sevkiyat' }, { value: 'STAGING', label: 'Hazırlık' }, { value: 'QUARANTINE', label: 'Karantina' },
    ] },
    { name: 'barcode', label: 'Barkod', type: 'text' },
    { name: 'priority', label: 'Öncelik', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  vehicles: [
    { name: 'plateNo', label: 'Plaka', type: 'text', required: true },
    { name: 'name', label: 'Ad', type: 'text' },
    { name: 'type', label: 'Tip', type: 'select', options: [
      { value: 'TRUCK', label: 'Kamyon' }, { value: 'VAN', label: 'Panelvan' }, { value: 'CAR', label: 'Otomobil' }, { value: 'MOTORCYCLE', label: 'Motosiklet' },
    ] },
    { name: 'capacityKg', label: 'Kapasite (kg)', type: 'number' },
    { name: 'capacityM3', label: 'Kapasite (m³)', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'routing-rules': [
    { name: 'routingTypeId', label: 'Yönlendirme Tipi', type: 'ref', refResource: 'routing-types' },
    { name: 'materialLinkType', label: 'Malzeme Bağ. Tipi', type: 'select', required: true, options: [{ value: 'PRODUCT', label: 'Ürün' }, { value: 'PRODUCT_GROUP', label: 'Ürün Grup' }] },
    { name: 'materialLinkCode', label: 'Ürün/Grup', type: 'ref', required: true, refResource: 'products' },
    { name: 'locationLinkType', label: 'Lokasyon Bağ. Tipi', type: 'select', required: true, options: [{ value: 'LOCATION', label: 'Göz / Lokasyon' }, { value: 'LOCATION_GROUP', label: 'Lokasyon Grup' }] },
    { name: 'locationLinkCode', label: 'Lokasyon/Grup', type: 'ref', required: true, refResource: 'locations' },
    { name: 'priority', label: 'Öncelik', type: 'number' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  facilities: [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Ad', type: 'text', required: true },
    { name: 'city', label: 'Şehir', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  'product-units': [
    { name: 'productId', label: 'Ürün', type: 'ref', required: true, refResource: 'products' },
    { name: 'unitId', label: 'Birim', type: 'ref', required: true, refResource: 'units' },
    { name: 'multiplier', label: 'Çarpan (baz birim adedi)', type: 'number' },
    { name: 'barcode', label: 'Barkod', type: 'text' },
    { name: 'isBaseUnit', label: 'Baz Birim', type: 'bool' },
    { name: 'batchTracking', label: 'Parti Takibi', type: 'bool' },
    { name: 'serialTracking', label: 'Seri Takibi', type: 'bool' },
  ],
  'location-groups': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Ad', type: 'text', required: true },
    { name: 'isWorkOrderGroup', label: 'İş Emri Grubu', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  sequences: [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Tanım', type: 'text', required: true },
    { name: 'isAutomatic', label: 'Otomatik', type: 'bool' },
    { name: 'prefix', label: 'Ön Ek', type: 'text' },
    { name: 'prefix2', label: 'Ön Ek-2 (SSP)', type: 'text' },
    { name: 'padLength', label: 'Hane Sayısı', type: 'number' },
    { name: 'startNo', label: 'Başlangıç No', type: 'number' },
    { name: 'endNo', label: 'Bitiş No', type: 'number' },
  ],
  parameters: [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Tanım', type: 'text' },
    { name: 'value', label: 'Değer', type: 'text' },
  ],
  'barcode-types': [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Tanım', type: 'text' },
    { name: 'parseScript', label: 'Parse Script (regex/ifade)', type: 'text' },
    { name: 'isProductionBarcode', label: 'Üretim Barkodu', type: 'bool' },
  ],
  printers: [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Ad', type: 'text' },
    { name: 'type', label: 'Tip', type: 'select', options: [{ value: 'IPP', label: 'Ağ (IPP)' }, { value: 'ZPL', label: 'Termal (ZPL/Zebra)' }, { value: 'SYSTEM', label: 'Sistem / Tarayıcı' }] },
    { name: 'host', label: 'IP / Host', type: 'text' },
    { name: 'port', label: 'Port', type: 'number' },
    { name: 'path', label: 'IPP Yolu (ör. /ipp/print)', type: 'text' },
    { name: 'location', label: 'Konum', type: 'text' },
    { name: 'isDefault', label: 'Varsayılan', type: 'bool' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
  partners: [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Ünvan', type: 'text', required: true },
    {
      name: 'type',
      label: 'Tip',
      type: 'select',
      options: [
        { value: 'CUSTOMER', label: 'Müşteri' },
        { value: 'SUPPLIER', label: 'Tedarikçi' },
        { value: 'BOTH', label: 'Her İkisi' },
      ],
    },
    { name: 'partnerGroupId', label: 'Cari Grubu', type: 'ref', refResource: 'partner-groups' },
    { name: 'regionId', label: 'Bölge', type: 'ref', refResource: 'regions' },
    { name: 'parentId', label: 'Üst Cari (zincir)', type: 'ref', refResource: 'partners' },
    { name: 'taxNumber', label: 'Vergi No', type: 'text' },
    { name: 'phone', label: 'Telefon', type: 'text' },
    { name: 'email', label: 'E-posta', type: 'text' },
    { name: 'city', label: 'Şehir', type: 'text' },
  ],
  products: [
    { name: 'code', label: 'Kod', type: 'text', required: true },
    { name: 'name', label: 'Ad', type: 'text', required: true },
    { name: 'unitId', label: 'Ana Birim', type: 'ref', required: true, refResource: 'units' },
    { name: 'barcode', label: 'Barkod', type: 'text' },
    { name: 'isActive', label: 'Aktif', type: 'bool' },
  ],
}

export const hasForm = (resource: string) => resource in FORM_CONFIG

export const canWrite = (): boolean => {
  try {
    const u = JSON.parse(localStorage.getItem('og_user') ?? '{}')
    return Boolean(u?.isSuperAdmin) || (u?.roles ?? []).some((r: string) => ['ADMIN', 'OPERATOR'].includes(r))
  } catch {
    return false
  }
}
