// Parametre REHBERİ — legacy TBLSBPARAMETRETANIM birebir dökümü (STOKBAR_UNI, 71 tanım — bozuk-Türkçe duplikeler ayıklandı).
// Parametreler ekranında Kod bu rehberden seçilir (StokBar davranışı); listede kod bu etiketle çözülür.
// Yeni tanım gerektiğinde buraya eklenir (katalog statik referans verisidir).
export const PARAM_CATALOG: { value: string; label: string }[] = [
  { value: "AcikBelgeMenusuEklensin", label: "AcikBelgeMenusuEklensin — Açik Belge Menüsü Eklensin" },
  { value: "AktifAy", label: "AktifAy — Aktif Ay Bilgisi" },
  { value: "AndroidAnaMenüResimAdres", label: "AndroidAnaMenüResimAdres — Android Ana Menü Resim Adresi" },
  { value: "AndroidFirmaLogoPath", label: "AndroidFirmaLogoPath — Android Firma Logo Path Adresi" },
  { value: "AyKapanisTarihi", label: "AyKapanisTarihi — Ay Kapanis Tarihi" },
  { value: "AyniBirimBarkodFarkliUrunKullanilsin", label: "AyniBirimBarkodFarkliUrunKullanilsin — Ayni Birim Barkod Farkli Ürünlerde Kullanilabilir" },
  { value: "BarkodAktartimiYapilsin", label: "BarkodAktartimiYapilsin — Ürün aktariminda barkod aktarimi da yapilsin" },
  { value: "BarkodLoglamasiYapilsin", label: "BarkodLoglamasiYapilsin — Barkod Loglamasi Yapilsin" },
  { value: "BatchBarkoduParseYapilsin", label: "BatchBarkoduParseYapilsin — Batch barkodu parse islemi için kullanilir." },
  { value: "BelgeOnayIptalKontrolGunSayisi", label: "BelgeOnayIptalKontrolGunSayisi — Belge Onay Iptali Geriye Dönük Gün Sayisi" },
  { value: "DEMenuIsimlerTamamenGorunsun", label: "DEMenuIsimlerTamamenGorunsun — Dinamik Etiketleme Menü Isimlerinin Tamami Gözüksün" },
  { value: "DizaynDosyaAdresi", label: "DizaynDosyaAdresi — Dinamik Etiketleme Dizayn Adresi" },
  { value: "DokumanYuklemeYolu", label: "DokumanYuklemeYolu — Doküman Yükleme Yolu" },
  { value: "EIrsaliyeUygulansin", label: "EIrsaliyeUygulansin — E-Irsaliye Uygulansin" },
  { value: "EkranlardaDetaySayisiBelgeDetaySayisiniGöstersin", label: "EkranlardaDetaySayisiBelgeDetaySayisiniGöstersin — EkranlardaDetaySayisiBelgeDetaySayisiniGöstersin" },
  { value: "ElTerminalindeMaxMiktarDegeri", label: "ElTerminalindeMaxMiktarDegeri — El Terminalinde Max Miktar Degeri" },
  { value: "EntegrasyonDBLinkAdi", label: "EntegrasyonDBLinkAdi — Entegrasyon DB Link Adi" },
  { value: "ER-FaturaTarihiEkSaha", label: "ER-FaturaTarihiEkSaha — Enroute Entegrasyonu Fatura Tarihi Ek Saha Kodu" },
  { value: "ER-FaturaTarihiOpTipi", label: "ER-FaturaTarihiOpTipi — Enroute Entegrasyonu Fatura Tarihi Operasyon Kodlari" },
  { value: "ER-SBAyniDBde", label: "ER-SBAyniDBde — Enroute ile Stokbar Ayni DB'de çalisiyor" },
  { value: "EslestirmeEkraniOperasyonTipi", label: "EslestirmeEkraniOperasyonTipi — Eslestirme ekraninda çikacak operasyon tipleri" },
  { value: "GozlemBasTarihiGunEkle", label: "GozlemBasTarihiGunEkle — Gözlem Baslama Tarihi Gün Ekle" },
  { value: "GozlemBitTarihiGunEkle", label: "GozlemBitTarihiGunEkle — Gözlem Bitis Tarihi Gün Ekle" },
  { value: "GozlemEkraniIslemTipi", label: "GozlemEkraniIslemTipi — Gözlem Ekrani Islem Tipi" },
  { value: "GumruklemeOperasyonu", label: "GumruklemeOperasyonu — Gümrükleme Isleminde Kullanilacak Operasyon Tipi" },
  { value: "HazirlananMiktarOperasyonTipiLokasyonaGoreHesapla", label: "HazirlananMiktarOperasyonTipiLokasyonaGoreHesapla — Hazirlanan Miktar Operasyon Tipi Lokasyona Göre Hesaplansin" },
  { value: "IOTSayimOperasyonTipi", label: "IOTSayimOperasyonTipi — IOT Sayim Operasyon Tipi" },
  { value: "IsAtamaKullaniciFiltresi", label: "IsAtamaKullaniciFiltresi — Is Atama Kullanici Filtresi" },
  { value: "IsEmriLokasyonGorevKodu", label: "IsEmriLokasyonGorevKodu — Is emri entegrasyonu görev kodu" },
  { value: "KaliteNumuneIslemTipi", label: "KaliteNumuneIslemTipi — Kalite Numune Islem Tipi" },
  { value: "KaliteNumuneOperasyonTipi", label: "KaliteNumuneOperasyonTipi — Kalite numune alimi isleminde olusacak belgenin operasyon tipi" },
  { value: "KaliteOpTipiNOK", label: "KaliteOpTipiNOK — Kalite Operasyon Tipi NOK" },
  { value: "KaliteOpTipiOK", label: "KaliteOpTipiOK — Kalite Operasyon Tipi OK" },
  { value: "MalBazindaIlkIslemTarihineGoreFiltre", label: "MalBazindaIlkIslemTarihineGoreFiltre — Mal bazinda toplama ekraninda sevkiyatlar ilk islem tarihine göre filtrelensin" },
  { value: "MalBazindaReferansaGoreFiltre", label: "MalBazindaReferansaGoreFiltre — Mal bazinda toplama ekraninda sevkiyatlar referans belge noya göre filtrelensin" },
  { value: "MalzemeBatchIcinSeriKontroluYapilsin", label: "MalzemeBatchIcinSeriKontroluYapilsin — Malzeme Batch Için Seri Kontrolu Yapilsin" },
  { value: "MalzemeIcinSeriKontroluYapilsin", label: "MalzemeIcinSeriKontroluYapilsin — Malzeme Için Seri Kontrolu Yapilsin" },
  { value: "MalzemeImportBatchIzlemeAcik", label: "MalzemeImportBatchIzlemeAcik — Malzeme Import Isleminde Batch Izleme Açik Olsun" },
  { value: "MalzemeImportSeriIzlemeAcik", label: "MalzemeImportSeriIzlemeAcik — Malzeme Import Isleminde Seri Izleme Açik Olsun" },
  { value: "MiktarOndalikHane", label: "MiktarOndalikHane — Ondalik Uzunluk" },
  { value: "NSPBaslamaTrhBosGelsin", label: "NSPBaslamaTrhBosGelsin — Nakliye Sevkiyat Parametre ekraninda Baslangiç Tarihi açilista bos gelsin." },
  { value: "NSPBolgeSeciliGelmesin", label: "NSPBolgeSeciliGelmesin — Nakliye Sevkiyat Parametre ekraninda Bölge tablosunda Tümünü Seç açilista bos gelsin." },
  { value: "OkutmaOperasyonTipiLokasyonSabit", label: "OkutmaOperasyonTipiLokasyonSabit — Okutmada Operasyon Tipi Lokasyon Sabitlensin" },
  { value: "PaletBolmeCikisOpTipi", label: "PaletBolmeCikisOpTipi — Palet Bölme Çikis Operasyon Tipi" },
  { value: "PaletBolmeGirisOpTipi", label: "PaletBolmeGirisOpTipi — Palet Bölme Giris Operasyon Tipi" },
  { value: "PaletBolmeOperasyonTipi", label: "PaletBolmeOperasyonTipi — Palet bölme isleminde kullanilacak operasyon tipi" },
  { value: "PaletBolmeRezerveMiktarKontrol", label: "PaletBolmeRezerveMiktarKontrol — Palet Bölme Isleminde Rezerve Miktar Kontrolü Yapilsin" },
  { value: "PaletOlusturmadaDetaylarGuncellensin", label: "PaletOlusturmadaDetaylarGuncellensin — Palet olusturma ekraninda detay listesi her okutmada güncellensin" },
  { value: "PaletResimAdres", label: "PaletResimAdres — Palet Resim Adresi" },
  { value: "PaletSilmeMesajiVerilsin", label: "PaletSilmeMesajiVerilsin — Paletlemede palet silindiginde silme mesaji verilsin" },
  { value: "PPCAltToplamAnaOlcudenGosterilsin", label: "PPCAltToplamAnaOlcudenGosterilsin — PPC Alt Toplam Ana Olcuden Gosterilsin" },
  { value: "PPCOndalikDegerSayisi", label: "PPCOndalikDegerSayisi — El Terminali Ondalik Uzunluk Degeri" },
  { value: "RFCKontrolsuzIskontoUygulansin", label: "RFCKontrolsuzIskontoUygulansin — Kontrolsüz belgelerde iskonto uygulansin parametresi isaretlenip ER'a gönderilsin" },
  { value: "SiparisAktarimAcikBelgeKontrolKisit", label: "SiparisAktarimAcikBelgeKontrolKisit — Siparis aktariminda açik belge kontrolü kisitli yapilsin" },
  { value: "StokbarScriptManagerAdress", label: "StokbarScriptManagerAdress — Barkod parsa için kullanilacak script manager adresi." },
  { value: "StokKontroldeDagitimSatisBirimindenYapilsin", label: "StokKontroldeDagitimSatisBirimindenYapilsin — Stok Kontrolde dagitim Satis Biriminden Yapilsin" },
  { value: "StokKontrolOpTipiLokasyonKullanilsin", label: "StokKontrolOpTipiLokasyonKullanilsin — Stok Kontrolde Operasyon Tipi Lokasyon Kullanilsin" },
  { value: "StokListeSayisi", label: "StokListeSayisi — Stok listesinde gösterilecek kayyt sayysy" },
  { value: "TekKullaniciKontrolSure", label: "TekKullaniciKontrolSure — Tek Kullanici Kontrolü Süresi (sn)" },
  { value: "TumDurumlarGelsin", label: "TumDurumlarGelsin — Üretim Gözlem Ekraninda Tüm Durumlar Gelsin" },
  { value: "TumMalzemelerIcinSeriKontroluYapilsin", label: "TumMalzemelerIcinSeriKontroluYapilsin — Tüm Malzemeler Için Seri Kontrolu Yapilsin" },
  { value: "UretimDinamikButonDegeri", label: "UretimDinamikButonDegeri — Üretime Bagli Belge Ekraninda dinamik buton isim ve degeri" },
  { value: "UretimGozlemTarihSecimi", label: "UretimGozlemTarihSecimi — Üretim Gözlem Tarih Seçimi" },
  { value: "UretimPlanSayaci", label: "UretimPlanSayaci — Üretim Plan Sayaci" },
  { value: "UrunDegisimiBelgeOperasyonu", label: "UrunDegisimiBelgeOperasyonu — Ürün Kod Degisim Belge Operasyon Tipi" },
  { value: "UrunDegisimiOperasyonu", label: "UrunDegisimiOperasyonu — Ürün Kod Degisim Operasyon Tipi" },
  { value: "UrunKodDegisimiTarihGonder", label: "UrunKodDegisimiTarihGonder — Ürün Kod Degisimi Tarih Gönder" },
  { value: "XMLDosyaAdresi", label: "XMLDosyaAdresi — Entegrasyonda kullanilan xmllerin tutuldugu adres" },
  { value: "YetkiliKullanici", label: "YetkiliKullanici — Yetkili Kullanici" },
  { value: "YuklemeSeferNoKontrol", label: "YuklemeSeferNoKontrol — Yüklemede Sefer No Kontrolü Yapilsin" },
  { value: "YüklemeYapilacakDepoKodu", label: "YüklemeYapilacakDepoKodu — Yükleme Yapilacak Depo Kodu" },
]
