-- AlterTable
ALTER TABLE "TBLDOCUMENT" ADD COLUMN     "documentStatusId" INTEGER;

-- AddForeignKey
ALTER TABLE "TBLDOCUMENT" ADD CONSTRAINT "TBLDOCUMENT_documentStatusId_fkey" FOREIGN KEY ("documentStatusId") REFERENCES "TBLDOCUMENTSTATUS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

